### ISSUE TITLE
Extend cssVariables to include all colors

### ISSUE THREAD

**Issue by miklb** [wprig/wprig#10]
## Issue Overview

Currently, the only color variable is `global-font-color` Was there a decision to not extend that to the rest of the colors used or is that open to a PR?

**Comment by mor10** [comment]
The current variables were provided as a baseline example more than anything. I'm not opposed to a PR that creates more variables for other colors.

**Comment by mor10** [comment]
Closing for now as no further discussion. feel free to reopen / submit PR.
