### ISSUE TITLE
Move footer styles in a separate file

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#100]
## Issue Overview
Actually, the footer styles are in `style.css` and are not critical because the footer is generally hidden when you load a page. 

If some styles are inherited from `content.css`, it force us to increase the specificity of our selectors in `style.css`, because `content.css`is loaded after `style.css`. 

## Possible Solution
These styles could be loaded later (before the footer markup) with a specific stylesheet.

**Comment by mor10** [comment]
The rules in `style.css` are minimal and provide a baseline for development. The idea is as your CSS gets more complex, you break it out into separate files, so if you want to completely overhaul the footer css, just pull it out of style.css and create a new custom file. That said, rules in `content.css` are meant to relate to post/page content only. If you want to override the footer styles, I recommend doing it either in `style.css` or in a dedicated `footer.css` file.

**Comment by benoitchantre** [comment]
Thank you @mor10 for your feedback on this.
