### ISSUE TITLE
Lazyload not working in 360 Browser， Cause all images not to appear ！！！

### ISSUE THREAD

**Issue by shangdev** [wprig/wprig#103]
## Issue Overview
Lazyload not working in 360 Browser， Cause all images not to appear ！！！

## Describe your environment
360 Browser

![image](https://user-images.githubusercontent.com/15621520/45068594-bd5b7400-b0fa-11e8-9b23-91a20c2343d7.png)

**Comment by mor10** [comment]
Can you provide a link to the 360 browser so I can test?
My guess is there is something going on with the JavaScript not loading.

**Comment by shangdev** [comment]
@mor10 
This is 360 browser.
https://browser.360.cn/se/

**Comment by mor10** [comment]
Looks to be a larger JS support issue with the browser. Closing for now.
