### ISSUE TITLE
Move browserlist to .browserlistrc?

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#105]
Allows for coop between tools without extended config settings.

**Comment by scriptex** [comment]
Instead of introducing another file, why not move it to package.json?

**Comment by mor10** [comment]
@ai made a good point here: By having it as a stand-alone file, it is crystal clear to users what's going on and where to change the settings. If it's in `package.json` it can easily get buried.

**Comment by ataylorme** [comment]
Closed by #227
