### ISSUE TITLE
Use BEM or any other CSS selector isolation

### ISSUE THREAD

**Issue by ai** [wprig/wprig#109]
## Issue Overview

We should force component isolation mindset in `dev/`

## Expected Behavior

Use component name prefix in selectors:

```css
.comments_title,
.comments_reply-title {
}

.comments_list {
}
```

```css
.comment_content a {
}

.comments_author  {
}
```

## Current Behavior

Right now there is no system behind classes in `dev/css`:

```css
.comment-content a {
}

.bypostauthor {
}

.comments-title,
.comment-reply-title {
}

.comment-list {
}
```

## Possible Solution

In my experience system behind CSS selector is very useful even for small projects.

Current React community force the same way.

BTW, maybe we can try to use `postcss-modules` since it will allow us to use CSS Modules with PHP templates.

https://evilmartians.com/chronicles/postcss-modules-make-css-great-again

## Related Issues and/or PRs

https://github.com/wprig/wprig/issues/108

**Comment by mor10** [comment]
I want to explore a rational implementation of BEM in WP Rig. To do so we need to recruit someone who has experience with BEM and wants to take on this project. volunteers / nominations welcome.

**Comment by spencerfinnell** [comment]
Interested in everyone’s thoughts about core-defined class names that can’t be changed or integrations with 3rd party plugins. The idea of a unified CSS system is great in theory but impossible to implement in WordPresss in my opinion. Every plugin will use their own convention (or none). 

Is the best solution to just get as far as possible with what can be controlled in the theme and use that as a “best practice” for further integrations?

**Comment by spencerfinnell** [comment]
In that regard is it worth overriding core/plugin PHP functions to change class names or is it more maintainable to document the non-conformity in the CSS?

**Comment by mor10** [comment]
@spencerfinnell Scope it to the theme - ie what we can control. Long-term, we can find a clean solution and then suggest migrating it up the chain into WP core. Lots of teams and packages use some version of this approach already. What I want us to explore is a best-practice approach which can be adopted by the majority of developers.

**Comment by spencerfinnell** [comment]
Great. Would love to see a standard be set for themes and a proposal for updating core markup to match. 

No BEM pro but I have been using it and I’ll definitely be watching this.

**Comment by ai** [comment]
I am thinking about these steps:

1. Use class isolation in `wprig` classes.
2. Use class isolation in `dev/` to force developers to use it in their own code.
3. Use class isolation in third-party classes.

Also let’s not stop on BEM. CSS Modules could be much better. We just need to parse JSON and pass results to PHP. It is harder but provides better isolation level (and CSS will be cleaner). So we should at least consider it.

**Comment by mor10** [comment]
@ai I'd like to see an example of what the modules approach would look like. One of the goals with this project is to level up theme developers without introducing things that are too different from how they normally work.

**Comment by ai** [comment]
An example of what the modules approach would look like:

```css
.list {
  …
}
.isEmpty {
   …
}
```

```php
<div class="<?= styles.list ?>">
</div>
```

(I am not sure about HTML template in PHP, maybe there is some syntax sugar in PHP to make `<?= styles.list ?>` cleaner.

More details: https://evilmartians.com/chronicles/postcss-modules-make-css-great-again

**Comment by mor10** [comment]
WordPress has a pretty robust syntax and filtering system which would allow for this. I need to read some more to wrap my head around it.

**Comment by spencerfinnell** [comment]
@ai the barrier to entry should also be considered. That technique might be great and I’d love to see it but the WordPress audience should be considered and WPRigs target audience should be defined. 

Starting with just BEM style CSS separated from the templating seems like a more manageable first step.

**Comment by mor10** [comment]
We can think of this as an "upgrade plan": Start with BEM, then when people get used to it, add in some CSS modules, etc.

**Comment by justintadlock** [comment]
@mor10 - I saw your callout on Twitter and thought I'd chime in.

We spent the better part of this year ~~hotly debating~~ _calmly and rationally discussing_ how to best handle this in the Mythic starter.  Feel free to borrow anything that we've done or improve upon it.  I'd love to see what y'all come up with.

**What we used:**

We used BEM with the addition of some utility classes (i.e., `.is-example`, `.has-example`).

We also used the ITCSS system for organizing.  It's handling of "components" fits in nicely with the "block" concept from BEM.

**What we targeted:**

Primarily, we focused on getting the classes that the theme actually has direct control over.  Coming up with a standard naming system for that was a tough enough job.

Then, we tackled areas where core WP has filter hooks.  And, covering several of those is simply a reality to get core's output to match up with some of the theme stuff.

**Comment by spencerfinnell** [comment]
What has worked well(ish) for me in the past is defining my own components via SCSS mixins which can properly use BEM. Then for 3rd party (including core) integrations map the random class names to the components defined by the theme. 

`.comment` can include a `@media` mixin. `.comment-author` can me `@media__figure` ‘`.comment-body` can be `@media__content`

It allows for multiple integrations to use the same system and it prevents having to maintain PHP templates (which can completely stop working on updates). A slightly wonky looking page when a plugin updates is better than a totoally broken page just so the defined class name can be “correct”.

**Comment by mor10** [comment]
This is why I love working with open source, and WordPress in particular. Thank you for chiming in on this @justintadlock. I'm hoping as both our projects move forward, we'll be able to learn and borrow from each other. Something something rising tide lifts all themes.

**Comment by mor10** [comment]
@spencerfinnell Well, Sass is already wired in and waiting ;o)

**Comment by mor10** [comment]
Also, if I remember correctly, there are some pretty fancy plugins and features in PostCSS that do much of what Sass does without the necessity of Sass...

**Comment by mor10** [comment]
OK, so how do we get started, and who wants to drive this bus?

**Comment by DavidWells** [comment]
If you use PostCSS you will have full access to the AST (abstract syntax tree) of the css to manipulate/scope it however you wish.

It's basically like Babel but for CSS

Checkout https://davidwells.io/blog/what-is-postcss/ and https://gist.github.com/DavidWells/9e4436608b834f1d3c0346db3631d774#gistcomment-2053946 for what postCSS + CSS modules are capable of.

You can also use less/sass/whatever with postcss

**Comment by muggeridge** [comment]
RE: BEM in WP Rig - it sounds good - as a developer I would prefer all the little bugs are fully ironed out before any major development is implemented. I am keen to get started with WP Rig however I am getting so many emails with bug fixes that I have little confidence that it okay to go ahead and deploy WP Rig, which is a shame as it hase so many benefits.

**Comment by mor10** [comment]
@muggeridge WP Rig, like all things, is a work in progress. For clarity, the BEM discussion will likely end up in v1.2 which is several months out. We're moving toward a stable v1.1 which will be a major upgrade, and a stable one at that.

**Comment by andreyberezhnoy** [comment]
What do you think about this solution? 
https://matlipe.com/using-postcss-modules-in-php/

**Comment by mor10** [comment]
We'll punt BEM and a full CSS rethink to v1.2 and make it the focus of the release. That way we'll have time to think carefully about what CSS should look like in WP themes today and in the future.

**Comment by robruiz** [comment]
I believe this has been addressed since we now use PostCSS.
