### ISSUE TITLE
Fix Jetpack integration not being loaded

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#112]
## Issue Overview
There is a `inc/jetpack.php` file for integration with Jetpack, but it is never loaded. A clause should be added to `functions.php`, similar as in https://github.com/Automattic/_s/blob/master/functions.php#L158.

## Steps to Reproduce
1. Install and activate Jetpack.
2. Notice that the theme integration with Jetpack features such as infinite scroll is not available.

## Expected Behavior
The Jetpack integration should load when the plugin is active.

## Current Behavior
The Jetpack integration never loads.

**Comment by mor10** [comment]
merged
