### ISSUE TITLE
Fix WordPress Coding Standards violations

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#115]
## Issue Overview
WordPress Coding Standards 1.0 and 1.1 include a couple of new sniffs, some of which WP Rig violates. Those occurrences should be fixed. This currently does not show up in Travis-CI, but that is only because the current setup (which is being improved in #114) has the old version 0.14.x hard-coded.

## Steps to Reproduce
1. Use WordPress Coding Standards in version ^1.0.
2. See the violation errors.

## Expected Behavior
Coding standards should not be violated.

## Related Issues and/or PRs
#22, #114

**Comment by mor10** [comment]
merged
