### ISSUE TITLE
Remove contributing.md from bundle?

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#118]
Are we supposed to remove/update the CONTRIBUTING.md?

Acutally, it contains information how to contribute to WP Rig and is part of the bundle created by `npm run bundle`. I think we should not include it in the bundle if it is supposed to stay unchanged.

**Comment by benoitchantre** [comment]
Yes

**Comment by mor10** [comment]
Opinion @ataylorme?

**Comment by ataylorme** [comment]
@mor10 we should consider creating a production bundle. See my comment in #101. Maybe something  to consider for ‘v1.1’?
