### ISSUE TITLE
WPRIG_MINIMUM_WP_VERSION constant not defined in WPRIG 1.1 branch

### ISSUE THREAD

**Issue by ev3rywh3re** [wprig/wprig#120]
## Issue Overview

Just quickly noting a PHP constant error. Maybe also related to #104. This is in the WPRIG 1.1 branch.

`WPRIG_MINIMUM_WP_VERSION constant not defined.` 

## Describe your environment

Personal Vagrant WordPress setup using Debian/Stretch64 with Apache2, MariaDB 10.1.26, and PHP7.0. My local npm environment is on MacOS  10.13.6. I'm still cleaning up both environments while looking for a great new team to work with since my development environment was on my previous employers' systems. Fortunately MacOS 10.13.6 has many of the WPRIG perquisites.

## Steps to Reproduce

1. Follow instructions for WPRIG using the WPRIG 1.1 branch.
2. PHP errors should be evident and mine were shown as part of the linting process.

## Possible Solution

Simple fix! Just need to see if WPRIG wants to standardize some of these variable settings and how they might conflict with WPRIG variable name replacements.

**Comment by felixarntz** [comment]
This should have been fixed by https://github.com/wprig/wprig/commit/fe102137e00eee0a9deb786d6b24db81ce4104b9 (see #111). @ev3rywh3re Can you update to the latest version of the 1.1 branch and check if the error persists?

**Comment by ev3rywh3re** [comment]
Looks good to me! Must have just missed the commit. Closing this now.
