### ISSUE TITLE
Facilitate assets versioning

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#122]
At the moment, assets use a date string that you can forget to update when you release a new version of the theme. We could improve that by using a `WP_RIG_THEME_VERSION` constant to reduce the number of changes to make for a release.

Ideally, the version number would be set in one place (themeConfig.js ?) and changed by the build / bundle script.

**Comment by mor10** [comment]
We had a lengthy discussion about this earlier. I just can't find it right now.
