### ISSUE TITLE
Improve SASS error logging

### ISSUE THREAD

**Issue by maximls** [wprig/wprig#128]
## Issue Overview
When there is a user error in SASS the build process continues and the error message gets lost in the log.

## Describe your environment
VS Code and FlyWheel server

## Steps to Reproduce

1. Make a mistake in SASS
2. Watch the build process complete and reload the page
3. Do NOT see CSS changes on the site (hit reload 5 times thinking it's cached while knowing that it's not)

## Expected Behavior

Either the build process fails with an error message (as it does in standalone SASS compilers) or display SASS success/fail message at the end of the log output where it is easily visible. 

## Current Behavior

The build completes and the SASS error is not easily visible in the log output.

## Possible Solution
I'm not an expert in build tools so I'm not sure how to go about fixing it. I hope there are other contributors more knowledgeable in this area. I think resolving this will help new developers adopt WPRig successfully.

**Comment by mor10** [comment]
Take a look at the v1.1 branch and see if it's better there. @ataylorme has rewired the entire build process.

**Comment by andreibarbuta** [comment]
I have a solution to this ( Credit to Zell Liew [ https://zellwk.com/ ] )

// We need to install: gulp-plumber and gulp-notify and add them to our gulp vars / const list:
var plumber = require("gulp-plumber");
var notify = require("gulp-notify");

// In the sassStyles function we replace:
.pipe(sass().on('error', sass.logError))
with:
.pipe(customPlumber("Error Running Sass"))

And watch the magic, this will bring up Windows / Mac OS native notification system.

NOTE: Works with CSS too

**Comment by ataylorme** [comment]
@andreibarbuta thanks for the sample code! I used that as a starting point.

@maximls can you test #224? The build process won't stop on sass errors but they should be much more visible in the system notifications.

**Comment by maximls** [comment]
@ataylorme I tested and everything looks great! Thanks for working on it.

**Comment by ataylorme** [comment]
Closed by #224
