### ISSUE TITLE
readme.txt is missing

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#130]
[Themes are recommended to include a readme.txt file, using plugin directory’s readme.txt markdown format.](https://developer.wordpress.org/themes/release/writing-documentation/) This recommendation will soon become required.

**Comment by mor10** [comment]
Should be easy enough to make based on `README.md`.

**Comment by benoitchantre** [comment]
I think ˋREADME.md` is about the framework but ˋreadme.txt` belongs to the theme built from the framework. It will the contain information used by wordpress.org like the description of the theme, the changelog, etc.

**Comment by felixarntz** [comment]
We might want to look into mechanisms like https://github.com/xwp/wp-dev-lib/blob/master/generate-markdown-readme, to prevent us from having to do duplicate work with `readme.txt` and `README.md`.

I like the idea of providing a proper `readme.txt` file with the starter theme - on the other hand, that is only relevant for themes to be released on wordpress.org. Maybe an additional flag in the theme config file could help with determining that.
