### ISSUE TITLE
Incorrect value in the 'calc()' expression

### ISSUE THREAD

**Issue by kudesa** [wprig/wprig#135]
## Issue Overview

Incorrect value in the 'calc()' function. 
## Describe your environment

Example: file style.css line 478
font-size: calc(var(--global-font-size) / 16)rem;
![image](https://user-images.githubusercontent.com/1862552/46574863-2c0a4680-c9b3-11e8-9bd8-0d25555f074c.png)
The syntax of a calc() function is wrong. Missing unit of measure in brackets.

in file editor-style.css
line 8, 141, 145, 149, 153

## Possible Solution
I think there is no need for calc.

Specification:
https://drafts.csswg.org/css-values-3/#calc-notation

Working version, but I would prefer a preprocessor
font-size: calc(1rem * var(--global-font-size) / 16);

**Comment by mor10** [comment]
Proposed solution added and merged. Thanks @kudesa!
