### ISSUE TITLE
Menu Toggle Often not Working in Various Browsers

### ISSUE THREAD

**Issue by WolfEsq** [wprig/wprig#136]
## Issue Overview
The menu toggle often does not work in some browsers. I have encountered this in a couple of ways: (1) In Firefox, resize the window and click the menu toggle, (2) In Firefox, refresh the window (leaving it small so the menu toggle shows), and then click the menu toggle, or (3) In Chrome for Android, load the  and click the menu toggle, refresh, and try again. 

After a couple of tries, you will notice that the menu toggle stops opening the menu. You will also see a JavaScript error in the console  `TypeError: SITENAV is null`.

NOTE: you may have to retry several times to reproduce the error. I have noticed that it doesn't happen every time I try to reproduce it. I have included more detailed steps below. 

I have only seen this error in Firefox and the Chrome browser for Android. So far, I cannot reproduce it in Chrome for desktop.

## Describe your environment

Fresh WordPress installation and fresh download of WP Rig. Imported WordPress Theme Unit Test xml.
Firefox version: `62.0.3 (64-bit)`
PHP version: `PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )`
Gulp version: `CLI version 2.0.1`
Composer version: `1.7.2 2018-08-16 16:57:12`
NodeJS version: `v10.11.0`
NPM version: `6.4.1`

## Steps to Reproduce

1. Clone wprig into themes folder
2. In the terminal, navigate to the `wprig` folder
3. Enter command `npm install`
4. Enter command `npm run build`
5. In the WordPress dashboard, activate the newly built WP Rig theme.
6. Logout and open your local site in Firefox
7. Resize the window until the menu toggle appears
8. Refresh the page (keeping the window size small)
9. Click the menu toggle. It will not open. (NOTE: you may have to retry steps 7-9 several times to reproduce the error. I have noticed that it doesn't happen every time I try to reproduce it.)
10. Open the browser console and note the JavaScript error `TypeError: SITENAV is null`

## Expected Behavior

I expected the menu toggle to reveal menu items.

## Current Behavior

The menu toggle does not open. JavaScript error `TypeError: SITENAV is null` appears in the console.

## Possible Solution

The problem appears to come from the way `navigation.js` is minified in the build process. I am able to bypass the error at first by changing this statement (starting on line 18 of `wprig/dev/js/navigation.js`):

```javascript
	// No point if no site nav.
	if ( undefined === SITENAV ) {
		return;
	}
```
Replacing it with the below modification will bypass the first instance of the error, but it will be thrown later in the file. This is not a solution, but it may be helpful.

```javascript
	// No point if no site nav.
	if ( ( undefined === SITENAV ) || ( null === SITENAV ) ) {
		return;
	}
```

## Screenshots / Video

![Screenshot](https://i.imgur.com/HCoIIIb.jpg)

**Comment by bamadesigner** [comment]
Thanks for the heads up @WolfEsq! I'll look into it.

**Comment by bamadesigner** [comment]
#140 should take care of it. Thanks @WolfEsq! If you can test the PR, I'd appreciate it.

**Comment by hazephase** [comment]
I am still having this problem, so I don't think it is fixed.

**Comment by idea--list** [comment]
Hi there,

I was really frustrated by the same issue and spent a few hours trying to debug it.
Tryed several things and ultimately this change in navigation.js seems to work reliable:

Change these lines
`document.addEventListener( 'DOMContentLoaded', function() {`
and `});` four lines below that

to
`window.onload = function () {`
and `}`

I know window.onload takes more time to get fulfilled as DOMContentLoaded, but this seems to work 100% reliable at least in Chrome for Android.

Am not sure if it is a JS core bug or does WP-rig do something in the background that makes DOMContentLoaded unreliable in mobile browsers. Interestingly enough on desktop browsers DOMContentLoaded works without causing this issue.

Please test this solution on other browsers as well.

**Comment by mor10** [comment]
Where are we on this?

**Comment by mor10** [comment]
Related: #438

**Comment by idea--list** [comment]
I think i have another solution that works on a site i made with WPRig v1.4.
However i can not double check it as npm intall throws a bunch of errors no matter if i chose V1.4 or V2 master. Which is the highest Node JS version that should work with WPRig on a Win 10 machine?

**Comment by milesdame** [comment]
I'm currently working on building a new theme and I'm encountering this problem. I downloaded the most recent version of wprig. Any thoughts?

**Comment by milesdame** [comment]
Hi all, I'm having an issue. I've added pages, but my menu still only says "Menu" and nothing happens when I click on it either. I just downloaded wprig two days ago and I'm not sure what to do.

**Comment by milesdame** [comment]
Since I had not actually started any customization yet I decided to scrap it and begin fresh again. I'm happy to report it is now working properly. I think I was the issue because I initially ran into some other problems that I tried to fix when running wprig initially.
