### ISSUE TITLE
Alignments for not found are not loaded 

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#138]
## Issue Overview
These styles are part of `content.css`, but the styelsheet is not loaded when there are no posts to display. See `index.php`, `search.php` and `404.php`.

## Steps to Reproduce

1. Search for a term that returns no result
1. See that the content is not aligned as expected because `content.css` is not loaded

## Expected Behavior
The content of `content-none.php` should be aligned as expected (centered, not full width).

## Current Behavior
The content of `content-none.php` uses full width.

## Possible Solution
We should either load `content.css` when there are no results or move the styles in `style.css`.

**Comment by bamadesigner** [comment]
#141 should address the issue. I've slated for v2.0 since its a possible breaking change.
