### ISSUE TITLE
`wp_print_styles()` is not recommended

### ISSUE THREAD

**Issue by kalenjohnson** [wprig/wprig#144]
## Issue Overview
`wp_print_styles()` is used [here ](https://github.com/wprig/wprig/blob/v1.0.4/dev/index.php#L28) to conditionally load CSS based on the current template/page. Good idea in theory, however I believe this can be used in a similar way with `wp_enqueue_scripts()` instead.

For reference, I thought this was a good idea I saw while Morten was demonstrating WP Rig at Wordcamp Vancouver 2018. Decided to research it a bit and found it's not a suggested way to load CSS anymore [since 2011](https://make.wordpress.org/core/2011/12/12/use-wp_enqueue_scripts-not-wp_print_styles-to-enqueue-scripts-and-styles-for-the-frontend/)

## Expected Behavior
The function isn't deprecated for some reason, however IMO any modern starter theme should use recommended conventions

## Possible Solution
Use `wp_enqueue_scripts()` for the current page/template conditionally

## Related Issues and/or PRs
https://make.wordpress.org/core/2011/12/12/use-wp_enqueue_scripts-not-wp_print_styles-to-enqueue-scripts-and-styles-for-the-frontend/

**Comment by kalenjohnson** [comment]
I'm actually a little confused by some of this wording.

The docs seem to reference both the hook name and the function: https://codex.wordpress.org/Plugin_API/Action_Reference/wp_print_styles

However the original make.wordpress.org link actually mentions it's the hook to not use, the function is fine: https://make.wordpress.org/core/2011/12/12/use-wp_enqueue_scripts-not-wp_print_styles-to-enqueue-scripts-and-styles-for-the-frontend/#comment-5319

So, I suppose the function is not necessarily suggested against, then...

**Comment by andreibarbuta** [comment]
wp_enqueue_style does not print the css resource into the page, you would need another function for that which would create code bloat.

wp_print_styles had some bugs that would sometimes print styles into the admin when used in functions.php, this cannot happen here, as it is only for a page dedicated to front-end. As far as I am aware there is no other function to insert styles into a page while also taking into account if they were already added.

**Comment by kalenjohnson** [comment]
That sounds reasonable. Sorry for my misunderstanding
