### ISSUE TITLE
Missing Help on "Progressive Web App enabled"

### ISSUE THREAD

**Issue by tedsecretsource** [wprig/wprig#150]
## Issue Overview

The readme doesn't contain any information on what "Progressive Web App enabled" consists of.

## Describe your environment

N/A

## Steps to Reproduce

N/A

## Expected Behavior

I was hoping to find some kind of brief description of how to enable common PWA features, such as making the site installable, specifying a custom offline error page, or even a setting that allows the caching of the home page by default.

## Current Behavior

No help info is available.

## Possible Solution

I am about to embark on a project that will require the three items listed above. If I am able to actually do these things, I'll write up some information and submit a pull request. If a PR already exists for this, please point me in that direction and I'll try to help :-)

**Comment by ivanjuras** [comment]
+1. Would like to know that, too. There's no manifest file, either.

**Comment by felixarntz** [comment]
The note on "Progressive Web App enabled" indicates that the theme supports WordPress PWA capabilities. It doesn't add the necessary functionality to WordPress itself, there is a [PWA feature plugin](https://github.com/xwp/pwa-wp) developed currently though, which you can install (be aware that it is in an early development stage). The idea is to add the functionality to WordPress core at some point in the future.

WP Rig adds support for the PWA plugin, that is what the information means. Please refer to the PWA plugin for more information on how to make use of it.

**Comment by GitaStreet** [comment]
You'll want the mentioned plugin. For a child the implementation take a look at this repo.
https://github.com/westonruter/twentyseventeen-westonson?files=1

**Comment by tedsecretsource** [comment]
Sorry for commenting on a closed case but this is very interesting and useful. Thank you @felixarntz and @GitaStreet for the pointers. I've also found https://wordpress.org/plugins/super-progressive-web-apps/ which works well enough as a starting point for how it should be done.

Thanks again and great work on the rig!

**Comment by GitaStreet** [comment]
@tedsecretsource 
Thanks. Will try that plugin also. 

Found this step by step guide today for adding theme support for AMP and PWA:
https://github.com/Automattic/amp-wp/pull/1519

wp_debug didn't like the  'app_shell' => true and some of it's a little over my head right now.
