### ISSUE TITLE
Can't install packages

### ISSUE THREAD

**Issue by inweb-pro** [wprig/wprig#158]
```
41501 verbose Windows_NT 10.0.14393
41502 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Alex Inweb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
41503 verbose node v10.13.0
41504 verbose npm  v6.4.1
41505 error code ELIFECYCLE
41506 error errno 1
41507 error wprig@1.0.4 install: `composer install`
41507 error Exit status 1
41508 error Failed at the wprig@1.0.4 install script.
41508 error This is probably not a problem with npm. There is likely additional logging output above.
41509 verbose exit [ 1, true ]
```

I stopped [at this step](https://wprig.io/learn/run-the-wp-rig-installer/).
Guys, what's the problem?

Windows 10
node -v && npm -v
v10.13.0
6.4.1

**Comment by mor10** [comment]
You need to install Composer. Here are instructions for how to install it on Windows: https://getcomposer.org/doc/00-intro.md#installation-windows

**Comment by SimonParfittCode** [comment]
Hi Mor10,

I'm having the same issue as inweb-pro. I'm very keen to start using WPRIG, as currently use _underscores start theme & Codekit 3 for developing WordPress websites, but feel maybe this is out-of-date and want to start using modern tools.

So, after downloading the WPRIG files, I then running the "npm install" command I get the error:

<img width="913" alt="Screenshot 2019-05-27 at 13 19 33" src="https://user-images.githubusercontent.com/1633650/58419676-26b55580-8083-11e9-8997-bce0941f76e0.png">

I'm sure I have install composer globally though, when I run the command "composer --version" I get the result of 1.8.5 and running command "composer" I get the attached screenshot.

<img width="917" alt="Screenshot 2019-05-27 at 13 20 02" src="https://user-images.githubusercontent.com/1633650/58419677-26b55580-8083-11e9-98c1-bc4da1802a82.png">

I'm new to the world of the command line, scary, so not sure what I'm doing wrong - please help, so eager to start using WPRIG.

Many Thanks ,
Simon
