### ISSUE TITLE
Use PHP7-supported language features

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#159]
## Issue Overview
WP Rig requires PHP 7.0 as a minimum. However, its codebase is entirely PHP 5.2 code. There's no point in missing out on all of the language features the more modern PHP versions provide, and more importantly, as a progressive WordPress theme, WP Rig should also make use of modern PHP practices.

Here is what I suggest:
* Add a `WP_Rig\WP_Rig` namespace for all PHP files, except for `functions.php` and `inc/back-compat.php`, which need to remain PHP 5.2-compatible.
* With the namespace in place, get rid of the unnecessary `wp_rig_` prefixes for functions and other PHP constructs. This allows for shorter and more readable function names.
* Use parameter and return type hints throughout the codebase, where applicable.
* Encourage security by using functions like `filter_input()` instead of direct access to superglobals, where applicable.
* Use function closures in places when a reusable function makes absolutely no sense, where applicable.

Just to define the scope of this issue a bit better: This is *not* about rewriting the codebase to follow modern design patterns, object-oriented programming or similar. While that might arguably improve some things, I would say there aren't enough benefits in theme development to take on the efforts for this.

Using PHP best practices while staying *within* the typical boundaries of theme development however is a necessity to move WordPress and the web forward.

cc @hellofromtonya for feedback / iteration on these ideas

**Comment by benoitchantre** [comment]
I think the namespace structure should offer some flexibility: we should be able to use a different value for the first level and be able to add other levels if needed.

This could be done with the addition of a `namespace` key in themeConfig.js and a specific search-replace during the build.

**Comment by mikeselander** [comment]
As someone who spent quite a few hours fixing namespaces, standards, etc. last week on a wprig project this change would be a _huge_ improvement. There's no reason not to use modern PHP7 features on a new theme framework these days so I'd ❤️ to see improvements here.

> Add a `WP_Rig\WP_Rig` namespace for all PHP files, except for functions.php and inc/back-compat.php, which need to remain PHP 5.2-compatible.

Why do these need to remain PHP 5.2-compatible?

Also, could the namespace be `WP_Rig\Theme` or similar? Dual `WP_Rig`s feels redundant and when replacing for a client project we would likely use `Client\Theme\Whatever` naming ourselves which would make the initial find/replace much easier.

**Comment by felixarntz** [comment]
@mikeselander 
> Why do these need to remain PHP 5.2-compatible?

That is because WordPress core doesn't impose any restrictions, and we wanna make sure we don't WSOD sites of users who are unaware of PHP and theme requirements. These are only bootstrap files without actual code anyway, so that's a fair tradeoff I'd say.

> Also, could the namespace be `WP_Rig\Theme` or similar?

I'd prefer to go with `WP_Rig\WP_Rig`, as it's the most common convention to have the namespace be defined as `Vendor_Name\Package_Name`, which in this specific case match. I'm in favor of @benoitchantre's suggestion of making the namespace configurable though, so a theme based on WP Rig could use anything they'd like.

**Comment by ataylorme** [comment]
> That is because WordPress core doesn't impose any restrictions, and we wanna make sure we don't WSOD sites of users who are unaware of PHP and theme requirements. These are only bootstrap files without actual code anyway, so that's a fair tradeoff I'd say.

I respectfully disagree and think we should have the include files follow a standard, such as psr-4, and be autoloaded with Composer. If we are going to modernize PHP practices we should do so all the way, not part of the way.

**Comment by felixarntz** [comment]
@ataylorme @mikeselander 
WordPress is a user-centric software, and while we are building a modern theme framework, we should still make decisions based on their sanity/benefit weight, compared to possible downsides. We should absolutely use modern PHP features, however fatal-erroring a user's site is an absolute no-go.

While WP Rig is for developers, the end results developers build with it are for users. And not only for super tech-savvy users, but also for the average WordPress user. We don't want to build a niche hardcore-dev theme that attracts only a few very advanced folks. We want to build a theme that is pretty much as easy to use and develop as other themes are, with the benefit that _this_ one uses modern best practices. We can only move WordPress and the web forward if we improve the situation for the entire ecosystem, not just for a select few.

Furthermore, by fatal-erroring on inexperienced users' sites, we simply lock them out and give them a terrible UX. If we instead fail gracefully and display a warning that they need a higher version of PHP, they will know what's wrong, can learn about it and update.

> I respectfully disagree and think we should have the include files follow a standard, such as psr-4, and be autoloaded with Composer. If we are going to modernize PHP practices we should do so all the way, not part of the way.

I generally agree, with the following caveats:
* `functions.php` is loaded by WordPress, so it's not controllable by an autoloader anyway. When we implement autoloading, this file would simply include `vendor/autoload.php`. No point in using something higher than 5.2 code for the ~5 lines of code needed for this.
* Autoloading only works with classes, however WordPress themes are not class-based. This is something we can improve, but it would require an entire rewrite, so this would potentially be material for v3 or later.

**Comment by ataylorme** [comment]
> While WP Rig is for developers, the end results developers build with it are for users. And not only for super tech-savvy users, but also for the average WordPress user

The WP Rig documentation says PHP 7 or greater required. I think we should enforce this, not just say it. WP Rig is for developers and by enforcing PHP 7 rather than suggesting it will encourage those developers to have discussions with the users of the themes they are building about their PHP version.

> Furthermore, by fatal-erroring on inexperienced users' sites, we simply lock them out and give them a terrible UX. If we instead fail gracefully and display a warning that they need a higher version of PHP, they will know what's wrong, can learn about it and update.

We can hook into theme activation and disallow the theme to be activated and display such a warning

**Comment by samikeijonen** [comment]
> This is what WP Rig does at the moment. And the code that does it needs to be 5.2-compatible. This is what I mean exactly, so I'm not sure what the problem is.

Plus one from me, that's the way to do it.

**Comment by ataylorme** [comment]
I misunderstood what was going on here and what @felixarntz was proposing. We chatted over Slack and I now understand and agree with him that we should have a minimum version that reflects the version WP Rig is compatible with and a recommended version, which is higher.

**Comment by felixarntz** [comment]
Fixed via #185.
