### ISSUE TITLE
Look into adding app shell support through AMP

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#160]
## Issue Overview

The AMP plugin will soon provide a way to enable an app-shell experience in WordPress, where page transitions are seamless, as in: When you click a link that leads to another part of your site, the header and footer will remain the same while only the actual content is fetched and updated. Click events on these links are intercepted so that the whole page reload does not happen.

Adding theme support for this is rather trivial:
* `add_theme_support( 'amp', array( 'paired' => true, 'app_shell' => true ) )`
* place a call to `amp_start_app_shell_content()` in the location where the dynamic content starts (typically towards the end of `header.php`)
* place a call to `amp_end_app_shell_content()` in the location where the dynamic content ends (typically towards the beginning of `footer.php`)

This is still in development, but I wanted to open discussion around this. A crucial part is that the app shell feature, as nice as it is, requires AMP paired mode, since AMP does not yet support an app shell. Therefore a site would essentially need to decide between whether it wants to have app shell support or native AMP. In the future support might be added to AMP too, so we can get the best of both worlds.

It might be best not to do anything in this regard yet, but let's keep this on our radar.

cc @westonruter 

## Related Issues and/or PRs
* https://github.com/Automattic/amp-wp/pull/1519
* https://github.com/westonruter/twentyseventeen-westonson/pull/8

**Comment by robruiz** [comment]
AMP is no longer a priority for WP Rig.
