### ISSUE TITLE
Create a gulp task for replacing strings in the development theme

### ISSUE THREAD

**Issue by ataylorme** [wprig/wprig#165]
@felixarntz and @mor10 we need to decide if a task to run the string replacement in the development version of the theme, rather than always using WP Rig naming in development, is necessary.

One reason I can see for including it is so that names of hooks and filters in the theme that other code, such as a plugin, are using are consistent during development and production.

See [this discussion in #133](https://github.com/wprig/wprig/pull/133#discussion_r232367726) for background.

See [commit d5cf64b189257d2268c99432d15ac8b3517565ca](https://github.com/wprig/wprig/pull/133/commits/d5cf64b189257d2268c99432d15ac8b3517565ca) for the code to implement this.

**Comment by mor10** [comment]
I see the use case for this, and I think it's important. The key is to provide clear documentation around what happens when a developer uses this function, ie "when you make this change, you have to use your own prefix" etc.

Question: Is it possible to make a stepped process in Gulp? So when the developer runs `npm run gulp -- sourceStringReplacement` they get an alert in command line saying something like 

```
Do you want to change the prefix/sourceString/whateverWeCallIt in the development theme 
from "wp-rig" to "[insert configured string]"? Yes/No
```
That way the developer has a chance to bail if they didn't realize what the function does.

**Comment by ataylorme** [comment]
> Question: Is it possible to make a stepped process in Gulp? 

Yes, the [question query callback in the node readline API](https://nodejs.org/api/readline.html#readline_rl_question_query_callback) makes that trivial to implement.

**Comment by mor10** [comment]
Ok. I say go with that then. We can tweak the text during RC.

**Comment by ataylorme** [comment]
I'll wait for #133 then work on this.

> I see the use case for this, and I think it's important

Did you and @felixarntz come to a consensus on that? I don't have an opinion one way or another but want to make sure the team is on the same page.

**Comment by felixarntz** [comment]
I'm still leaning against this, but of course am open to discuss it. Having that task somewhere might be okay, but I'd say definitely not in `package.json`.

Either way, this is not breaking, so not super-critical. Could land any time. :)

**Comment by ataylorme** [comment]
@mor10 is this something you want to see in `2.0`? If so I can make a PR, otherwise lets punt or close this issue.

**Comment by ataylorme** [comment]
The production bundle step:
1) create the production directory
2) runs all the compilations/optimizations (PHP, JS, CSS, translations, etc.)
3) copies only necessary files, omitting files not needed for production (source files. README, etc)
4) does string replacement
5) optionally create a `.zip`

If string replacement were done on the dev copy of the theme the only difference between it and the prod bundle after `npm run build`, which runs all the compilations/optimizations, is that the non-production files would remain. 

That adds some file size weight to the theme but does not affect functionality.

@felixarntz see #246 as a use case for this. The recommended way of working is building a production theme but if some people do not wish to work that way and use the extra step allowing them to run the string replacement in the dev theme as a one-time task would provide a workaround.

Since we have the ability to provide that option, I disagree with not making it available. Even if our recommended approach is to use the source and production method we should not force users to adhere to it.

**Comment by mor10** [comment]
1. Add the gulp feature
2. Don't add it to `package.json`
3. Document for those interested

**Comment by ataylorme** [comment]
The consensus in the WP Rig meeting is that there can be a gulp task but it should not be a script in `package.json`.

We need to document this as well - it is ejecting from WP Rigs workflow.

**Comment by mor10** [comment]
Moving to future release because #298 is labeled as future release.

**Comment by robruiz** [comment]
I'm curious to know where we are at with this. Anyone have enough interest to dive back in and get it implemented?

**Comment by robruiz** [comment]
I believe this is already implemented.
