### ISSUE TITLE
Move remaining functions related to assets in assets.php

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#168]
Functions that manage the assets are now in assets.php, but following functions are still in template-functions.php:

- `wp_rig_filter_script_loader_tag()`
- `wp_rig_get_preload_stylesheet_uri()`
- `wp_rig_add_body_style()` (name is missleading)

They should be moved in assets.php.

**Comment by mor10** [comment]
Yes to this. We are marking it for `v2.0`. Are you working on a PR @benoitchantre?

**Comment by felixarntz** [comment]
Done via #169
