### ISSUE TITLE
Recent changes to style.css made the theme out of sync with the tutorial video

### ISSUE THREAD

**Issue by dmccan** [wprig/wprig#17]
Great job here and with the video series. 
## Issue Overview

The tutorial video gives an example of editing the CSS by making some changes to the menu. However, there were changes to the menu CSS a few days ago: "Optimizing main menu to be accessible". Now the github version and the tutorial example are out of sync. 

## Possible Solution

There may not be anything that could be done about this, but perhaps a note under the video or something might help avoid confusion for those doing the tutorial.

**Comment by solarianian** [comment]
I followed the video instructions last week, ended up with no menu items displayed. No menu elements (no <ul>, no <li>, no <a>) contained in html <navigation></navigation>.
I'll try again soon, from scratch.

**Comment by mor10** [comment]
I'll get this sorted. Thanks for reporting.

**Comment by mor10** [comment]
I found a couple of minor CSS errors which had snuck in during our rushed work to get WP Rig shipped with a fully accessible menu before WCEU. They are now resolved and the master branch provides the correct code again. Pull down the fresh version of style.css and you should see the demo from the course work as expected. Let me know if it works.
