### ISSUE TITLE
Add functions related to icons (svg)

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#174]
## Issue Overview
Most themes need icons for different purposes, including social menu, search, shopping cart, etc.
WP Rig could include related functions to do it the right way.

## Possible Solution

Could be based on [functions-icons.php](https://github.com/samikeijonen/checathlon/blob/master/inc/functions-icons.php) of Checathlon theme.

**Comment by mor10** [comment]
Duplicate-ish of #36. SVG is marked for `v2.1` release.
