### ISSUE TITLE
Duplicates styles in editor-styles.css

### ISSUE THREAD

**Issue by jdelia** [wprig/wprig#178]
## Issue Overview
There are three blocks of styles that are duplicated in the editor-styles.css. Stylelint flagged them. 

## Steps to Reproduce

Block on line 39 and 58 are duplicates. 53 and 72 are duplicates. 46 and 65 are duplicates.

## Possible Solution
Remove duplicates.

https://github.com/wprig/wprig/blob/v2.0/assets/css/src/editor/editor-styles.css

**Comment by mor10** [comment]
Will fix.

**Comment by jdelia** [comment]
Morten - I did a PR for you already. :) https://github.com/wprig/wprig/pull/179

**Comment by jdelia** [comment]
See # https://github.com/wprig/wprig/pull/179
