### ISSUE TITLE
Let readme.txt for the theme built on WP Rig

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#183]
`readme.txt` is a required file for themes distributed in wp.org repository. It should contains informations about the theme build with WP Rig.

I suggest to use something like below and to move the current content of `readme.txt` in another file that will not be part of the bundle. This content could be in the Wiki.

If you agree on that, how can we prevent the automattic replacement of `WP Rig`in the credits?

```
=== WP Rig ===

Contributors: 
Tags: 
Requires at least: 4.8
Tested up to: 4.9.8
Requires PHP: 7.0
Stable tag: 1.0.0
License: GPLv3 or later
License URI: http://www.gnu.org/licenses/gpl-3.0.html

Here is a short description of the theme.

== Description ==
This is the long description.  No limit, and you can use Markdown (as well as in the following sections).
 
For backwards compatibility, if this section is missing, the full length of the short description will be used, and
Markdown parsed.
 
A few notes about the sections above:
 
*   "Contributors" is a comma separated list of wp.org/wp-plugins.org usernames
*   "Tags" is a comma separated list of tags that apply to the plugin
*   "Requires at least" is the lowest version that the plugin will work on
*   "Tested up to" is the highest version that you've *successfully used to test the plugin*. Note that it might work on
higher versions... this is just the highest one you've verified.
*   Stable tag should indicate the Subversion "tag" of the latest stable version, or "trunk," if you use `/trunk/` for
stable.
 
Note that the `readme.txt` of the stable tag is the one that is considered the defining one for the plugin, so if the `/trunk/readme.txt` file says that the stable tag is `4.3`, then it is `/tags/4.3/readme.txt` that'll be used for displaying information about the plugin.  In this situation, the only thing considered from the trunk `readme.txt` is the stable tag pointer.  Thus, if you develop in trunk, you can update the trunk `readme.txt` to reflect changes in your in-development version, without having that information incorrectly disclosed about the current stable version that lacks those changes -- as long as the trunk's `readme.txt` points to the correct stable tag.
 
If no stable tag is provided, it is assumed that trunk is stable, but you should specify "trunk" if that's where you put the stable version, in order to eliminate any doubt.

== Installation ==

1. In your admin panel, go to Appearance > Themes and click the Add New button.
2. Click Upload Theme and Choose File, then select the theme's .zip file. Click Install Now.
3. Click Activate to use your new theme right away.

== Frequently Asked Questions ==

= Does this theme support any plugins? =

WP Rig includes support for Infinite Scroll in Jetpack.

== Changelog ==

= 1.0.0 =
* Initial release

== Credits ==

* Based on WP Rig https://wprig.io [GPLv3 or later](http://www.gnu.org/licenses/gpl-3.0.html)
* normalize.css https://necolas.github.io/normalize.css/, (C) 2012-2018 Nicolas Gallagher and Jonathan Neal, [MIT](https://opensource.org/licenses/MIT)

```

**Comment by mor10** [comment]
To the last question, I think we can shield this file from the rewrite in the build process @ataylorme?

**Comment by ataylorme** [comment]
@mor10 I don't think we can shield a specific section of a file from replacement. The entire file contents are in a single string in the file stream in gulp and the replacement runs on that string.

I think it would be easier to create a separate file with the credit section and then append that file content to the `readme.txt` after the production build and string replacement happens.

**Comment by mor10** [comment]
Suggestion from @ataylorme: Build two files: `readme.txt` and `credits.txt` to get merged on build. `readme.txt` gets processed and string replace occurs. `credits.txt` gets merged without string replace.

**Comment by ataylorme** [comment]
@mor10 #297 makes changes so that string replacements do *not* happen in `readme.txt`. We can update documentation accordingly. With that being the case, I don't think `credits.txt` is necessary.

The more I think about it I don't think it is a good idea to append WP Rig credits in the readme regardless. This is open source software and if someone chooses not to give credit where it is due that is their prerogative.

**Comment by mor10** [comment]
@ataylorme Credits should remain in `readme.txt` for clarity. It's also important for organizations and companies with strict OSS policies (my company is an example). Since no rewriting happens in that file, I see no need to split the two files up. 

Does that mean we can close this issue?

**Comment by ataylorme** [comment]
@mor10 yes, I think we can close as #297 resolved the issue
