### ISSUE TITLE
Modularize PHP codebase

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#186]
## Issue Overview
As a follow-up to #159, let's modularize the PHP codebase to leverage further modern best practices such as autoloading and a more error-proof approach to coding a theme.

Currently the PHP codebase consists of the following files:
* `inc/assets.php`
* `inc/customizer.php`
* `inc/image-sizes.php`
* `inc/setup.php`
* `inc/template-functions.php`
* `inc/template-tags.php`
* `pluggable/lazyload/lazyload.php`
* `pluggable/custom-header.php`
* `pluggable/jetpack.php`

(There is also `inc/back-compat.php`, but this is only for graceful fallback for old setups, and `functions.php` that only serves as an entry point to loading the other files - these can be ignored here.)

All these files are currently full of functions, which by their definition are all publicly accessible from anywhere. This is a bad practice and makes it almost impossible to not break backward-compatibility when making _any_ change. It is also precisely why WordPress core is as locked-in to that problem as it is today. The only file which contains functions the theme developer needs to actually call is `inc/template-tags.php` - the rest are just internal.

Therefore I suggest the following:
* Move all the above files in the `inc` directory to a new `inc/core` directory. Then transform each of them into a class containing the functionality, to scope them better and protect outside access to the parts which should just not be accessed from the outside. As with #159, the actual functionality remains the same. Each of these classes should have an `register()` method to start it up and hook it into WordPress.
* Move all the above files in the `pluggable` directory to a new `inc/modules` directory. Then transform each of them into a class as well, similar to those in `inc/core`, with the significant difference that these ones are modules which can easily be loaded or not loaded, without the theme breaking. Each of these classes should have an `register()` method to start it up and hook it into WordPress.
* This will leave us with only `template-tags.php` in the `inc` directory, making it obvious that these are functions intended to be used by the theme developer from the outside, i.e. the actual PHP templates.
* `functions.php` can then be used to initialize all core classes and module classes as necessary. Furthermore we can leverage PHP autoloading so only the files we actually need are lazy-loaded on request.

This provides a solid foundation from which we can iterate in the future without further breaking changes. As #159 is already taken care of via #185, I could start with this right after - again, should not take a long time, I think we should do this for 2.0.

**Comment by mor10** [comment]
I say "yes" as long as we update documentation. We also need to provide some sort of "how do I use this when the tutorial I'm reading says things work completely differently" guide.

**Comment by felixarntz** [comment]
Absolutely. I'm happy to work on this once WP Rig 2.0 is close to final.

**Comment by ataylorme** [comment]
Merged in #220
