### ISSUE TITLE
Allow replacing namespace in gulp task

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#192]
As a follow-up to #185, we should allow developers to easily replace the `WP_Rig\WP_Rig` namespace throughout.

Replacements like this one are already part of the gulp production build task, however it will currently simply replace `WP_Rig`, causing the namespace to always have the same vendor as package part in its name. However, we need to account for cases where a developer wants the namespace to be something like `The_Author\The_Theme`, or anything else (possibly consisting of more than 2 parts). Therefore I think we should make the entire `WP_Rig\WP_Rig` string replaceable with a custom namespace, in addition to the existing strings. One thing we would need to make sure though is that that specific replacement would need to fire before the other ones - specifically all instances of `WP_Rig\WP_Rig` need to already have been replaced before the `WP_Rig` instances are replaced.

This is not mission-critical for 2.0, but the sooner we have it the better.

cc @ataylorme

**Comment by ataylorme** [comment]
Merged in #204
