### ISSUE TITLE
Question: should we convert stylesheets to scss?

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#203]
Styles for the color palette and the editor show repetitive code.

By using Sass, they could be edited more efficiently. [See example from  Bill Erickson](https://www.billerickson.net/building-a-gutenberg-website/#use-sass).

What are your opinions?

**Comment by mor10** [comment]
I want to avoid forcing the use of Sass. The same effect can be achieved using CSS custom properties and processed via PostCSS.

**Comment by ataylorme** [comment]
https://codepen.io/jakealbaugh/post/css4-variables-and-sass is an interesting read

**Comment by ataylorme** [comment]
With #281 merged I no longer this we should switch to Sass by default

**Comment by benoitchantre** [comment]
Thank you all for your opinions and this interesting read. Feel free to close this issue.
