### ISSUE TITLE
Screenshot in production theme cannot be viewed

### ISSUE THREAD

**Issue by luminuu** [wprig/wprig#225]
Not sure if this is a huge issue, but I just came across this while testing WP Rig at WCUS Contributor Day.

## Issue Overview

After running the build process, it's not possible to open the screenshot.png in the production theme. It is displaying when viewing the WP admin Themes page though.

## Describe your environment

OS: macOS Mojave
WP Rig: v2.0 branch

## Steps to Reproduce

1. Get a local copy of WP Rig.
2. Optional, but easier to check: update the screenshot.png so it's not just a transparent image.
3. Run `npm run bundle`.
4. Try to open the screenshot.png in the production theme. It won't open.

## Expected Behavior

The screenshot.png should be opened in macOS Preview or Photoshop.

## Current Behavior

macOS Preview says: "The file "screenshot.png" could not be opened. It may be damaged or use a file format that Preview doesn't recognize."
Adobe Photoshop CC 2019 says: "Not a PNG file"

## Possible Solution

I assume that the Gulp process may be the source of this issue.

**Comment by ataylorme** [comment]
@luminuu thank you for the bug report. Can you test the fix in #254?

**Comment by ataylorme** [comment]
Closed by #254 in the `v2.0` branch
