### ISSUE TITLE
Coding standards check - don't use WordPress

### ISSUE THREAD

**Issue by dingo-d** [wprig/wprig#23]
## Issue Overview
Hi!

I saw that you are using 4 rulesets in the `phpcs.xml.dist`

https://github.com/wprig/wprig/blob/acae4c38c1c121ba5f81a3ae4a73208186d4dfb2/phpcs.xml.dist#L36-L39

Loading the `WordPress` coding standard will load `WordPress-VIP, Core, Docs and Extra` and that is not necessary for the themes on wordpress.org.

## Possible Solution
We are currently working on [`WordPress-Theme`](https://github.com/WPTRT/WordPress-Coding-Standards) standard, which will soon be separated into its own standard, that is meant just for the theme checking. So you can use this one for the time being. I think you'd only need to add this to your composer

```json
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/WPTRT/WordPress-Coding-Standards"
  }
],
"require": {
  "wp-coding-standards/wpcs": "dev-feature/theme-review-sniffs",
  "wimg/php-compatibility": "*"
},
```

and you can then use it as `<rule ref="WordPress-Theme"/> ` in the ruleset :)

**Comment by mor10** [comment]
@dingo-d Can you create a PR for this?

**Comment by mor10** [comment]
WPCS was updated to 1.0.0 which means this is no longer relevant. Closing.

**Comment by dingo-d** [comment]
I'll create a PR once we defork the [Theme coding standards](https://github.com/WPTRT/WordPress-Coding-Standards)
