### ISSUE TITLE
BrowserSync not loading site after entering URL in themeConfig.js

### ISSUE THREAD

**Issue by digisavvy** [wprig/wprig#232]
## Issue Overview
There is confusion when running the theme for the first time. By default, the theme has `'wprig.test:8888'`. For some folks, the might think that `8888` should be part of the URL. I had issues with the browsersync loading the site when I prepended my local URL to port `8888`. When I removed `8888` the site loaded in browsersync just fine.

## Describe your environment

This happens on my local setup. I'm using VS Code and Chrome for the browser.

## Steps to Reproduce

1. Clone the theme to the theme folder
2. Run `npm install`
3. Adjust themeConfig.js to your needs (make sure `:8888` is part of the proxyUrl string).
3. Run `npm run dev` and then the browser tab will open and try to load the site where it will hang and not load anything. 
4. 

## Expected Behavior

The site should have loaded.

## Possible Solution

The docs should explicitly state what to enter for the proxyURL.

**Comment by bamadesigner** [comment]
@mor10 Basically the issue here is confusion that, because the `:8888` is included in the default URL example, that you need a port in your local URL. When most likely you do not. I propose the best solution is simply to remove the `:8888` from the base config. Can you think of any reason not to? Was there a reason for including it initially?

**Comment by tanmalik786** [comment]
@bamadesigner I believe you can set proxyURL exactly like the URL you use to access your local site in your browser [like localhost/wprig or wprig.local whatever it's without the http or https part] and then can experiment with bypassPort to see if the Browsync loads well - for me bypassPort: 8181 worked just fine.

**Comment by mor10** [comment]
@bamadesigner The reason for including it is _if_ you need a port, you also need to know where it goes. This looks like a documentation problem to me.

**Comment by benoitchantre** [comment]
This will probably be part of #284.
