### ISSUE TITLE
IDs for headings in documentation page.

### ISSUE THREAD

**Issue by Shelob9** [wprig/wprig#235]
It would be super helpful if I could link to headings in the docs. If I could say `for installation instructions, see https://wprig.io#install-dependencies` or similar.
 
<img width="1058" alt="screen shot 2018-12-09 at 10 58 24 pm" src="https://user-images.githubusercontent.com/1994311/49711629-0c3b0d00-fc06-11e8-94d5-90e24efdc988.png">

**Comment by mor10** [comment]
Done. Closing.
