### ISSUE TITLE
MAC npm ERR! Error: EACCES: permission denied

### ISSUE THREAD

**Issue by scottheappey** [wprig/wprig#237]
## Issue Overview
I can't install NPM or run the build. Saying npm ERR! Error: EACCES: permission denied and gulp issues ...

## Describe your environment
I'm running MAMP Pro on Mac. I did a fresh install in a new folder called Development. Macintosh HD⁩/Development⁩/

## Steps to Reproduce
1. 
'use strict';

module.exports = {
	theme: {
		slug: 'slhd',
		name: 'SLHD',
		author: 'SH'
	},
	dev: {
		browserSync: {
			live: true,
			proxyURL: 'slhd:8888',
			bypassPort: '8181'
		},
		browserslist: [ // See https://github.com/browserslist/browserslist
			'> 1%',
			'last 2 versions'
		],
		debug: {
			styles: false, // Render verbose CSS for debugging.
			scripts: false // Render verbose JS for debugging.
		}
	},
	export: {
		compress: true
	}
};

2. 
Scotts-MacBook-Pro:slhdtheme scottheappey$ sudo npm install
Password:

> fsevents@1.2.3 install /Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.3 and node@11.4.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents
node-pre-gyp ERR! node -v v11.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> node-sass@4.9.0 install /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/vendor/darwin-x64-67 : { Error: EACCES: permission denied, mkdir '/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:775:3)
    at sync (/Development/slhd/wp-content/themes/slhdtheme/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Development/slhd/wp-content/themes/slhdtheme/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/vendor' }

> node-sass@4.9.0 postinstall /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags=--libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@11.4.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:160:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:160:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:13:12)\n    at F (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:68:19)\n    at E (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:80:29)\n    at /Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:89:16\n    at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/index.js:42:5\n    at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/mode.js:8:5\n    at FSReqCallback.oncomplete (fs.js:160:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 11.4.0
gyp verb command install [ '11.4.0' ]
gyp verb install input version string "11.4.0"
gyp verb install installing version: 11.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 11.4.0
gyp verb build dir attempting to create "build" dir: /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=""--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/scottheappey/.npm/_logs/2018-12-10T19_21_01_123Z-debug.log

3. 
Scotts-MacBook-Pro:slhdtheme scottheappey$ sudo npm install
Password:

> fsevents@1.2.3 install /Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.3 and node@11.4.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Development/slhd/wp-content/themes/slhdtheme/node_modules/fsevents
node-pre-gyp ERR! node -v v11.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> node-sass@4.9.0 install /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/vendor/darwin-x64-67 : { Error: EACCES: permission denied, mkdir '/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:775:3)
    at sync (/Development/slhd/wp-content/themes/slhdtheme/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Development/slhd/wp-content/themes/slhdtheme/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/vendor' }

> node-sass@4.9.0 postinstall /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags=--libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@11.4.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:160:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:160:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:13:12)\n    at F (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:68:19)\n    at E (/Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:80:29)\n    at /Development/slhd/wp-content/themes/slhdtheme/node_modules/which/which.js:89:16\n    at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/index.js:42:5\n    at /Development/slhd/wp-content/themes/slhdtheme/node_modules/isexe/mode.js:8:5\n    at FSReqCallback.oncomplete (fs.js:160:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 11.4.0
gyp verb command install [ '11.4.0' ]
gyp verb install input version string "11.4.0"
gyp verb install installing version: 11.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 11.4.0
gyp verb build dir attempting to create "build" dir: /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass/build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/Development/slhd/wp-content/themes/slhdtheme/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=""--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Development/slhd/wp-content/themes/slhdtheme/node_modules/node-sass
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/scottheappey/.npm/_logs/2018-12-10T19_21_01_123Z-debug.log
Scotts-MacBook-Pro:slhdtheme scottheappey$ npm run build
npm ERR! path /Users/scottheappey/.npm/_logs/2018-12-08T02_45_19_910Z-debug.log
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink
npm ERR! Error: EACCES: permission denied, unlink '/Users/scottheappey/.npm/_logs/2018-12-08T02_45_19_910Z-debug.log'
npm ERR!     at Object.unlinkSync (fs.js:974:3)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:336:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at Glob.emit (events.js:189:13)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!  { Error: EACCES: permission denied, unlink '/Users/scottheappey/.npm/_logs/2018-12-08T02_45_19_910Z-debug.log'
npm ERR!     at Object.unlinkSync (fs.js:974:3)
npm ERR!     at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/npm.js:336:20
npm ERR!     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)
npm ERR!     at Glob.emit (events.js:189:13)
npm ERR!     at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)
npm ERR!     at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)
npm ERR!     at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, unlink '/Users/scottheappey/.npm/_logs/2018-12-08T02_45_19_910Z-debug.log'\n    at Object.unlinkSync (fs.js:974:3)\n    at Function.rimrafSync [as sync] (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:306:17)\n    at /usr/local/lib/node_modules/npm/lib/npm.js:336:20\n    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)\n    at Glob.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:151:7)\n    at Glob.emit (events.js:189:13)\n    at Glob._finish (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:197:8)\n    at done (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:182:14)\n    at Glob._processReaddir2 (/usr/local/lib/node_modules/npm/node_modules/glob/glob.js:434:12)\n    at /usr/local/lib/node_modules/npm/node_modules/glob/glob.js:371:17",
npm ERR!   errno: -13,
npm ERR!   syscall: 'unlink',
npm ERR!   code: 'EACCES',
npm ERR!   path:
npm ERR!    '/Users/scottheappey/.npm/_logs/2018-12-08T02_45_19_910Z-debug.log' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

> wprig@1.0.4 build /Development/slhd/wp-content/themes/slhdtheme
> gulp

[06:22:35] Failed to load external module @babel/register
[06:22:35] Requiring external module babel-register
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Development/slhd/wp-content/themes/slhdtheme/gulpfile.babel.js:26:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at loader (/Development/slhd/wp-content/themes/slhdtheme/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Development/slhd/wp-content/themes/slhdtheme/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@1.0.4 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@1.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

4.

**Comment by Peech1502** [comment]
Hi,

i have the same problem! I hope for some help soon

**Comment by mor10** [comment]
This looks like a permission error - npm not being able to write to the directory. To test, try adding WP Rig to a different directory and run `npm install` again. It could be a configuration problem with the specific folder or environment you're working in or it could be related to security settings on your computer. Do a general Google search for "Error: EACCES: permission denied" and you'll see this is a problem a lot of people encounter when working with npm. It is not directly related to WP Rig itself.
