### ISSUE TITLE
Search results display full posts

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#251]
## Issue Overview

Without the `search.php` template, search results display full posts. This is not usefull for the end user. When there's a widget area, the developer of the theme doesn't control whether there will be a search widget or not. I think it's a good practice to keep this template enabled by default.

## Expected Behavior

Search results should always display an excerpt.

## Current Behavior

Search results display the full post because the `search.php` template is not used (in the optional directory).

## Possible Solution

Move `search.php` out of the optional directory.

**Comment by mor10** [comment]
Merged. Closing.
