### ISSUE TITLE
Error on npm run build

### ISSUE THREAD

**Issue by tiborp** [wprig/wprig#26]
Hi, 

I would love to chechout/use this theme. I managed to update to Gulp 4 and did a succesfull `npm install` but am getting an error when trying to run `npm run build`

```
Failed to load external module @babel/register
[15:16:46] Requiring external module babel-register
/Users/tibor/Sites/wprig/wp-content/themes/wprig/node_modules/matched/lib/promise.js:8
module.exports = async function(patterns, options) {
                       ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tibor/Sites/wprig/wp-content/themes/wprig/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@1.0.0 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@1.0.0 build script.
```
Can't really figure out what's happening that causes this error, so hoping for suggestions :-)

Thanks in advance!

Cheers , Tibor

**Comment by ygagnon** [comment]
I'm having the exact same issue.  Have you had any success in resolving this yet?  If so, how?

**Comment by ygagnon** [comment]
I succeeded at getting it to build without errors.  In order to do so, I had to do a few things:

1) I updated NPM to the latest version
2) I double checked my VS Code settings and fixed one of the lines pertaining to "composerJsonPath" (I'd forgotten to include the "composer.json" filename).
3) I re-ran "npm install"
4) I re-ran "npm run build"

{
	"phpcs.enable": true,
	"phpcs.composerJsonPath": "wp-content/themes/[yourThemeFolder]/**composer.json**",
	"phpcs.standard": "WordPress",
	"editor.renderWhitespace": "all"
}

- Yvan

**Comment by mor10** [comment]
This looks to be an issue with Node/NPM versions. try updating Node and NPM and see if that helps. The composer.json part @ygagnon is referring to would not impact the build process, only whether or not PHPCS is active in the editor itself.

**Comment by gnujach** [comment]
Thank, update version of node and npm work for me!!

**Comment by tiborp** [comment]
I also manged to fix it by updating node & npm. Somehow in my package.json, gulp 3.9 was added as a dev dependency, so I had to change that to 4.0 before the run build command could be executed, but changing that to 4.0 did the trick.

Thanks for your help!

**Comment by bamadesigner** [comment]
I'm going to close this issue as it seems to be resolved. Thanks!
