### ISSUE TITLE
themeConfig.js is being run numerous times during gulp

### ISSUE THREAD

**Issue by bamadesigner** [wprig/wprig#265]
## Issue Overview
I logged the results of the theme config merge during the gulp process and its logged at least 8 times. Which means the merge function is running 8+ times.

It would be great to clean up/cache this info so this code only runs once.

I was running on v2.0 branch.

**Comment by bamadesigner** [comment]
Ping @ataylorme.

**Comment by ataylorme** [comment]
@bamadesigner the [`getThemeConfig`](https://github.com/wprig/wprig/blob/v2.0/gulp/utils.js#L20:L59) helper function does cache the config, and uncached defaults to `false`.

Some tasks, such as [styles](https://github.com/wprig/wprig/blob/v2.0/gulp/styles.js#L22), call `getThemeConfig` with uncached set to `true`.

I think we need to audit where all such calls bypassing the cache are happening and determine if cache busting is necessary and eliminate any instances where it is not.

**Comment by bamadesigner** [comment]
@ataylorme I hear ya. It would be great if the merge was just run once on the build and stored. I can't think of a scenario where it needs to be run again to produce the same data unless we change the value during the build. Do we?

**Comment by ataylorme** [comment]
> I can't think of a scenario where it needs to be run again to produce the same data unless we change the value during the build.

@mor10 can weigh in here but I remember support for changing theme configuration on the fly was desired. One example would be toggling debugging for CSS/JS without needing to stop and restart gulp and the entire watch process.

Maybe we can make hot reload of the theme config a config variable?

**Comment by ataylorme** [comment]
> The need for reloading of the config file happens only when files which impact other files are changed, which was mainly around CSS

The mainly CSS portion is wrong - sass and JS are also currently getting an uncached copy as assets (CSS, JS and sass) aren't minified when debugging is on.

**Comment by ataylorme** [comment]
BrowserSync also uses an uncached copy so its settings can be changed on the fly as well

**Comment by mor10** [comment]
This might be confused or impossible, but here goes. Is this a solution?

- The `require-uncached` option is broken out into a separate task which outputs a variable.
- On first run, the variable is then used in place of `require-uncached` being called a bunch of times.
- On individual task runs, the `require-uncached` task is run only if required somehow.

**Comment by mor10** [comment]
It feels like it should be possible to just call the file once and then reuse the result, but considering individual tasks are called via `watch` they would somehow have to be able to know if some other task already triggered `require-uncached` and then either use the new cache or generate a new one based on the result. Cache busting of some sort? I'm having trouble visualizing the logic tree for this.

**Comment by ataylorme** [comment]
@mor10 I propose we disallow configuration to be changed while gulp is running. To me, it seems like something that will not be done often enough to have the benefit of stopping/restarting gulp outweigh the performance cost the other 99% of the time when gulp is running and configuration has not changed

**Comment by mor10** [comment]
Looping back around to this, I am leaning toward @ataylorme's sentiment: With CSS out of the config loop, any other config changes will be environment changes which don't really happen. I propose we disallow configuration changes during live runs as suggested by Andrew.

**Comment by ataylorme** [comment]
> I vote we disallow configuration changes during live runs as suggested by Andrew.

@bamadesigner or @felixarntz can we have one more +1 on this? If there is majority agreement I can make a PR

**Comment by bamadesigner** [comment]
@ataylorme I agree with this decision. PR time!

**Comment by ataylorme** [comment]
Closed by #394
