### ISSUE TITLE
v2.0 feature freeze

### ISSUE THREAD

**Issue by ataylorme** [wprig/wprig#269]
This issue is meant to discuss a feature freeze for `v2.0`. At the time of writing the [`2.0` milestone](https://github.com/wprig/wprig/milestone/2) is 70% complete. Over the last few months, we have continued to add to the scope of `v2.0`.

I would like to propose that all new features, not bug fixes, for `v2.0` should be proposed by January 17th, 2019 (two weeks from today).

Proposed features will then be reviewed/discussed in the WP Rig meeting on the 17th. Accepted feature proposals will be added to the `2.0` milestone and a feature freeze will be enforced.

The feature freeze will allow us to focus on merging existing pull requests and work on the accepted features in the `2.0` milestone.

Once all features in the `2.0` milestone have been merged into the `v2.0` branch we can release the `v2.0-beta` beta.

After the beta is released all effort will be focused on bug fixes, documentation, and testing.

The number of feature proposals made, and accepted, by the 17th will help determine a timeline for the beta.

@felixarntz has advocated for an extended testing period and I agree. After the beta is released I propose we test for 30 days. Additional beta releases can be made during that time. Then, depending on how the beta testing goes, we can either extend the beta testing period or move to a release candidate.

I think this timeline gives us a good chance of releasing `v2.0` by the end of quarter 1, 2019. I would love to hear what others have to say - feedback and discussion is highly encouraged.

**Comment by mor10** [comment]
Sounds reasonable.

**Comment by bamadesigner** [comment]
Sounds good to me. Thanks @ataylorme!

**Comment by benoitchantre** [comment]
Should proposed features be linked here?

**Comment by ataylorme** [comment]
> Should proposed features be linked here?

Yes, a link here would be good for visibility. Proposed features should have their own issue where conversation can take place.

**Comment by benoitchantre** [comment]
#173, #282 and #286

**Comment by ataylorme** [comment]
Open issues (as of this comment) have been reviewed and those determined to be needed for `2.0` have been added to the [`2.0` milestone](https://github.com/wprig/wprig/milestone/2). 

The feature freeze is now in effect with a target date of 1/31 for completion of the 29 open issues in the `v2.0` milestone.

**Comment by felixarntz** [comment]
Features are frozen, milestone is only bugs, documentation needs to be written. :)
