### ISSUE TITLE
Update documentation re: child themes

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#270]
State in `README.md` that WP Rig should not be used to build a child theme. See #260.

**Comment by jacklowrie** [comment]
Quote from Rachel Cherry on #260:

> To sum up our thoughts: WP Rig works great as a parent theme but is not intended for use as a child theme. WP Rig is built to lay a solid theme foundation, which is great for a parent theme, but not for a child theme. A child theme is meant to only add on or modify the foundation.
