### ISSUE TITLE
Browsers can't resolve CSS variables

### ISSUE THREAD

**Issue by luminuu** [wprig/wprig#271]
## Issue Overview

I just pulled the current state of v2.0 to a fresh installation. After setting it up, the CSS variables are not available, like `var(--global-font-family)`. 

## Describe your environment

Editor: VS Code
Browser: Firefox, Chrome, Safari
OS: macOS Mojave

## Steps to Reproduce

1. Pull WP Rig to a new directory.
2. Checkout branch `v2.0`
3. Do the setup routine.
4. Change the fonts in `config/cssVariables.json`.
5. Check the site. There are no changes to the fonts, just a fallback to a serif font.

## Expected Behavior

Changing the font entries in `cssVariables.json` also changes the fonts displayed on the site.

## Current Behavior

Safari does this:
![grafik](https://user-images.githubusercontent.com/7585600/50675152-79b34100-0fec-11e9-8042-b24a9235ff40.png)

Firefox does this:
![grafik](https://user-images.githubusercontent.com/7585600/50675173-9c455a00-0fec-11e9-835d-c5a16dc6b7e0.png)
(The message translates to `--global-font-family was not set`)

Chrome doesn't give any notice in the Dev Tools, however the issue is the same as in Firefox and Safari.

Font files get fully loaded from Google Fonts, no issue there.

## Possible Solution

Maybe switching to SASS files could help. Can anyone tell me why the variables are located in a .json file and not directly in the CSS?

## Related Issues and/or PRs

I guess #247 is related.

**Comment by bamadesigner** [comment]
Hi @luminuu! This PR will address the issue: https://github.com/wprig/wprig/pull/267

Thanks for reporting!
