### ISSUE TITLE
Additional assets don't get bundled

### ISSUE THREAD

**Issue by luminuu** [wprig/wprig#273]
## Issue Overview
I have created a theme with additional font files in the `assets` folder, in a `fonts` subdirectory. When bundling the theme for production, these assets don't get added.

## Describe your environment

macOS Mojave, recent clone of WP Rig (4th January)

## Steps to Reproduce

1. Have a WP Rig working environment ready.
2. Add a folder with some files to the `assets` folder, for example a web font.
3. Run `npm run bundle`.
4. Check the created theme's assets folder, the additional directory and files are missing.

## Expected Behavior

When adding additional assets, those should be bundled with the theme. In case of my example, I don't want to use Google Fonts for GDPR reasons. So I downloaded the webfonts and added them to the assets folder in a new directory, to avoid clutter in the other directories.

## Current Behavior

Additional files in the assets folder don't get bundled in the production theme.

## Possible Solution

Doing some Gulp magic to detect additional files and just copy them to the production theme.

**Comment by ataylorme** [comment]
> Doing some Gulp magic to detect additional files and just copy them to the production theme.

I'm not sure grabbing any extra files in assets is a good idea as there may be unintended files (OS files, code editor hidden files, etc.)

An alternative would be to specify which assets/additional assets to copy in [the configuration](https://github.com/wprig/wprig/blob/v2.0/config/config.default.json)

@luminuu would that work for you? For example, you would be able to add something like `assets/fonts/**/*{.woff,.ttf}` (only specific file extensions) or `assets/fonts/**/*` (all files in `assets/fonts`).

**Comment by luminuu** [comment]
@ataylorme That would absolutely work for me, I think it's the best solution for this. I thought about this way today too but you were faster writing it down here :)

**Comment by ataylorme** [comment]
@luminuu with PR  #297 you can now add an `additionalFilesToCopy` array to `config.json` under `export.compress`. Here is the example I tested with font files:

```
{
    "export": {
        "compress": false,
        "additionalFilesToCopy": [
            "assets/fonts/**/*{.woff,.ttf,.ttc}"
        ]
    }
}
```

If you can help test the PR that would be 💯

**Comment by luminuu** [comment]
@ataylorme I have tested the PR and it worked perfectly! Thank you for adding this feature.

**Comment by mor10** [comment]
Merged. Closing.
