### ISSUE TITLE
Expected CSS Grid to work in IE 11

### ISSUE THREAD

**Issue by drivenfaroff** [wprig/wprig#279]
## Issue Overview

Expected CSS Grid to work in IE 11 as 'last 2 versions' was set in themeConfig.js for browserslist.

## Describe your environment

VS Code 
IE 11

## Steps to Reproduce

Used some standard CSS Grid and noticed layout issues in IE 11.

## Possible Solution

Added this to gulpfile.babel.js to enable correct grid output through autoprefixer.

`autoprefixer: {
grid: true
},`

**Comment by mor10** [comment]
Note to self: Look at new CSS grid tooling from PostCSS.

**Comment by ataylorme** [comment]
@drivenfaroff `last 2 versions` [does not cover IE11 in Brower List](https://browserl.ist/?q=last+2+versions). 

I added `IE 11` to `.browserslistrc` and see MS prefixes for  flexbox, not grid. [According to caniuse.com IE11 has partial support for CSS grid](https://caniuse.com/#search=grid).

I am not convinced this isn't working as exprected.

**Comment by ataylorme** [comment]
@drivenfaroff I am not trying to sound standoffish. Please play with `.browserlistrc` and see if you can get the desired result. I don't have IE 11 to test but Brower List and Post CSS are both very popular/standard packages and we are using them with their default, which should cover most use cases

**Comment by drivenfaroff** [comment]
This is more of a autoprefixer issue then a wprig issue. `last 2 versions` [does cover IE11](https://browserl.ist/?q=last+2+versions), it's in the list under "Desktop Browsers", however it's looking like even though it covers IE11 they have grid layout [disabled by default for IE](https://github.com/postcss/autoprefixer#does-autoprefixer-polyfill-grid-layout-for-ie).

Feel free to close this issue. If anything should be done maybe just an acknowledgement to look at autoprefixer docs for more information on CSS Grid support.

Thanks.

**Comment by ataylorme** [comment]
@drivenfaroff as a WP Rig user would it be helpful to you if a way to pass options to `postcss` was exposed in the WP Rig configuration, rather than having to edit the gulp files directly?

**Comment by mor10** [comment]
https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

**Comment by mor10** [comment]
Bumping `autoprefixer` to the latest version should make a difference here: https://github.com/postcss/autoprefixer

**Comment by mor10** [comment]
@drivenfaroff We are updating Autoprefixer in #337. With this update, you'll be able to use the new CSS grid fallbacks without any configuration. A full writeup of how to make  your grid markup backwards compatible is available here: https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

**Comment by benoitchantre** [comment]
> CSS grid fallbacks without any configuration

I just tested the `v2.0` now with IE11 on BrowserStack. Apparently this doesn't work: the sidebar is displayed below the content instead being next to the content.

**Comment by ataylorme** [comment]
@benoitchantre did you update `.browserlistrc` to have `IE 11`?

Reading [Does Autoprefixer polyfill Grid Layout for IE?](https://github.com/postcss/autoprefixer#does-autoprefixer-polyfill-grid-layout-for-ie) I'm wondering if adding `/* autoprefixer grid: autoplace */` to the CSS files would have an effect.

**Comment by benoitchantre** [comment]
@ataylorme In `.browserslistrc`, we have `> 1%` and `last 2 versions`. [That includes IE11](https://browserl.ist/?q=%3E+1%25%2C+last+2+versions).

I haven't found know how to configure autoprefixer with the build script.

**Comment by ataylorme** [comment]
From the linked doc in my last comment:

> Autoprefixer can be used to translate modern CSS Grid syntax into IE 10 and IE 11 syntax, but this polyfill will not work in 100% of cases. This is why it is disabled by default.

Looking at the [autoprefixer section of the `postcss-preset-env` README](https://github.com/csstools/postcss-preset-env#autoprefixer) it seems we may need `autoprefixer: { grid: true }`.

In #429 I am working on adding tests for the gulp tasks. @benoitchantre an expected input and output for IE grid CSS would be helpful. It might be as simple as:

```css
.a {
  display: grid;
}
```

```css
.a {
  display: -ms-grid;
  display: grid;
}
```

**Comment by benoitchantre** [comment]
@atalyorme Going back home now. I’ll try to look at that later based on https://autoprefixer.github.io/ which has the polyfill enabled.

Your example looks good. Do you want more (all?) properties for the tests?

**Comment by ataylorme** [comment]
> Do you want more (all?) properties for the tests?

No, I think if prefixing is present for one it will be there for all.

@benoitchantre can you test #429? I used this case to add a new feature of allowing `autoprefixer` to be configured. By default `grid` is set to `false` but changing it to `true` in `config/config.json` should add the prefixes needed by IE.

First, I wrote the test then I worked on the styles task until the test passed. My goal with #429 is to make testing as easy as `npm run test-gulp` instead of checking things manually whenever the gulp process is tweaked.

**Comment by benoitchantre** [comment]
@ataylorme Yes, but in 2-3 hours.

**Comment by benoitchantre** [comment]
Thank you @ataylorme, it works (autoprefixer adds support for IE).

Here's a screenshot of the result. The sidebar is now displayed next to the content as expected, but we have other issues because not all grid properties are supported by IE.

![bs_win8 1_IE_11 0](https://user-images.githubusercontent.com/1521015/56384874-dc3bf000-621d-11e9-9881-b8f0f9173758.jpg)

Here are some warnings reported by the build script when we turn on `grid` in `config.json`.

```
assets/css/src/content.css
174:32  ⚠  auto-fill value is not supported by IE [postcss-preset-env]
175:2   ⚠  grid-gap only works if grid-template(-areas) is being used [postcss-preset-env]
322:32  ⚠  auto-fill value is not supported by IE [postcss-preset-env]
323:2   ⚠  grid-gap only works if grid-template(-areas) is being used [postcss-preset-env]

assets/css/src/front-page.css
16:33   ⚠  auto-fit value is not supported by IE [postcss-preset-env]
17:3    ⚠  grid-auto-flow: dense is not supported by IE [postcss-preset-env]
18:3    ⚠  grid-gap only works if grid-template(-areas) is being used [postcss-preset-env]

assets/css/src/global.css
738:3   ⚠  grid-gap only works if grid-template(-areas) is being used [postcss-preset-env]
739:3   ⚠  IE does not support justify-content on grid containers [postcss-preset-env]
```

**Comment by ataylorme** [comment]
> we have other issues because not all grid properties are supported by IE.

@benoitchantre I think that is okay. My expectation is that WP Rig will not have IE support out of the box. Rather, a user must make adjustments if their project requires IE support.

That means opting into `autoprefix: { grid: true}` in the configuration as well as editing the CSS files to have IE compatible syntax.

**Comment by benoitchantre** [comment]
I made a test in a separate PR. The layout uses flexbox if grid is not supported.

**Comment by felixarntz** [comment]
Appears to not be completed as of 2.0, so moving to Future Release.

**Comment by mor10** [comment]
I've done some thinking and had some conversations about the issue of Grid backwards compat via autoprefixer. My conclusions are as follows:

1. We should ship grid, and _only_ grid, where grid is appropriate (no fallbacks)
2. The autoprefixer fallbacks work, but are an anti-pattern and should be avoided.
3. Possibly provide links to authoritative articles on how to mimic grid layouts using for example flex. This could be a dedicated docs article.

**Comment by mor10** [comment]
Added to documentation https://github.com/wprig/docs/blob/master/documentation/troubleshooting/css-grid.md

closing
