### ISSUE TITLE
No Vendor directory created during npm install

### ISSUE THREAD

**Issue by maltesesolutions** [wprig/wprig#283]
## Issue Overview

npm install error
No vendor directory created.

## Describe your environment

I am running Mac OS, and have been following along with your video course: "WordPress: Building Progressive Themes with WP Rig"

I have all the dependencies described in the video.

## Steps to Reproduce

1. I have tried several times with clean installs and get the same results and errors

## Current Behavior

No vendor directory is created.

## Screenshots / Video

<img width="1216" alt="screen shot 2019-01-11 at 10 05 44 am" src="https://user-images.githubusercontent.com/20502938/51041721-8bff2300-1588-11e9-8456-76003f7d9ad1.png">

Thanks

**Comment by ataylorme** [comment]
@maltesesolutions are you working with the original version of WP Rig or the new (in-progress) `2.0` version?

**Comment by mor10** [comment]
1. What version of WP Rig are you using?
2. Is Composer installed?

**Comment by maltesesolutions** [comment]
I have:

npm 6.5.0
composer 1.8.0
gulp 2.0.1

wprig 1.0.4 (downloaded from github)

**Comment by ehowey** [comment]
What version of node.js do you have installed?  I was having a similar error and was able to fix it by reverting to v.10.x of node.js. Not sure if that helps or you figured it out. I don’t understand node well enough to know why this fixed it but I think it has something to do with script dependencies and a mismatch between the versions.

**Comment by mor10** [comment]
@maltesesolutions have you resolved the issue or are you still stuck?

**Comment by mor10** [comment]
Fixed in `v2.0`. Closing.
