### ISSUE TITLE
Question: should we add action hooks?

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#287]
What are your opinions about adding action hooks?

I think it might be usefull to have some action hooks: they would help adding some features offered by plugins, for example breadcrumb. In this situation, we could create a Breadcrumb component, which could be compatible with one or many plugins. It would be cleaner than to modify many template files.

**Comment by samikeijonen** [comment]
I'll vote no because:

- There will be no standard for hook names. And I hope Rig doesn't start one:)
- That's why we have small templates where we can modify stuff via child theme in public themes.
- For custom themes parent theme works also.

**Comment by benoitchantre** [comment]
Thank you for your feedback @samikeijonen.

**Comment by ataylorme** [comment]
I vote no because [`get_template_part` has an action hook for each template included](https://core.trac.wordpress.org/browser/tags/5.0/src/wp-includes/general-template.php#L134) in the form of `get_template_part_{$slug}`.

Since WP Rig makes liberal use of template parts this gives us many action hooks already.

**Comment by benoitchantre** [comment]
> Can you provide some use cases?

I was thinking of small components provided by plugins, for example a breadcrumb. Instead of adding the code to invoque the function in many templates, an action hook could be used. As mentioned by Adrew, we have already many hooks provided by `get_template_part_{$slug}`.

**Comment by ataylorme** [comment]
@benoitchantre do the existing `get_template_part_{$slug}` action hooks suite your use case? If so, we can probably close this issue.

**Comment by ataylorme** [comment]
Going to close this out. If the existing `get_template_part_{$slug}` hooks aren't sufficient please re-open
