### ISSUE TITLE
 Menu Toggle and Menu Dropdown not Working on iPad

### ISSUE THREAD

**Issue by kokimu** [wprig/wprig#289]
## Issue Overview

I found menu toggle for the narrow menu and menu dropdown for the regular menu are not working on iPad. It works fine on iPhone though.  I'm using BrowserSync.
When I try responsive design mode on the web browser on a laptop, it works fine on any viewport sizes.
Not sure if this is because the version of my iPad and its iOS are old...

## Describe your environment

Editor: VS Code
Devices: MacBook Pro with OS 10.14.2, iPad v9.3.5 with iOS 9.3.5, iPhone 6s with iOS 12.1.2 
Browser: Firefox (Tried with Chrome and Safari on all above devises, and got the same result.)
Other: MAMP, BrowserSync

## Steps to Reproduce

I set up WP Rig locally and just got started working on.  So far, just a few changes were made on the following files within the "dev" folder.  All changed files are attached.
[menu_issue_on_ipad.zip](https://github.com/wprig/wprig/files/2766594/menu_issue_on_ipad.zip)

- functions.php
- navigation.js  (in "js" folder)
- header.php
- style.css

## Expected Behavior

The Menu Toggle and Menu Dropdown work on iPad.

## Current Behavior

Nothing happens when tapping on the Menu Toggle button.
For the regular menu, I can only access the top menus because the dropdown menu is not working.

**Comment by ataylorme** [comment]
@tessak22 have you been having menu issues? If so, can you describe them here.

**Comment by mor10** [comment]
Where are we on this @bamadesigner?

**Comment by ehowey** [comment]
I am still seeing some odd behaviour with this.  I am working on a client site using the latest commits to v2.0.  I just pushed a very early beta version of the site out for the client to look at, the css is a bit messy (all at the end of the file) still since I am waiting until a stable release to integrate it properly into the wprig CSS.  The pictures are also temporary placeholders so excuse the skewed size and perspective on the front page images.

I was getting this error on an iPhone 6.  The host is siteground if that makes any difference.  This is using a bundled version of the theme, so not the development rig.

You can see the site here:
https://lwb-beta.erichowey.design/

**Comment by briainod** [comment]
I'm experiencing exactly the same problem - the navigation works sporadically.

I thought the 'click' Event Listener might not be getting picked up so I've replaced it with 'touchstart' depending on the User Agent (dev/js/navigation.js:128) but it doesn't seem to make a difference.

I've added a console.log to the Event, it fires/doesn't fire when the menu does/does't work.

Have also tried switching the HTML element from <button> to <a>

http://avonmorepro.staging.wpengine.com/

**Comment by ehowey** [comment]
When I was digging through trying to problem solve I noticed that navigation.js is loaded "async" while lazyload.js is loaded "defer" - would switching navigation.js to "defer" solve this at all?  This is a bit beyond my knowledge but from the reading I did about DOMcontentloaded it seemed like the script must be firing at the wrong time sometimes...the only reason I can surmise for this is some kind of variability in the page load speed...I am sure someone who understands this more than me will come up with the right solution.

**Comment by dolcizia22** [comment]
Having the same issue with two sites I'm working on. Occasionally the mobile menu button will work but more often I get this "Uncaught TypeError: Cannot read property 'querySelector' of null
    at initMenuToggle"

I'm not very experienced at all with js so I'm looking forward to someone wiser than I am saving the day .

**Comment by benoitchantre** [comment]
#428 fixes this issue.

**Comment by ataylorme** [comment]
Closed by #428
