### ISSUE TITLE
Fatal Error when activating wprig theme

### ISSUE THREAD

**Issue by ygagnon** [wprig/wprig#29]
## Issue Overview

I've got a local development environment set up on a Windows 10 PC using WampServer and VSCode, and when I log in to my WordPress admin and attempt to activate the wprig theme (which I've named "wp") .. I'm getting the following fatal error:

**Fatal error: Cannot redeclare wp_scripts() (previously declared in C:\wamp64\www\wp\wp-includes\functions.wp-scripts.php:21) in C:\wamp64\www\wp\wp-content\themes\wp\functions.php on line 292**

I've tried downgrading the PHP versions from 7.x down to 5.x, .. but I still get the same error. 

I've followed all of the instructions, have all of the necessary settings properly configured in VSCode, was able to run "npm run build" without any issues and have BrowserSync up and running.  But the fatal error I'm getting is preventing me from going any further.  Any ideas as to what might be happening?

- Yvan

**Comment by carolinan** [comment]
Try using a different theme name, since wp_ is already used as a prefix.

**Comment by hellofromtonya** [comment]
>Fatal error: Cannot redeclare wp_scripts() (previously declared in C:\wamp64\www\wp\wp-includes\functions.wp-scripts.php:21) in C:\wamp64\www\wp\wp-content\themes\wp\functions.php on line 292

That error is telling you that you are attempting to redeclare the function `wp_scripts`.  That function exists in WordPress Core.

You have your theme named as `wp` in the themes folder. I'm guessing that you are also using the prefix of `wp_`.  As @carolinan pointed out, you need to change your prefix to be something other than `wp_`.  

Notice that with WP Rig theme, it's prefixed as `wprig_`.   For you, give it a name that you want, some unique name for your theme.

**Comment by ygagnon** [comment]
I tried changing my theme folder name from "wp" to "yvan" .. then updated the theme name in my "themeConfig.js" file .. and then re-ran "npm install" and "npm run build" .. but I still get the same fatal error when I attempt to activate the theme:


Fatal error: Cannot redeclare wp_scripts() (previously declared in C:\wamp64\www\wp\wp-includes\functions.wp-scripts.php:21) in C:\wamp64\www\wp\wp-content\themes\yvan\functions.php on line 292

Is it really necessary that I re-install WordPress using a different table prefix?  

- Yvan

**Comment by hellofromtonya** [comment]
## A Little Background on the Error:

Look at the error.  It's telling you that you have a function called `wp_scripts()` on line 292 in your functions.php file.  That function exists in WordPress Core.  You need to rename the function to something else.  

**Best practice is not to prefix using `wp_`. **

## How to fix?

You've already run `npm run build` previously when your theme slug was `wp`.  During that build process, it renamed everything to start with that prefix.  

How do you fix that?  Well, after changing the `themeConfig.js` file, you'll need to re-run `npm run build`.  But hold on.  By doing so, it does not rename all of the functions in the PHP files.  Hmm.

@ygagnon To get going, you'll need to delete the generated theme PHP files.  Then re-run `npm run build`.

**Comment by hellofromtonya** [comment]
I'll create a new issue to deal with re-running `npm run build` and rebuilding the PHP files.

**Comment by ygagnon** [comment]
Deleting all of the generated PHP files and re-running "spm run build" allowed me to activate the wprig theme without errors .. but now the front end of the site is throwing errors .. almost as though there are some other non-PHP files that I also need to delete:

**Fatal error: Uncaught Error: Call to undefined function yvan_is_amp() in C:\wamp64\www\wp\wp-content\themes\yvan\header.php:20 Stack trace: #0 C:\wamp64\www\wp\wp-includes\template.php(688): require_once() #1 C:\wamp64\www\wp\wp-includes\template.php(647): load_template('C:\\wamp64\\www\\w...', true) #2 C:\wamp64\www\wp\wp-includes\general-template.php(41): locate_template(Array, true) #3 C:\wamp64\www\wp\wp-content\themes\yvan\index.php(15): get_header() #4 C:\wamp64\www\wp\wp-includes\template-loader.php(74): include('C:\\wamp64\\www\\w...') #5 C:\wamp64\www\wp\wp-blog-header.php(19): require_once('C:\\wamp64\\www\\w...') #6 C:\wamp64\www\wp\index.php(17): require('C:\\wamp64\\www\\w...') #7 {main} thrown in C:\wamp64\www\wp\wp-content\themes\yvan\header.php on line 20**

**Comment by ygagnon** [comment]
I'm going to try deleting all files and re-installing the github package.  I'll report back afterwards.

- Yvan

**Comment by hellofromtonya** [comment]
@ygagnon Good idea.  Delete the folder. Clone it again.  Start over.  Let's see if the problem goes away.

**Comment by ygagnon** [comment]
Re-installing worked. I'm now up and running without errors.  Thanks for your help!
-- Yvan

**Comment by hellofromtonya** [comment]
Yippee!!  Thanks for your patience, @ygagnon. You can go ahead and close this issue since it's resolved for you.

BTW I did open a new issue for discussing the ability to regenerate/rebuild PHP files after running the build.
