### ISSUE TITLE
front-page.php should not load a sidebar

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#290]
## Issue Overview

Introduced with #244.

I’ll work on it as soon as #291 is merged.

**Comment by mor10** [comment]
For reference, `front-page.php` loads a sidebar to provide an example of how to load a sidebar in a non-standard way.

**Comment by benoitchantre** [comment]
I just checked again `master` and see no sidebar. Comments are displayed as a second column when they are enabled.

In `v2.0`, I see the same as `master` plus a sidebar as a third column.
Is it how it should be or a small mistake introduced when refactoring all template parts?

**Comment by mor10** [comment]
Sorry @benoitchantre. My bad. I was testing for the wrong scenario. You are absolutely right, there should not be a sidebar in the `front-page.php` template. 

The template was mainly designed to handle the blog index, not a static page, and I see in testing I didn't account for the static page as front page scenario. I'm going to create a PR to fix these issues and update the overall styling (which is hideous now that I look at it).
