### ISSUE TITLE
Inconsistent title sizes for the main title

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#293]
## Issue Overview

The main title has different sizes depending on the template that is used.

- When `h1` has the `.entry-title` class, the font-size value is `2rem`
- When `h1` has the `.page-title` class (blog, category, search, archive, ...), the font-size value is inherited from `h1` and has a value of `2em`

I'll work on it as soon as #86 is merged.

**Comment by mor10** [comment]
Merged, so closing.
