### ISSUE TITLE
Is this method for testing AMP plugin activation still accurate

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#3]
https://github.com/wprig/wprig/blob/a2374230c592c265451810e5ca16526ab70d40a9/dev/inc/template-tags.php#L10-L20

I have a feeling the answer is 'no'. Can someone verify / change?

@westonruter
@amedina

**Comment by westonruter** [comment]
The answer is yes! That is still the correct way. The plugin is being updated in 1.0 to make this more reliable in fact.
