### ISSUE TITLE
Require name and slug in config.json

### ISSUE THREAD

**Issue by ataylorme** [wprig/wprig#301]
## Issue Overview
gulp performs string replacement when building for production in `2.0`. The `README.md` in `2.0` *suggests* the following:

> Configure theme settings, including the theme slug and name.
> View ./config/config.default.json for the default settings.
> Place custom theme settings in ./config/config.json to override default settings.

I think we should fail gulp development, watch and production if name and slug have not changed from the defaults.

This will help guide users to creating a proper configuration as the current suggestion is not easily discoverable.

**Comment by mor10** [comment]
Good idea. I vote yes. Anyone else have a strong opinion on the matter? @bamadesigner perhaps?

**Comment by felixarntz** [comment]
Maybe only fail for the production stuff? As in `npm run bundle` from https://github.com/wprig/wprig/blob/v2.0/package.json#L87

I think you should be able to run everything development-related without changing these.

**Comment by ataylorme** [comment]
> Maybe only fail for the production stuff?

That makes sense to me
