### ISSUE TITLE
"npm run bundle" does not work by default on Windows

### ISSUE THREAD

**Issue by andreibarbuta** [wprig/wprig#302]
The problem is caused by the format of this line which is Linux compatible but not windows.
"bundle": "NODE_ENV=production gulp bundleTheme",

I managed to solve the issue by installing this:
npm install -g win-node-env

...after that I ran "npm run bundle" and worked without any problems

Hope it helps as a temporary solution, I'll let smarter people than me suggest a permanent solution

Link to a discussion of the problem:
https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman

**Comment by mor10** [comment]
@ataylorme Do you have any experience with this?

**Comment by ataylorme** [comment]
I do not as I don't have a Windows machine to test on. I think we can add the workaround to documentation though.

Testing version 2 beta on Windows, when we release a beta, would be really helpful. @andreibarbuta would you be interested in doing that?

**Comment by andreibarbuta** [comment]
Yes, gladly!

**Comment by kauaicreative** [comment]
I believe this is what we are looking for, https://www.npmjs.com/package/cross-env

@andreibarbuta thanks for the workaround for now

**Comment by ataylorme** [comment]
#494 has a potential solution but needs a pull request. I don't want to make a PR without testing on Windows. Is someone here with Windows willing to create the PR/test?

**Comment by mor10** [comment]
Fixed in `v2.0`. Closing.
