### ISSUE TITLE
PHP end tag should be removed when it's placed at the end of a file

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#306]
## Issue Overview

Some files contain a PHP end tag at the end. It's optional and generally advised not to have a PHP end tag at the end of a file.

>  The closing tag of a PHP block at the end of a file is optional, and in some cases omitting it is helpful when using include or require, so unwanted whitespace will not occur at the end of files, and you will still be able to add headers to the response later. It is also handy if you use output buffering, and would not like to see added unwanted whitespace at the end of the parts generated by the included files.

Source: [PHP manual](http://php.net/manual/en/language.basic-syntax.instruction-separation.php)

**Comment by mor10** [comment]
Merged. Closing.
