### ISSUE TITLE
Add an Excerpt component

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#313]
## Issue Overview

Its very common a theme need to change the default excerpt lenght. If I understand correctly the component approach from @felixarntz, the function and its filter should be contained in an _Excerpt_ component.

If you think it should be part of `2.0`, let me know. I can quickly work on that and submit a PR.
A sample use case to be to reduce the excerpt length in the search results.

Cc @mor10.

**Comment by felixarntz** [comment]
We can certainly review this and see whether it would make sense to include it. My initial thoughts are that this would be too specific, even if many themes use it.

I think for these kinds of (more opinionated) things it would be great to have a pool of pre-implemented components outside of WP Rig that a developer could easily pull in. That would be an amazing project for the future.

IMO, even if we decide this can be built-in, it can be added after 2.0.

**Comment by benoitchantre** [comment]
Closing in favor of #491.
