### ISSUE TITLE
Allow skipping translation file generation

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#314]
Currently, every build will generate a new `.pot` file to use for writing translations. However, that might not always be desired. Particularly as themes in the wordpress.org repository don't require or use these, as wordpress.org has its own translation system that themes automatically integrate with.

I think it would be great to have a setting in our `config.json`, called `useLanguagesDir`, that defaults to true (as it is now), but can be set to false. In that case, the `translate` tasks in Gulp should not run.

The other, a bit more challenging thing this would involve is to dynamically change https://github.com/wprig/wprig/blob/v2.0/inc/Localization/Component.php#L47 to only `load_theme_textdomain( 'wp-rig' )`. A potential solution would be to simply keep the code in the PHP file as is, and add that part as another PHP replacement item when building the theme.

@ataylorme Pinging you to get your feedback.

**Comment by ataylorme** [comment]
@felixarntz for the gulp side I propose we remove the translation process from the default tasks. We can expose it as a stand-alone task through npm script (`npm run pot` or similar).

The reason for this is that, as you say, people may wish to create translation files in different ways (or not at all). I don't think we should lock people into a default.

Personally, I would want to [make them with wp-cli](https://github.com/wp-cli/i18n-command) so that PHP and JavaScript files are processed and will do this in a build step on a CI server.

**Comment by felixarntz** [comment]
I like the idea of excluding the task from the default ones.

**Comment by mor10** [comment]
Can you two sort this out and make an executive decision. I don't have an opinion on the matter either way as long as translation files _can_ be made.

**Comment by ataylorme** [comment]
> I don't have an opinion on the matter either way as long as translation files can be made.

Currently, the translation process is run on *source* files, not *production* files. @mor10 and @felixarntz what do you think of having the current translation task (`npm run translate`) run `gulp-pot` on the production directory?

If we are no longer creating the `.pot` files on each dev run I can't think of a reason to keep basing them off of the source files and not the production ones.

**Comment by mor10** [comment]
that makes sense, especially considering production files may look different from development files at some point in the future.

**Comment by ataylorme** [comment]
Cool. I'll add a configuration option, as @felixarntz suggested in order to disable the `.pot` file generation on production builds.

**Comment by ataylorme** [comment]
Closed by #358
