### ISSUE TITLE
Check for file existence before copying specific files when bundling theme

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#315]
When bundling the theme and building into the production directory, a few files are directly copied (those files are in the `export.src` property in `gulp/constants.js`). Right now, when one of these files doesn't exist, the process fails.

This should not be the case, as many people might want to delete some of these files, for example you might not want to have `readme.txt` when you're not building a theme for wordpress.org.

Is that something that would be rather easy to fix @ataylorme? If so, it would be great to get it into 2.0.

**Comment by ataylorme** [comment]
#297 is rethinking how this works a bit but I think the source of the bug, the files not existing, will remain. [`gulp.src` will error when the pattern matches one file and that file is not found](https://gulpjs.com/docs/en/api/src#errors).

I will need to test and see if `allowEmpty` will resolve this or if it will have an adverse effect (e.g. writing an empty file). Reading [the `glob-stream` source code](https://github.com/gulpjs/glob-stream/blob/897b0fbacaa9a59b2126691217179998e2470e81/readable.js#L89) makes me think `allowEmpty` will work.

**Comment by mor10** [comment]
Was this resolved in #297? Can we close this issue?

**Comment by ataylorme** [comment]
Yes to both
