### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by paaljoachim** [wprig/wprig#317]
Is there a general documentation, api docs and other docs somewhere in addition to the video tutorials?

**Comment by seanrasmussen** [comment]
I was wondering the same thing. I haven't found much. There's the wiki tab in github but it doesn't have much there. I am actually just writing basic usage notes for myself. I'm thinking about adding it to the wiki, or suggesting that documentation gets added to the wprig website, too....

**Comment by mor10** [comment]
Look under the Projects tab: We have a whole Documentation project underway and we're looking for contributors. Just waiting for `v2.0` to get to beta so we don't have to redo a bunch of the documentation. Process and workspace TBD, but will likely be a Drive folder with a bunch of open documents. Once the documents are done, they will be placed either in the Wiki here, on wprig.io, or both.
