### ISSUE TITLE
Allow modification of the stylesheet loading mechanism

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#318]
WP Rig by default preloads stylesheets and injects their `<link>` tags directly within the HTML markup and page content. This helps performance, but may not be preferred under certain circumstances. There are already checks in place to disable preloading in an AMP context, however that doesn't cover all the cases. Other scenarios where someone might potentially want to skip this is accessing the theme via the Customizer. Also, when that mechanism is disabled, all stylesheets should be enqueued rather than only registered.

Let's introduce a simple layer in the `Styles` component that allows to disable the default way of preloading for more flexibility. As part of that, let's introduce a `wp_rig()->print_styles()` template tag, which must then be used instead of directly calling core's `wp_print_styles()`. Having the method allows us to make custom tweaks (like skipping the mechanism if it's disabled) without affecting templates in the future.

**Comment by mor10** [comment]
Merged. Closing.
