### ISSUE TITLE
Slick Slide Integration

### ISSUE THREAD

**Issue by solarianian** [wprig/wprig#32]
## Issue Overview

Slick Slide is one of the most used carousel/slideshow outhere.
Which is the the best way to integrate it in WP Rig? 

## Expected Behavior

Slick Slide should be loaded only where is used.

First, I tried to include slick.min.js, only for certain page template:
`if ( is_page_template( 'page-with-slick.php' ) ) {
	wp_enqueue_script( 'wprig-slick-slide-script-min', get_theme_file_uri( '/js/slick.min.js' ), array(), '20180626', true );
		}`

Unfortunately, the conditional  is_page_template is not working for me in wp rig. 
However, ( is_page(ID) ) is working (slick.min.js is loaded only on page with ID 41). A more general solution is ideal (like is_page_template).

the same in css case:
`// Preload css for slick slide
		if ( is_page_template('page-with-slick')) {
			$preloads['wprig-slick'] = wprig_get_preload_stylesheet_uri( $wp_styles, 'wprig-slick' );
			$preloads['wprig-slick-theme'] = wprig_get_preload_stylesheet_uri( $wp_styles, 'wprig-slick-theme' );
		}`

**Comment by mor10** [comment]
`is_page_template()` should work fine. There's nothing in WP Rig blocking core functions. 

I'm working on a tutorial around adding a slideshow to WP Rig.

**Comment by solarianian** [comment]
Hello!
is_page_template is working only if I call the template file from /verbose folder, like: 
`if ( is_page_template('verbose/page-with-slick.php')) {
		//slick css
		wp_register_style( 'wprig-slick', get_theme_file_uri( '/css/slick.css' ), array(), '20180626' );
		wp_register_style( 'wprig-slick-theme', get_theme_file_uri( '/css/slick-theme.css' ), array(), '20180626' );
	}`

Should I reinstall or is normal? 

I tried get_page_template_slug(); to see the exact path of template. The result was verbose/page-with-sidebar.php

thank you

**Comment by bamadesigner** [comment]
Where are you calling `is_page_template()`? These core functions only work after the main WP Query has been loaded.

If you're calling inside the `wp_enqueue_scripts` action you should be fine. If you're calling, e.g., inside the `init` action, then its too early.

**Comment by bamadesigner** [comment]
Hi @solarianian! Since we haven't heard from you in a while, we're going to close the issue. Feel free to comment if you want to chat some more.

**Comment by malviyaritesh** [comment]
Should I create a new Component for Slick Slider integration? If yes, how? Please give me some direction to go to.
