### ISSUE TITLE
Change output type for CSS (Sass) debug mode to 'expanded'

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#323]
`nested` output is hard to read. `expanded` is better imo.

https://github.com/wprig/wprig/blob/2c335bd86f4c3d9fd4e1f3ce847202b3ba5cd07e/gulp/sassStyles.js#L24

**Comment by mor10** [comment]
Any Sass people have strong opinions here? @benoitchantre?

**Comment by benoitchantre** [comment]
I agree.

**Comment by ataylorme** [comment]
Closed by #393
