### ISSUE TITLE
Move reused styles in editor-styles.css in separate files

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#334]
## Issue Overview

`editor-styles.css` contains many duplicated definitions from `content.css`. Custom block colors and custom font-sizes are good candidates for separate files that should be imported into `editor-styles.css` and `content.css`.

**Comment by mor10** [comment]
Can you make a PR for this so I can test properly?

**Comment by benoitchantre** [comment]
@mor10 These styles are now inlined automatically in the editor from php (when we declare our color palette our font sizes in the Editor component). The last commit in #332 closes this issue.

**Comment by benoitchantre** [comment]
I'll submit a follow-up PR after the merge of #332 with the goal to have more styles in `editor-styles.css` without duplication. Some sections from `global.css` should be moved to separated files (Typography, Elements, Links, ...) and imported into `global.css` and `editor-styles.css`.

**Comment by benoitchantre** [comment]
> Is this completed?

- #410 moves gallery block styles to `_blocks.css` (ready to be merged)
- `button`, `input` and other selectors that are part of the block editor UI cannot be imported in `editor-styles.css`: they change the appearance of the editor controls
- there are maybe a few more selectors in `content.css` that could be moved to another separate file; not sure it's worth it, but I can do some tests to see what selectors could be concerned

**Comment by benoitchantre** [comment]
@felixarntz I have found that captions styles and galleries (legacy) could be reused in `editor-styles.css`. We could move them in a new `_media.css` file.

In `_typography.css`, we have a padding of `1.6em` for `<pre>`.
I suggest to use a value of `1.5em` instead of `1.6em` and to remove the lines 117-123 from `content.css`.

https://github.com/wprig/wprig/blob/fc187e710d44c0db7c06ab6e631f0ef9cab77dde/assets/css/src/content.css#L117-L123
