### ISSUE TITLE
Composer install run on npm install

### ISSUE THREAD

**Issue by ataylorme** [wprig/wprig#336]
As a WP Rig user with an automated build process on Continuous Integration
Who loves the separation of concerns
I want to be able to run `npm install` without having `composer install` run
In order to do these tasks separately
Using a NodeJS Docker image for `npm install`
And a PHP Docker image for `composer install`
So that I don't have to maintain my own Docker image with PHP and NodeJS

See [package.json#L89](https://github.com/wprig/wprig/blob/v2.0/package.json#L89)

**Comment by mor10** [comment]
Originally, Composer required it's own install command. We combined them to take out a setup step early on. Let's discuss.

**Comment by ataylorme** [comment]
I think the advantage of being able to run them separately, which is useful for isolated container-based build environments, outweighs saving some users the hassle of having to run an additional command.

Also, if a user changes anything in Composer or wants to run something in Composer script, such as unit testing, they must run Composer commands (e.g. `composer update` or `composer run-phpcs`).

**Comment by mor10** [comment]
I'm fine with splitting them up again. That's how it worked in v1 and nobody complained. Create a PR for it and see if anyone balks at the idea.

**Comment by Drivingralle** [comment]
Maybe haveing one command like `npm rig-init` to run both commands for les advanced users and easy learning for beginners. This command could be documented in the getting started guides. 

And the two commands `npm install` and `composer install` for users that know what they are doing.

**Comment by ataylorme** [comment]
@Drivingralle thanks for the suggestion - I really like it 😄.
