### ISSUE TITLE
Tables inserted manually have a different style than table block

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#343]
## Issue Overview

A table inserted manually in the Classic Editor looks like that (unstyled):

<img width="672" alt="table - html" src="https://user-images.githubusercontent.com/1521015/53677687-65ba5180-3cb4-11e9-96d6-f50ce1366257.png">

A _Table_ block looks like that:

<img width="753" alt="table block" src="https://user-images.githubusercontent.com/1521015/53677725-d06b8d00-3cb4-11e9-9c7c-3fe8b48f69fc.png">

_Note: the width of the table (not 100%) is an issue introduced by https://github.com/wprig/wprig/commit/15ef2f9e94823f708e27fd9a69d92455f16aecb0._

## Expected Behavior

A table inserted manually should have the same styles than the _Table_ block. We may have them in posts/pages that are not yet converted to blocks.

**Comment by mor10** [comment]
stupid gutenberg issue. this is outside of scope
