### ISSUE TITLE
Potential gulp improvements

### ISSUE THREAD

**Issue by ataylorme** [wprig/wprig#35]
## Issue Overview

I have some personal gulp preferences from things I learned implementing gulp 4 in other projects. I am not sure if these are welcome improvements to WP Rig or not. 

Please let me know if you would consider some, or all, of these changes. If so I am happy to submit a pull request but don't want to spent time doing without validation of the improvement ideas.

### Monolithic gulp file

[`gulpfile.babel.js`](https://github.com/wprig/wprig/blob/master/gulpfile.babel.js) is a monolithic file that can be modularized

#### Suggested Solution

`gulpfile.babel.js` is written in ES6+ and can make use of imports. Here is [an example](https://github.com/ataylorme/Advanced-WordPress-on-Pantheon/blob/master/web/wp-content/themes/twentyseventeen-child/gulpfile.babel.js)

### Manually loading gulp plugins

[`gulpfile.babel.js`](https://github.com/wprig/wprig/blob/master/gulpfile.babel.js) manually loads gulp plugins. This currently adds 23 lines to the file.

#### Suggested Solution

Use [`gulp-load-plugins`](https://www.npmjs.com/package/gulp-load-plugins) to store gulp plugins in a single variable.

### Misc ES6+ Syntax updates

The `gulpfile.babel.js` uses some older conventions, such as [concatenating strings with `+`](https://github.com/wprig/wprig/blob/master/gulpfile.babel.js#L69).

#### Suggested Solution

Update `gulpfile.babel.js` to consistently use modern conventions. In this specific example using [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

### Use [`pump`](https://www.npmjs.com/package/pump) instead of `pipe`

gulp 4 suggests the use of `pump` instead of `pipe`. See [why use pump](https://github.com/gulpjs/gulp/tree/master/docs/why-use-pump).

#### Suggested Solution

Update `gulpfile.babel.js` to use `pump` instead of `pipe`. Here is [an example](https://github.com/ataylorme/Advanced-WordPress-on-Pantheon/blob/master/web/wp-content/themes/twentyseventeen-child/gulp/buildScript.js).

## Related Issues and/or PRs

Unsure if I should wait for the work in #30 to be merged before starting more gulp work.

**Comment by hellofromtonya** [comment]
Excellent points, @ataylorme.  +1 from me to move forward.

Note:  We are working on resolve #30 in PR #31.  Once merged, it'll need to be included in the new approach.

**Comment by ataylorme** [comment]
Thanks for the +1 @hellofromtonya. I'll wait for #31 rather than start work and have to refactor it in.

**Comment by mor10** [comment]
#31 has been merged. I've added this to the v1.1 milestone as I have a feeling it'll introduce a bunch of new thinking which may result in breaking changes. v1.1 branch (off Development) is now active and ready for contributions. Please create a PR and let's get this going!

**Comment by ataylorme** [comment]
@mor10 great! I've been out for some vacation around Independence Day but will work on a PR today/tomorrow.

**Comment by ataylorme** [comment]
I've started work in the [`issue-35-gulp-improvements` branch of my fork](https://github.com/ataylorme/wprig/tree/issue-35-gulp-improvements) but ran out of time today to finish up. It is pretty close with about half of the function moved into their own files.

Here is a todo list of what I did today and I plan to finish in my next session, which is most likely tomorrow.

- [x] Use gulp-load-plugins to store gulp plugins in a single variable.
- [x] Use pump instead of pipe
- [ ] split remaining functions in `gulpfile.babel.js` into separate files
- [ ] check for unused imports and remove them
- [ ] ES6+ Syntax updates final check
	- I did a lot of conversions as I have worked so far
- [ ] Use gulp 4 builtin sourcemaps rather than `gulp-sourcemaps`

**Comment by ataylorme** [comment]
@hellofromtonya and @mor10 the PR is up. Please comment on #47 with any questions, additional things I can do, etc.

I would also be happy to be the maintainer of gulp items in WP Rig going forward. Let me know if you're interested in the help. I can give guidance, support, code reviews, etc. on items such as #36

**Comment by miklb** [comment]
any chance could take a look at #7 while re-configuring Gulp?

**Comment by mor10** [comment]
FYI I've been on a mini holiday this past week. I'll take a close look at all this when I get back and confer with @bamadesigner about next steps. My cursory overview tells me this is a huge step forward.

**Comment by mor10** [comment]
FYI, seal of approval: https://twitter.com/gulpjs/status/1016382871618113537?s=19

**Comment by hellofromtonya** [comment]
@miklb I agree with @ataylorme.  Let's focus on getting the gulp architecture in place first.  Then we can go back and address bugs like #46 and enhancements like #7 and #36.

**Comment by miklb** [comment]
OK, I just saw the issue title and figured I'd ask.

**Comment by mor10** [comment]
@ataylorme I would love for you to be the maintainer and overseer of the Gulp process moving forward. What you've done so far is excellent and far beyond what I imagined.

**Comment by mor10** [comment]
Closing this issue as #47 is merged. See 1.1 for new Gulp process with all improvements listed above and more!

**Comment by ataylorme** [comment]
> @ataylorme I would love for you to be the maintainer and overseer of the Gulp process moving forward. What you've done so far is excellent and far beyond what I imagined.

@mor10 thank you for the kind words. I'd be happy to help out with gulp related items. Perhaps we can make use of the [code owner's feature](https://blog.github.com/2017-07-06-introducing-code-owners/)? I have plans this weekend but will look at the open gulp issues next week.
