### ISSUE TITLE
v2.0 Bundle styles.css header wrong

### ISSUE THREAD

**Issue by Drivingralle** [wprig/wprig#350]
## Issue Overview
I tried to get started wit v2.0 in a new project. But the generated bundle doesn't contain my config.

## Describe your environment
MacOS 10.14.3, NPM 6.8.0

## Steps to Reproduce
Using this config in `config.json`:
`{
    "theme": {
        "slug": "test-rig",
        "name": "Test Rig",
        "author": "Rig Tester"
      }
}`

Computer:~ drivingralle$ cd Desktop/rig-playground/
Computer:rig-playground drivingralle$ ls
.		..		.DS_Store	.idea
Computer:rig-playground drivingralle$ git clone https://github.com/wprig/wprig.git
Cloning into 'wprig'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 1811 (delta 25), reused 40 (delta 12), pack-reused 1738
Receiving objects: 100% (1811/1811), 1.02 MiB | 649.00 KiB/s, done.
Resolving deltas: 100% (1105/1105), done.
Computer:rig-playground drivingralle$ ls
wprig
Computer:rig-playground drivingralle$ cd wprig/
Computer:wprig drivingralle$ ls
CHANGELOG.md		composer.json		languages		readme.txt
CONTRIBUTING.md		composer.lock		package-lock.json	screenshot.png
LICENSE			dev			package.json
README.md		gulpfile.babel.js	phpcs.xml.dist
Computer:wprig drivingralle$ git checkout v2.0
Branch 'v2.0' set up to track remote branch 'v2.0' from 'origin'.
Switched to a new branch 'v2.0'
Computer:wprig drivingralle$ ls -a
.				README.md			offline.php
..				assets				optional
.browserslistrc			comments.php			package-lock.json
.editorconfig			composer.json			package.json
.eslintignore			composer.lock			phpcs.xml.dist
.git				config				phpunit.integration.xml.dist
.github				footer.php			phpunit.xml.dist
.gitignore			functions.php			readme.txt
.travis.yml			gulp				screenshot.png
404.php				gulpfile.babel.js		sidebar.php
500.php				header.php			style.css
CHANGELOG.md			inc				template-parts
CONTRIBUTING.md			index.php			tests
LICENSE				languages
Computer:wprig drivingralle$ npm install

> fsevents@1.2.7 install /Users/drivingralle/Desktop/rig-playground/wprig/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/drivingralle/Desktop/rig-playground/wprig/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> node-sass@4.11.0 install /Users/drivingralle/Desktop/rig-playground/wprig/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/drivingralle/.npm/node-sass/4.11.0/darwin-x64-64_binding.node

> node-sass@4.11.0 postinstall /Users/drivingralle/Desktop/rig-playground/wprig/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/drivingralle/Desktop/rig-playground/wprig/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine

> gifsicle@4.0.1 postinstall /Users/drivingralle/Desktop/rig-playground/wprig/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@4.0.0 postinstall /Users/drivingralle/Desktop/rig-playground/wprig/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@5.1.0 postinstall /Users/drivingralle/Desktop/rig-playground/wprig/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> wprig@2.0.0 install /Users/drivingralle/Desktop/rig-playground/wprig
> composer install

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 36 installs, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (3.3.2): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.4.4): Loading from cache
  - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
  - Installing mockery/mockery (1.2.0): Loading from cache
  - Installing antecedent/patchwork (2.1.8): Loading from cache
  - Installing brain/monkey (2.2.0): Loading from cache
  - Installing phpcompatibility/php-compatibility (9.1.0): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (6.5.13): Loading from cache
  - Installing wp-coding-standards/wpcs (2.0.0): Loading from cache
dealerdirect/phpcodesniffer-composer-installer suggests installing dealerdirect/qa-tools (All the PHP QA tools you'll need)
phpcompatibility/php-compatibility suggests installing roave/security-advisories (dev-master || Helps prevent installing dependencies with known security issues.)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility/,../../wp-coding-standards/wpcs/
added 1675 packages from 822 contributors and audited 19101 packages in 33.948s
found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Computer:wprig drivingralle$ npm run dev

> wprig@2.0.0 dev /Users/drivingralle/Desktop/rig-playground/wprig
> gulp

[18:38:59] Requiring external module @babel/register
[18:39:02] Using gulpfile ~/Desktop/rig-playground/wprig/gulpfile.babel.js
[18:39:02] Starting 'default'...
[18:39:02] Starting 'php'...
[18:39:02] Starting 'images'...
[18:39:02] Starting 'sassStyles'...
[18:39:02] Starting 'styles'...
[18:39:02] Starting 'scripts'...
[18:39:04] Finished 'sassStyles' after 2.59 s
[18:39:05] gulp-imagemin: Minified 1 image (saved 20 B - 22.7%)
[18:39:06] Finished 'images' after 4.48 s
[18:39:06] Finished 'scripts' after 4.7 s
[18:39:08] 

reset.css
 332    ✖  Expected selector "::-webkit-file-upload-button" to come before selector     no-descending-specificity
           ":root"

[18:39:08] Finished 'styles' after 6.14 s
[18:39:19] Finished 'php' after 18 s
[18:39:19] Starting 'serve'...
[18:39:19] Finished 'serve' after 12 ms
[18:39:19] Starting 'watch'...
[18:39:19] 'watch' errored after 17 ms
[18:39:19] TypeError: expected a string
    at module.exports (/Users/drivingralle/Desktop/rig-playground/wprig/node_modules/is-negated-glob/index.js:5:11)
    at sortGlobs (/Users/drivingralle/Desktop/rig-playground/wprig/node_modules/glob-watcher/index.js:66:18)
    at Array.forEach (<anonymous>)
    at watch (/Users/drivingralle/Desktop/rig-playground/wprig/node_modules/glob-watcher/index.js:63:18)
    at Gulp.watch (/Users/drivingralle/Desktop/rig-playground/wprig/node_modules/gulp/index.js:45:10)
    at watch (/Users/drivingralle/Desktop/rig-playground/wprig/gulp/watch.js:49:2)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/Users/drivingralle/Desktop/rig-playground/wprig/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[18:39:19] 'default' errored after 18 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wprig@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/drivingralle/.npm/_logs/2019-03-03T17_39_19_818Z-debug.log
Computer:wprig drivingralle$ npm run bundle

> wprig@2.0.0 bundle /Users/drivingralle/Desktop/rig-playground/wprig
> NODE_ENV=production gulp bundleTheme

[18:39:47] Requiring external module @babel/register
[18:39:50] Using gulpfile ~/Desktop/rig-playground/wprig/gulpfile.babel.js
[18:39:50] Starting 'bundleTheme'...
[18:39:50] Starting 'prodPrep'...
[18:39:50] Creating the production theme directory /Users/drivingralle/Desktop/rig-playground/test-rig
[18:39:50] Finished 'prodPrep' after 55 ms
[18:39:50] Starting 'php'...
[18:39:50] Starting 'scripts'...
[18:39:50] Starting 'styles'...
[18:39:50] Starting 'sassStyles'...
[18:39:50] Starting 'images'...
[18:39:53] Finished 'sassStyles' after 2.6 s
[18:39:53] gulp-imagemin: Minified 1 image (saved 20 B - 22.7%)
[18:39:55] Finished 'images' after 4.74 s
[18:39:55] Finished 'scripts' after 4.81 s
[18:39:56] 
assets/css/src/global.css
 323:1  ✖  Expected selector "::-webkit-file-upload-button" to come before selector     no-descending-specificity
           ":root"
[18:39:56] Finished 'styles' after 6.2 s
[18:40:08] Finished 'php' after 18 s
[18:40:08] Starting 'translate'...
[18:40:08] Finished 'translate' after 250 ms
[18:40:08] Starting 'prodFinish'...
[18:40:08] Finished 'prodFinish' after 79 ms
[18:40:08] Finished 'bundleTheme' after 18 s
Computer:wprig drivingralle$ cd ..
Computer:rig-playground drivingralle$ ls -a
.		..		.DS_Store	.idea		test-rig	test-rig.zip	wprig
Computer:rig-playground drivingralle$ cd test-rig
Computer:test-rig drivingralle$ ls -a
.		500.php		comments.php	header.php	languages	screenshot.png	template-parts
..		LICENSE		footer.php	inc		offline.php	sidebar.php
404.php		assets		functions.php	index.php	readme.txt	style.css

## Expected Behavior
Header in `style.css `file in `test-rig` folder to contain "Test Rig" as theme name and "Rig Tester as Author".

## Current Behavior
Default strings are used.

## Screenshots / Video
Compiled theme as ZIP: https://cloudup.com/cZwsnPWWkdK

**Comment by Drivingralle** [comment]
Also if I run `npm run bundle` directly after `npm install` the replacement fails.

**Comment by ataylorme** [comment]
@Drivingralle we are actively working on v2 but hope to have a beta soon. Once we do I will let you know so that you can test again.

**Comment by benoitchantre** [comment]
Same result with `v2.0-beta.1`.
`styles.css` in the bundle doesn't contains the values from `config.default.json`

**Comment by ataylorme** [comment]
Also, with `style.css`, the idea is that can be edited directly in the development theme. Though I see how leaving `Theme Name: WP Rig` would be desired so that you can easily tell which theme is which (dev vs production theme) in the WordPress dashboard.

@Drivingralle can you test #427? That PR runs string replacement on `style.css`.
