### ISSUE TITLE
Alignment of the Quote block

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#362]
## Issue Overview

Actually, the border of the _Quote_ block is not aligned with the content.

![capture d ecran 2019-03-05 a 11 52 29](https://user-images.githubusercontent.com/1521015/53800716-a082ea80-3f3d-11e9-9639-5207516243e9.png)

Is it something intentional @mor10?
To my eyes, it seems to be an issue caused by a padding added to all elements inside entry content.

In _Twenty Nineteen_, the border of the _Quote_ block is aligned with the content.

![capture d ecran 2019-03-05 a 11 52 10](https://user-images.githubusercontent.com/1521015/53800876-0b342600-3f3e-11e9-937b-03f3f0d91ab9.png)

**Comment by benoitchantre** [comment]
If it's not intentional and we want to fix it, I see three options:

1. Create a similar border for the _Quote_ block with a pseudo element, allowing us to use some padding on the element itself without having an influence on its border. Only fix this the alignment issue for this block.
1. Remove the extra padding on the elements inside `entry-content` (we already have a padding on the container), adjust content width to get the same width for the content. Global fix with small appearance change on bottom borders.
1. Option 2 + recreate bottom borders with a pseudo elements to have them a bit wider than the content width. Global fix with identical aspect.

I'm in favor of options 2 or 3.

**Comment by ataylorme** [comment]
I vote for option 2. It seems like a good way to solve this issue and prevent similar ones going forward

**Comment by benoitchantre** [comment]
I just tested that again on `v2.0`

**For large screens**, the border is aligned with the content (ok)
![Capture d’écran 2019-03-14 à 17 50 14](https://user-images.githubusercontent.com/1521015/54375689-d3398b00-4681-11e9-9b4c-ab65be449c05.png)

**For small screens**, the border is aligned with the viewport (should be aligned with the content)
![Capture d’écran 2019-03-14 à 17 58 26](https://user-images.githubusercontent.com/1521015/54376174-c9fcee00-4682-11e9-9b65-262cdfa91d7b.png)

Based on that, it seems the option 1 is the solution.

**Comment by benoitchantre** [comment]
It should be fixed by #362. I have found a simpler solution by using a left margin.

**Comment by benoitchantre** [comment]
Fixed by #353.
