### ISSUE TITLE
watch task fails

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#363]
## Issue Overview

When you run `npm run dev`, it stops at the watch task with the following error:

```
TypeError: expected a string
```

The error is located in line 49.

To fix this error, we can replace `[paths.styles.src, paths.styles.cssCustomProperties, paths.styles.cssCustomMedia]` by `paths.styles.src`, but doing that, a change in `custom-properties.css`, `custom-media.css` or `reset.css` will not trigger the style task because they are excluded.

Cc. @ataylorme

**Comment by ataylorme** [comment]
@benoitchantre can you test #364 and see if solves the issue for you?

**Comment by ehowey** [comment]
Is the same as what I had happen here: https://github.com/wprig/wprig/issues/340

**Comment by benoitchantre** [comment]
> Is the same as what I had happen here: #340

Yes

**Comment by ataylorme** [comment]
@benoitchantre can you verify this is fixed for you? If so, please close the issue.

**Comment by benoitchantre** [comment]
✔️ works
