### ISSUE TITLE
Build: setting preserve to false for custom properties and custom media doesn't work

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#365]
## Issue Overview

Changing the `preserve` value should work out of the box, whatever WP Rig uses as the default value.

Actually, the default value is set to `true`, but changing it to `false` doesn't work.

We the value is set to `false`, the custom properties or custom media definitions are removed, but the values are not computed. In the stylesheets, we have references to undefined values.

**Comment by ataylorme** [comment]
#369 should fix this when it is merged

**Comment by benoitchantre** [comment]
Closed by #369.
