### ISSUE TITLE
Store folder for plugin zip file

### ISSUE THREAD

**Issue by Lautobus** [wprig/wprig#377]
## Issue Overview

I've made a custom plugin to manage Custom Post Types and want to bundle it with the theme so it could be install and activated with TGM Plugin Activation.
I've try to store the plugin zip file in "inc" and "pluggable" folder but the bundle process seems to get rid of zip files.
I could manually add the zip files after the bundle process but would be more easy to store them somewhere in the folders structure and bundle them automatically with the rest of the theme files.

So, is there a way (specific store folder or specific bundle process) to bundle my plugin zip files?

Thanks for help.

**Comment by ataylorme** [comment]
Hi @Lautobus try adding it to the `export.filesToCopy` section of the config. This is where you can add extra files to be copied to the production build. Here is an example `config/config.json`

```json
{
    "export": {
        "filesToCopy": [
            "LICENSE",
            "readme.txt",
            "style.css",
            "screenshot.png",
            "my-cpt-plugin.zip"
        ]      
    }
}
```

We also released [`v2.0-beta1`](https://github.com/wprig/wprig/releases/tag/v2.0-beta.1) so please test that version as it is the most up to date.
