### ISSUE TITLE
Gutenberg Cover block not centering content

### ISSUE THREAD

**Issue by kauaicreative** [wprig/wprig#380]
## Issue Overview
wprig 2.0 - Gutenberg Cover block centers content on backend but not on frontend. 

## Steps to Reproduce

1. Add Cover block to page and view on frontend.

## Expected Behavior
See images with `display:block` turned on/off

## Screenshots / Video
![image](https://user-images.githubusercontent.com/127033/54448141-4eb33f00-474b-11e9-868d-f54c21ae1d98.png)
![image](https://user-images.githubusercontent.com/127033/54448148-54108980-474b-11e9-91cc-55fcf8225793.png)

## possibly relates to: 
issue #191

**Comment by benoitchantre** [comment]
Closed by #386.
