### ISSUE TITLE
assets directory structure could be improved. 

### ISSUE THREAD

**Issue by kauaicreative** [wprig/wprig#381]
## Issue Overview
When viewing the wprig src theme, relative src css references fail with current assets directory structure e.g. 
`background-image: url('../images/image.jpg');`

## Steps to Reproduce
1. Set theme to wprig source theme
2. Set a relative path in your css file. Something like this: 
`background-image: url('../images/image.jpg');` 
3. The image can not be found because the reference in the wprig src theme would need to be:
`background-image: url('../../images/src/image.jpg');` 
But in the dist theme it would need to be:
`background-image: url('../images/src/image.jpg');` 

## Possible Solution
The src css references will work perfectly if we move the src assets into their own src assets directory and change the assets tree to look something like this:
```
\assets\css
\assets\images
\assets\js
\assets-src\css
\assets-src\images
\assets-src\js
```
Another advantage is that it simplifies the .gitignore file a little :) 
```
!/assets/
```
vs
```
!/assets/
/assets/*
!/assets/css/
/assets/css/*
!/assets/css/src/
!/assets/js/
/assets/js/*
!/assets/js/src/
!/assets/images/
/assets/images/*
!/assets/images/src/
```

**Comment by mor10** [comment]
Question about file structure. cc @ataylorme @felixarntz

**Comment by mor10** [comment]
wontfix. closing.
