### ISSUE TITLE
Add wp_body_open hook

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#391]
## Issue Overview

> Starting from WordPress 5.2 a new function is added – `wp-body_open()` – that is used to trigger a `wp_body_open` action. The intention of this action is to allow people to add things – like a `<script>` tag – directly inside the body of a page.
> Themes should start adding this hook to their themes as soon as 5.2 releases.

Source : [make.wordpress.org](https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/)

**Comment by bamadesigner** [comment]
Addressed in #392.
