### ISSUE TITLE
Creation of new WP templates

### ISSUE THREAD

**Issue by mrky007** [wprig/wprig#40]
Hi, this rig is perfect for theme development. Also a BIG thanks for the tutorials on LinkedIn Learning. There is one thing I need to ask you though. Is there a plan for a tutorial on hoe to create new WP templates (like WooCommerce pages etc...)?

I know I can add these easily, but I don't want to loose all the WP Rig goodies in the process of creating these.

Thanks.

**Comment by mor10** [comment]
See my response to #37. tl;dr: We are open to including extensions like WooCommerce as long as they sit in the `./dev/pluggable/` folder so developers can choose to include them or not. That's one of the development principles for WP Rig: Modularity.
