### ISSUE TITLE
Remove @custom-media rules from setup (for now)

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#403]
See #400 and https://github.com/wprig/wprig/pull/369#issuecomment-472177337

`@custom-media` might be a bridge too far along the bleeding edge route for right now. I propose we remove the `@custom-media` rules from existing stylesheets, replacing them with standard Custom Properties for now, as we await better support. The custom media rules file can stay in the system with a comment at the top saying it is experimental and conflicts with AMP plugin etc. 

This resolves #400 without changing the Gulp + PostCSS configuration, leaves developers to play around with bleeding edge experimental features if they want to, and provides necessary context for people to make informed decisions.

CC @ataylorme @westonruter @benoitchantre

Tagging as `v2.0` bug because it is.

**Comment by ataylorme** [comment]
I am okay with removing custom media but leaving support for it (and documenting that support) if user's wish to implement it. We could warn about possible AMP incompatibilities.

To me, this is similar to WP Rig supporting Sass but not shipping with any Sass files.

**Comment by mor10** [comment]
Riiiiiiiiiight... There was a reason I used `@custom-media` to begin with: You can't use custom properties in media queries, which is why `@custom-media` exists in the first place. This requires some more thought.

From the [spec](https://www.w3.org/TR/css-variables-1/#using-variables):

> The var() function can not be used as property names, selectors, or anything else besides property values. (Doing so usually produces invalid syntax, or else a value whose meaning has no connection to the variable.)

Thoughts @bamadesigner and @benoitchantre?

**Comment by benoitchantre** [comment]
Ok with your proposal.

Would it be possible to check and merge #390 before?

**Comment by ataylorme** [comment]
> The use of @custom-media is not allowed with AMP.

Custom media just needs to be excluded from the built CSS, not the source. We could rethink the decision in #369 and use `importFrom` to inject/process custom-media/custom-properties and _not_ preserve them in the built CSS.

This would allow them to continue to be used in the source without having anything in the built CSS that conflicts with AMP.

**Comment by mor10** [comment]
Custom Properties must be preserved. They are not bleeding edge. Custom media can be imported and rewritten in the interim.

**Comment by ataylorme** [comment]
Closed by #405
