### ISSUE TITLE
Travis doesn't test PHP 7.3 stable

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#409]
## Issue Overview

Is there a reason not to include tests for PHP `7.3`?
Also, why failures are allowed with a stable branch of PHP (`7.2`)?
https://github.com/wprig/wprig/blob/b3edfa4c488ff03aeed4770ed5a75973db4e3227/.travis.yml#L22-L40

**Comment by benoitchantre** [comment]
I feel this is something that should be milestoned for `v2.0`.

Cc. @felixarntz,

**Comment by ataylorme** [comment]
I think @mor10 set up Travis initially. I added gulp tests but otherwise I haven't touched the Travis config. I don't see a reason for PHP `7.3` to not be included.

**Comment by mor10** [comment]
This is @felixarntz territory.

**Comment by ataylorme** [comment]
Closed by #527
