### ISSUE TITLE
PHP_CodeSniffer error with PHP 7.3.x

### ISSUE THREAD

**Issue by greatislander** [wprig/wprig#412]
## Issue Overview
I'm encountering an error with all build and watch processes related to PHP_CodeSniffer. It appears to be fixed in a forthcoming update to PHP_CodeSniffer, but I thought I should file a report here so that anyone else who encounters it can benefit.

## Describe your environment
macOS: 10.14.4
PHP: 7.3.4

## Steps to Reproduce
1. Clone this repo and checkout the v2.0 branch.
2. Change the theme name/slug/namespace in `./config/config.json`.
3. Run `npm run rig-init`.
4. Run `npm run dev` or `npm run build`.

## Expected Behavior
The theme builds and watches (in dev mode) or builds.

## Current Behavior
Build fails.

<details>

```
❯ npm run build

> wprig@2.0.0 build /Users/ned/Sites/platform/wp-content/themes/wprig
> gulp buildDev

[09:39:51] Requiring external module @babel/register
[09:39:54] Using gulpfile ~/Sites/platform/wp-content/themes/wprig/gulpfile.babel.js
[09:39:54] Starting 'buildDev'...
[09:39:54] Starting 'php'...
[09:39:54] Starting 'images'...
[09:39:54] Starting 'sassStyles'...
[09:39:54] Starting 'scripts'...
[09:39:54] Starting 'translate'...
[09:39:54] Starting 'styles'...
[09:39:55] Finished 'sassStyles' after 1.12 s
[09:39:56] gulp-imagemin: Minified 0 images
[09:39:56] Finished 'images' after 2.21 s
[09:39:57] 'php' errored after 3.36 s
[09:39:57] Error in plugin 'gulp-phpcs'
Message:
    Execution of Code Sniffer Failed
Details:
    stdout:
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined variable: childOutput in /Users/ned/Sites/platform/wp-content/themes/wprig/vendor/squizlabs/php_codesniffer/src/Runner.php on line 705 in /Users/ned/Sites/platform/wp-content/themes/wprig/vendor/squizlabs/php_codesniffer/src/Runner.php:562
Stack trace:
#0 /Users/ned/Sites/platform/wp-content/themes/wprig/vendor/squizlabs/php_codesniffer/src/Runner.php(705): PHP_CodeSniffer\Runner->handleErrors(8, 'Undefined varia...', '/Users/ned/Site...', 705, Array)
#1 /Users/ned/Sites/platform/wp-content/themes/wprig/vendor/squizlabs/php_codesniffer/src/Runner.php(502): PHP_CodeSniffer\Runner->processChildProcs(Array)
#2 /Users/ned/Sites/platform/wp-content/themes/wprig/vendor/squizlabs/php_codesniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#3 /Users/ned/Sites/platform/wp-content/themes/wprig/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#4 {main}
  thrown in /Users/ned/Sites/platform/wp-content/themes/wprig/vendor/squizlabs/php_codesniffer/src/Runner.php on line 562

[09:39:57] 'buildDev' errored after 3.37 s
[09:39:57] The following tasks did not complete: <series>, scripts, translate, styles
[09:39:57] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.0 build: `gulp buildDev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ned/.npm/_logs/2019-04-09T12_39_57_581Z-debug.log
```

</details>

## Possible Solution

Searching for `Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined variable: childOutput` turned up this issue in PHP_CodeSniffer, which appears to be affecting others working on WordPress: https://github.com/squizlabs/PHP_CodeSniffer/issues/2304

It's been fixed in https://github.com/squizlabs/PHP_CodeSniffer/commit/c09a4e1a2f3f6fe4a628e72b5e61ad35b309ed02 and the fix will be released in PHP_CodeSniffer 3.4.2 ([comment](https://github.com/squizlabs/PHP_CodeSniffer/issues/2304#issuecomment-481100231)).

## Screenshots / Video
N/A.

## Related Issues and/or PRs
N/A.

**Comment by simon-olsen** [comment]
I've been trying to fix this issue for some time now.

```
phpcs: Referenced sniff "PHPCompatibility" does not exist
```

WP Rig compiles fine, but as soon as I click into any PHP file, VS Code repeatedly shows this message.

I've tried `composer require "squizlabs/php_codesniffer"` (in the theme) and `composer global require "squizlabs/php_codesniffer"`.

```
squizlabs/php_codesniffer (3.4.2 => 3.5.2)
```

I'm running the latest WP Rig install as of now.

How do I get it working?

**Comment by Netyson** [comment]
> How do I get it working?

Hi Simon, maybe i have something to help you. I had this issue also in my VS Code environment.

I added some Documentation to the WP-Rig Google Drive. See: https://docs.google.com/document/d/1mWoEIHNhs77zEKv3L_-KNJnLxa_Fbzu2q1v6722zhzY/edit#heading=h.s3p0vddiqmvc

unfortunately i dont know how or when it will be included in the official documentation.

**Comment by simon-olsen** [comment]
Thanks for sending this through but I'm still not able to get rid of the warnings in VS Code.

I can see in my wprig-theme folder the _/vendor/phpcompatibility_ and _/vendor/wp-coding-standards_ folders. They're full of all the dependencies.

When I run `phpcs -i` in my WP Rig theme I get...

```
The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1, PSR12, WordPress, WordPress-Extra, WordPress-Docs and WordPress-Core
```
I then run the following from within my WP Rig theme...
```
username$ phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs/, vendor/phpcompatibility/php-compatibility/PHPCompatibility/

Using config file: /Users/username/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf

Config value "installed_paths" updated successfully; old value was "vendor/wp-coding-standards/"
```
Still no luck. Now I'm getting `phpcs: Referenced sniff "WordPress" does not exist`

**Comment by Netyson** [comment]
Are you on a Windows or Mac OS environment?

You should find a folder .vscode/settings.json
Can you check if there are following links included? change the paths with yours, if you environment is differed.

```
  "phpcs.executablePath": "vendor\\squizlabs\\php_codesniffer\\bin\\phpcs",
  "phpcs.standard": "vendor\\wp-coding-standards\\wpcs,vendor\\phpcompatibility\\php-compatibility\\PHPCompatibility",
  "phpcs.enable": true,
  "phpcs.composerJsonPath": "C:\\xampp\\7222\\htdocs\\wp-content\\themes\\wprig\\composer.json",
```

**Comment by simon-olsen** [comment]
I'm on a Mac. And I think it's fixed now!

I updated my `.vscode/settings.json` file at the root of my project with the paths to those folders in my project.

```
{
  "phpcs.enable": true,
  "phpcs.executablePath": "wp-content/themes/wprig-theme/vendor/squizlabs/php_codesniffer/bin/phpcs",
  "phpcs.composerJsonPath": "wp-content/themes/wprig-theme/composer.json",
  "phpcs.standard": "wp-content/themes/wprig-theme/vendor/phpcompatibility/php-compatibility/PHPCompatibility",
  "editor.renderWhitespace": "all"
}
```

For anyone else reading this, ensure you change `wprig-theme` to the name of your custom WP Rig theme folder.

Thanks very much for your help, @Netyson.

**Comment by simon-olsen** [comment]
Looks like I spoke too soon.

`phpcs: Referenced sniff "WordPress" does not exist`

I tried updating the `phpcs.standard` in VS Code workspace settings to the wpcs path :

```
"phpcs.standard": "wp-content/themes/wprig-emcee/vendor/wp-coding-standards/wpcs",
```

So my VS Code Workspace settings are now...

```
{
  "phpcs.enable": true,
  "phpcs.executablePath": "wp-content/themes/wprig-theme/vendor/squizlabs/php_codesniffer/bin/phpcs",
  "phpcs.composerJsonPath": "wp-content/themes/wprig-theme/composer.json",
  "phpcs.standard": "wp-content/themes/wprig-theme/vendor/wp-coding-standards/wpcs",
  "editor.renderWhitespace": "all"
}
```

I still get the warning every time I edit a PHP file.

Also tried the path to the WordPress folder `.../vendor/wp-coding-standards/wpcs/WordPress`

What am I doing wrong?

**Comment by simon-olsen** [comment]
Just a heads up. 3.5 months later and I never managed to fix this. Regardless of the settings.json in the _/vscode_ folder, nor the instructions from the Google Doc, I'd either get 
```
phpcs: Referenced sniff "PHPCompatibility" does not exist
```
or I'd update the `installed_paths` to point at my php-compatibility folder in _/vendor_ and then get
```
phpcs: Referenced sniff "WordPress" does not exist
```
I had the same issues on two different Macs and in both my WP Rig project and also in a fresh install.

Is it because the config during `npm run rig-init` and `composer update` is geared toward a Windows environment?

I'd really like to get this solved instead of having to ignore the above notifications appearing with every keystroke in a PHP doc in VS Code.

Or how do we just turn it off???

**Comment by sebemerson** [comment]
Bit of a long shot without all the context, but as you're using wp rig, try the following to remove the notification and potentially get it working. Remove everything and just leave this..
`{
 "phpcs.enable": true,
  "editor.renderWhitespace": "all",
  "phpcs.standard": "WordPress"
}`

If it has worked, try making a mistake in a php file and wait for a moment to see if the codesniffer kicks in
