### ISSUE TITLE
Update lazyload to meet current best-practice

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#414]
Lazy loading of images (and iframes) is coming to a browser near you very soon. The lazy loading feature in WP Rig should be updated to meet this new standard: https://addyosmani.com/blog/lazy-loading/

Todo:

- [ ] - Add `loading="lazy"` attribute/value pair to all images to be lazy loaded.
- [ ] - Add `loading="eager"` to the first featured image on single posts and pages.
- [ ] - Update classnames to conform with fallback suggestion in @addyosmani's blog post (https://addyosmani.com/blog/lazy-loading/).
- [ ] - Remove the Customizer on/off feature as this will become a browser default.
- [ ] - Keep conditional for Jetpack for now.
- [ ] - Monitor https://github.com/joemcgill/WP_Media_Experiments for WP core developments.

Cc: @joemcgill

**Comment by felixarntz** [comment]
I think this is better suited for post-2.0 because it's too early to implement this IMO. While we want to be on top of the time, implementing this now would be too much so. The feature is still in draft (see https://github.com/whatwg/html/pull/3752), Chrome is only including it experimentally.

In combination with this not being a breaking change, I suggest to punt to "Future Release".

**Comment by mor10** [comment]
sure.

**Comment by waviaei** [comment]
FYI. Lazy loading is now removed from Chrome in 76.

> The policy is removed in favor of a newer feature policy for loading, namely loading-frame-default-eager  which is more aligned with how the loading attribute will be used. The removal applies to both the Feature-Policy header and the <iframe> allow attribute.

https://developers.google.com/web/updates/2019/06/chrome-76-deps-rems

**Comment by addyosmani** [comment]
Lazy loading has not been removed from Chrome 76. That update refers to an outdated feature policy (for controlling the default values for the feature), but the feature itself is still there.

**Comment by waviaei** [comment]
@addyosmani Thank you for clarifying!

**Comment by mor10** [comment]
@addyosmani (repeat from Twitter) what in your opinion is a good baseline for image loading in a CMS like WordPress? Setting all images to "lazy" and allowing devs to switch individual images to "auto" or "eager"? Or set all images to "auto" and allow devs to switch to "lazy"? Assume devs rarely change the default setting, and users stuff their pages full of images, mostly below the fold.

**Comment by felixarntz** [comment]
Now that Chrome supports native lazy-loading, I created #577 to finally bring it to WP Rig (with graceful fallback to existing script).

**Comment by mor10** [comment]
We need to monitor the [core Trac ticket](https://core.trac.wordpress.org/ticket/44427) on this and see what happens. If/when core adopts the new `loading:"lazy"` spec, the modality of lazy-loading in WP changes significantly and we can probably offload the entire lazy solution in favor of the core feature. Hold until then.

**Comment by jacklowrie** [comment]
related to #669 , and closed by #657

**Comment by robruiz** [comment]
Lazy loading is handled by WordPress now. Closing this issue.
