### ISSUE TITLE
Undefined custom properties in editor-styles.css 🤔

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#417]
## Issue Overview

Custom properties are back in `editor-styles.css`. We should only have computed values, otherwise we have undefined values because of a bug in the block editor.

Cc. @ataylorme

**Comment by benoitchantre** [comment]
Introduced in 067c2b76ea0ffe341d9f9d5471f13db7a0bf228f

**Comment by ataylorme** [comment]
This is why I want to write tests for the gulp tasks themselves

**Comment by benoitchantre** [comment]
Sounds like a good idea.
