### ISSUE TITLE
Use a theme slug that is more than one word

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#43]
## Issue Overview

We need to consider whether the theme `slug` in `themeConfig.js` will always be the only parameter that needs to be covered when making initial naming replacements. The slug at the moment is only a single word, however what happens if the the slug would be something consisting of two words? If I want to have `my-theme`, this would only work as a textdomain replacement, but no longer as function name prefix replacement (we'd probably need to sanitize it to `my_theme` there. If the code at some point includes classes or namespaces, we would also need to account for `My_Theme`.

## Possible Solution

I think the starter theme would be better off using distinct `wp_rig` and `wp-rig` strings, possibly even `WP_Rig`. That would make replacements in such cases easily possible while at the moment it uses the simplest use-case.

## Related Issues and/or PRs

This came up during #31.

**Comment by mor10** [comment]
Flagging this as a bug to give it priority for 1.1

**Comment by mor10** [comment]
Pick a day you want to do this on and we'll do a PR freeze until the PR is submitted, tested, and merged.

**Comment by felixarntz** [comment]
I'll implement this next Tuesday.

**Comment by felixarntz** [comment]
Fixed via #93
