### ISSUE TITLE
Clearer documentation about naming of wprig folder in 2.0

### ISSUE THREAD

**Issue by ehowey** [wprig/wprig#430]
## Issue Overview
In the documentation installing wprig v2.0 it states as follows:

1. Clone or download this repository to the themes folder of a WordPress site on your development environment.
  -DO NOT change the name of the theme directory from the default wprig.

In discussion during office time today I asked a question about this.  It turns out that renaming the folder is not such a big deal, the problem occurs when you rename the wprig folder to your production theme name which causes confusion in the "npm run bundle" process.

## Possible Solution

1. Clone or download this repository to the themes folder of a WordPress site on your development environment.
  -DO NOT give the wprig development folder the same name as your production theme. This will cause issues when you bundle your theme for production.  For instance if your theme will eventually be named "Excalibur" you cannot use this as your folder name.  The "excalibur" folder gets created during the "npm run bundle" process when you are ready to deploy.  See more detail on [the production process farther on in the readme.](https://github.com/wprig/wprig/blob/v2.0/README.md#how-to-build-wp-rig-for-production)

**Comment by ataylorme** [comment]
@ehowey thank you for sharing that this wasn't clear for you. I think your suggested solution makes sense. Would you like to open a pull request to the README?
