### ISSUE TITLE
Full width template help

### ISSUE THREAD

**Issue by ecotechie** [wprig/wprig#433]
## Using the 2.0 branch
I realize I'm likely being very dense here and I'm approaching this wrong...

## Issue Overview
Not able to fully remove sidebar from page template

## Steps to Reproduce
1. activate optional template, custom-page-template.php
2. remove get_sidebar() function call, this removes sidebar

## Expected Behavior
A full page setup like front-page.php template has.

```
.site {
    margin: 0 auto;
    max-width: 100%;
}
```

## Current Behavior
Sidebar is not loaded, but the `.has-sidebar .site` CSS still makes a two column grid taking the space of the sidebar.
 
```
.has-sidebar .site {
    margin: 0 1em;
    display: grid;
    grid-template-columns: 3fr 1fr;
    grid-gap: 2rem;
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
}
```

**Comment by benoitchantre** [comment]
In the `Sidebars` component, you need to define the template files that don't have a sidebar.

https://github.com/wprig/wprig/blob/b3edfa4c488ff03aeed4770ed5a75973db4e3227/inc/Sidebars/Component.php#L90-L92

**Comment by ecotechie** [comment]
Thanks a million @benoitchantre! I looked everywhere and ended up hacking the css to do it. But This Is The Way :+1:
