### ISSUE TITLE
Can I use wprig to update existing theme?

### ISSUE THREAD

**Issue by AmirHosseinSaadatmand** [wprig/wprig#434]
## Issue Overview
Can I use wprig to update existing theme?

What should i do?

Thank you a lot

**Comment by ataylorme** [comment]
@AmirHosseinSaadatmand I am not sure what you are asking.

Do you:
1) Have an existing theme that does not have WP Rig implemented at all and want to start using it
1) Have a WP Rig theme using v1 and want to update to v2

In either case, I think the answer is the same - download v2 of WP Rig and then work on bringing over the templates, CSS, etc. from your existing theme.

**Comment by mor10** [comment]
Answered. closing.
