### ISSUE TITLE
IE11 : sub menus don't work

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#437]
## Issue Overview

We can see the following Javascript error located in `navigation.js`:
`Object doesn't support property or method 'forEach'`

https://github.com/wprig/wprig/blob/b3edfa4c488ff03aeed4770ed5a75973db4e3227/assets/js/src/navigation.js#L41-L43

Tested with IE11 in BrowserStack.

## Possible Solution

Replace the `forEach` loop by a `for` loop

**Comment by ataylorme** [comment]
@benoitchantre I'm of the opinion that if your project requires IE 11 support you should add a polyfill. [Here is one for `forEach`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Polyfill).

Alternatively, you could enqueue a new script [from polyfill.io](https://polyfill.io/v3/url-builder/) for the features you need to polyfill.

Perhaps this can be a documentation issue?

**Comment by benoitchantre** [comment]
Thank you for the links @ataylorme.

If you don’t mind, I’m curious to knows why you advise to use a polyfill rather than to adapt the loop as we have only one usage of a `forEach` loop. From my readings, a `for` loop is a lot more performant than a `forEach` loop.

If WP rig doesn’t officially support IE11, I think that should be documented. Ideally, the documentation would include known issues and ways to solve these issues (like you answer)

**Comment by ataylorme** [comment]
I am not against using a `for` loop in this specific case.

I guess my input for a polyfill is more a general opinion. Each WP Rig user's project needs will differ and someone supporting older browsers should look to use polyfills in their projects in general, regardless of it they are based on WP Rig

**Comment by benoitchantre** [comment]
Thank you. I will submit a PR to fix that with a `for` loop.

Do you want I open a separate issue about a browser support documentation?

**Comment by ataylorme** [comment]
Yes, a separate issue for browser support/IE documentation would be great. I think that is important as we move from beta to a full release

**Comment by benoitchantre** [comment]
I did a PR that uses `for` loops instead of `forEach`. Unfortunately, sub menus are not working in IE11. Same result with a polyfill instead of this PR.

If someone has an idea why, I'm not against some help. 🆘

**Comment by benoitchantre** [comment]
Closed by #438.
