### ISSUE TITLE
Add Stylelint

### ISSUE THREAD

**Issue by ai** [wprig/wprig#44]
## Issue Overview

Feature request to add Stylelint, CSS linter.

Thanks for the project. It is awesome, that you promote ESLint for JS code quality control. Maybe we should do the same for CSS?

Stylelint right now is the most powerful and the most popular CSS linter. 
https://stylelint.io/

There is even Stylelint config from WordPress team
https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress

## Expected Behavior

Use Stylelint to lint CSS

## Current Behavior

Only ESLint for JS

## Possible Solution

Add Stylellint

**Comment by mor10** [comment]
I need to test this out. Right now, PHPCS is running CSSLint on all CSS files.

**Comment by ai** [comment]
@mor10 cool! It is awesome that CSS code right now is protected.

BTW, even CSS Lint author think that Stylelint is better ;)
https://twitter.com/slicknet/status/1012002688622399488

**Comment by ai** [comment]
@mor10 Stylelint needs a config (the same was as in ESLint, there is no default config, you must select rule manually or to use some community shared config). So it will be better to decide what rules are important for you.

But I will send you a PR with a code to use Stylelint in Gulp:

**Comment by ai** [comment]
Here is PR with initial support: https://github.com/wprig/wprig/pull/45

What could be added:

- [ ] Mention Stylelint in the docs.
- [ ] Add `stylelint-config-recommended-scss` and lint Sass files in `sass` Gulp task. But in this case, we need to separate origin CSS files and compiled from Sass CSS files (to not lint Sass files twice).
- [ ] Stylelint could automatically fix some of the problems. Maybe we need to give a simple way to use this feature for users? Maybe `pre-commit` hook?
- [ ] Review WordPress Stylelint config. Maybe add some other rules like keep persist order of properties?

**Comment by ataylorme** [comment]
I took a stab at this in #56. 

> Stylelint could automatically fix some of the problems. Maybe we need to give a simple way to use this feature for users? Maybe pre-commit hook?

[`gulp-stylelint`](https://www.npmjs.com/package/gulp-stylelint) has an option to do fixes inline. I set it so it fixes what it can before writing the output CSS file. It might make more sense to update the source file rather than the destination though. Maybe this could be a new gulp task that can be added to `scripts` in `package.json` as `npm run fix-styles` or similar.

> dd stylelint-config-recommended-scss and lint Sass files in sass Gulp task. But in this case, we need to separate origin CSS files and compiled from Sass CSS files (to not lint Sass files twice).

This should be doable now that #47 is merged as sass files get written to the same destination as CSS files rather than the CSS dev directory.

**Comment by ataylorme** [comment]
> Review WordPress Stylelint config. Maybe add some other rules like keep persist order of properties?

If we keep with the current WordPress rules there are quite a few violations in `dev/style.css` (see the attached report).

[wp-rig-stylelint-report-wordpress-coding-standards.txt](https://github.com/wprig/wprig/files/2198399/wp-rig-stylelint-report-wordpress-coding-standards.txt)

**Comment by mor10** [comment]
Merged with v1.1. Closing.

**Comment by ataylorme** [comment]
@mor10 what do you want to do about the existing coding standard violations in WP Rig? They are mostly in CSS

**Comment by mor10** [comment]
I thought they were fixed. If not, I'll get it sorted.

**Comment by mor10** [comment]
I believe all of this is now resolved. Closing.
