### ISSUE TITLE
Menu Toggle Not Working Correctly

### ISSUE THREAD

**Issue by ColtonGO** [wprig/wprig#440]
## Issue Overview

I am having the menu toggle issue previously reported. I just tried again with a fresh copy of wprig since the issue someone else created has been closed and moved to the done and it is still not working correctly for me. The only changes made to the fresh copy of wprig are to enable browsersync. Could this be something I didn't setup correctly? I followed along with the videos to install everything else required on my Windows 10 machine.
## Describe your environment

I am using VS Code, Google Chrome, Microsoft Edge, iphone6 (Google Chrome, Safari). I am using WAMP64 with a fresh copy of WordPress 5.1.1
## Steps to Reproduce

1. Sync all using browsersync
2. Menu toggle does not work on any browser on PC or iPhone 6 
3. Navigate away from homepage. Menu toggle works on all browsers except Microsoft Edge (PC)
4. Click website title and menu toggle doesn't work on any browsers.
5. Repeat steps 2-3 and sometimes it works in certain browsers, other times it doesn't.

## Expected Behavior

The menu toggle to display the menu when clicked
## Current Behavior

Clicking the site title seems to consistently break the menu toggle. Other times it's a toss up on whether it will work or not.
## Related Issues and/or PRs

Menu Toggle and Menu Dropdown not Working on iPad #289

**Comment by benoitchantre** [comment]
Are you using the `v2.0` branch?
If yes, did you run `npm run build` before your tests?

**Comment by ColtonGO** [comment]
Turns out I was using the master branch.
I downloaded v2.0 branch and followed the instructions within that branch for installation. I received the this error when running npm run dev:
`Requiring external module @babel/register
internal/modules/cjs/loader.js:711
    throw err;
    ^

SyntaxError: C:\wamp64\www\cressman\wp-content\themes\wprig-2.0\config\config.json: Unexpected token } in JSON at position 107
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.require (C:\wamp64\www\cressman\wp-content\themes\wprig-2.0\config/themeConfig.js:15:25)Config.js:15:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)                        s\pirates\lib\index.js:99:24)
    at Module._compile (C:\wamp64\www\cressman\wp-content\themes\wprig-2.0\node_modules\pirates\lib\index.js:99:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR!                                                                              utput above.
npm ERR! Failed at the wprig@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                          ebug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\colto\AppData\Roaming\npm-cache\_logs\2019-04-25T17_17_51_631Z-debug.log`

Here is the log:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle wprig@2.0.0~predev: wprig@2.0.0
6 info lifecycle wprig@2.0.0~dev: wprig@2.0.0
7 verbose lifecycle wprig@2.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle wprig@2.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\wamp64\www\cressman\wp-content\themes\wprig-2.0\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\wamp64\bin\php\php7.3.1;C:\ProgramData\ComposerSetup\bin;C:\Users\colto\AppData\Local\Microsoft\WindowsApps;C:\Users\colto\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\colto\AppData\Roaming\npm;C:\Users\colto\AppData\Roaming\Composer\vendor\bin
9 verbose lifecycle wprig@2.0.0~dev: CWD: C:\wamp64\www\cressman\wp-content\themes\wprig-2.0
10 silly lifecycle wprig@2.0.0~dev: Args: [ '/d /s /c', 'gulp' ]
11 silly lifecycle wprig@2.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle wprig@2.0.0~dev: Failed to exec dev script
13 verbose stack Error: wprig@2.0.0 dev: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid wprig@2.0.0
15 verbose cwd C:\wamp64\www\cressman\wp-content\themes\wprig-2.0
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error wprig@2.0.0 dev: `gulp`
22 error Exit status 1
23 error Failed at the wprig@2.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

Any ideas on what I could be doing wrong?
Help would be greatly appreciated.

**Comment by benoitchantre** [comment]
Run `npm install` and `composer install`, then try to run again `npm run dev` or `npm run build`

**Comment by ColtonGO** [comment]
Here is what shows when running those:
PS C:\wamp64\www\cressman\wp-content\themes\wprig-2.0> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 18796 packages in 8.308s
found 10 vulnerabilities (3 low, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS C:\wamp64\www\cressman\wp-content\themes\wprig-2.0> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility/,../../wp-coding-standards/wpcs/
PS C:\wamp64\www\cressman\wp-content\themes\wprig-2.0> npm run dev

> wprig@2.0.0 dev C:\wamp64\www\cressman\wp-content\themes\wprig-2.0
> gulp

[11:24:07] Requiring external module @babel/register
internal/modules/cjs/loader.js:711
    throw err;
    ^

SyntaxError: C:\wamp64\www\cressman\wp-content\themes\wprig-2.0\config\config.json: Unexpected token } in JSON at position 107
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.require (C:\wamp64\www\cressman\wp-content\themes\wprig-2.0\config/themeConfig.js:15:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (C:\wamp64\www\cressman\wp-content\themes\wprig-2.0\node_modules\pirates\lib\index.js:99:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\colto\AppData\Roaming\npm-cache\_logs\2019-04-25T18_24_08_550Z-debug.log
PS C:\wamp64\www\cressman\wp-content\themes\wprig-2.0>

**Comment by ehowey** [comment]
I am not at my computer so I am not 100% sure this is the same as what happened for me. Are you by chance using the same “wprig” folder name?

If so try downloading a fresh copy of the 2.0 branch and change the folder name to something other than wprig. Like wprig2.  The follow the rest of the install instructions. Maybe that fixes it?...I had something similar once.

**Comment by ColtonGO** [comment]
I didn't change the original folder name from "wprig-2.0" but I did as you suggested and used the folder name "wprig2" and it seems to work.

The issue I have now is that when I define custom settings in config.json they don't work. So when I run npm run dev browsersync is still proxying "wprig.test:8888". If I try editing the config.default.json file I get the error from before...

On a different note, is there still supposed to be a dev folder like with the master branch?
I appreciate your time and effort.

**Comment by ehowey** [comment]
We sound very similar in what difficulties we ran into in the install process...I think I had something similar like this too.  What I found is that there are some opening and closing `{` in the config file that are easy to get wrong.  I found the easiest thing was to just copy and past the whole config.default.json file into the config.json file and edit it.  I know this isn't exactly what the install instructions say to do, that you can just copy the parts of config.default.json you need and leave the rest...I ran into some kind of problem doing this as well; something with how the settings were nested in the `{` brackets which is maybe what is happening for you too?

**Comment by ColtonGO** [comment]
I tried copy and pasting everything from config.default.json to config.json and making my edits. Browsersync now works but none of the changes to slug, name, etc are functioning.

**Comment by ehowey** [comment]
I believe that is working as intended Colton. Those are replaced in the production process. You should see those replaced when you run the command “npm run bundle”

**Comment by ColtonGO** [comment]
haha ok sweet.
Thanks for your help!
