### ISSUE TITLE
Google Fonts: subset defaults to `latin-ext` instead of `latin`

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#444]
## Issue Overview

`Latin Extended` allows to support more languages, but the file to download is bigger than `Latin`. If the website don't need extended characters, this is a waste of bandwidth.

By default Google Fonts gives you a link with `Latin` subset.

Theme authors should be able to change the character support.
The default value for `subset` should be `latin` because not all fonts support `latin-ext`.

Edit: looking at this issue again, I think the only change needed is an update of the default value for `subset`. Theme authors can change the value directly if needed.

**Comment by mor10** [comment]
Is there a list somewhere of what languages use `latin-ext`?

**Comment by benoitchantre** [comment]
[According to Wikipedia](https://en.m.wikipedia.org/wiki/Latin_Extended-A), languages that use the followings alphabets:

- Catalan
- Czec
- Latin
- Latvian
- Lithuanian
- Polish
- Slovak
- Turkish
- Welsh

I just found that Google Fonts serve a stylesheet that contains all sunsets to major browsers even if we specify a subset, because they [browsers are able download only what they need](https://caniuse.com/#feat=font-unicode-range) based on the Unicode ranges they find in the page.

See https://github.com/google/fonts/issues/1189

I think we can safely remove `subset` from the query arguments.

**Comment by ataylorme** [comment]
Closed by #446
