### ISSUE TITLE
Reconsider the name of the `Sidebars` component

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#448]
I think the term _Sidebars_ is ambiguous, because it is tied to a specific layout that could not be used by the theme. A generic term like _Widget Areas_ would be more neutral and aligned with [future changes in the admin](https://make.wordpress.org/design/2019/04/24/widgets-to-blocks-ux-flow-proposal/).

![gp2-widget-areas](https://user-images.githubusercontent.com/1521015/56951574-7cf0b080-6b38-11e9-87a5-d04351f88590.png)

A theme can register many widget areas without having one displayed next to the content (eg. widget areas for the footer, after the content, ...)

Do you agree to rename that component?

**Comment by benoitchantre** [comment]
I forgot to discuss that during yesterday office hours. What are your opinions on this @mor10?

Feedbacks from everybody are welcome.

**Comment by mor10** [comment]
Breaking change. Needs discussion.

**Comment by robruiz** [comment]
Im going to close this as it seems out-dated. Also, I believe FSE template-parts addresses this in a different way.
