### ISSUE TITLE
add_image_size() not used: is there a need for documentation or code?

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#453]
## Issue Overview

I have noticed that there's no usage of `add_image_size()` in WP Rig, because there's currently no need for custom image sizes due to its simple design.

There's a high chance that themes build on WP Rig will need custom image sizes and that they want to make them available in the editor sizes list.

## Possible Solution

Based on that assumption, I see the following options:

- do nothing: that's the job of developers to add the required features
- add some documentation: how to add custom image sizes, how to filter sizes properly, ...
- add methods in the component but don't initialize them

What are your opinions?

**Comment by ehowey** [comment]
Documentation would be great...I had to figure this one out on my own and not even sure I really did it the right way...works...but I am still wrapping my head around all of those components.  It was a bit confusing that there was a component called "Image_sizes"...I ended up putting it in a custom component I made for the project I am working on.  I just tucked it into the initialize function like this:
`public function initialize() {
		add_action( 'customize_register', array( $this, 'action_register_customizer_control' ) );
		add_image_size( 'lwb-featured', 720, 300, true );
	}`

**Comment by benoitchantre** [comment]
Can be closed, unless we think there's a need for documentation.
