### ISSUE TITLE
Sidebar not aligned with the content

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#457]
## Issue Overview

When the viewport is not large enough to display the sidebar next to the content but wider than `48em` (value of `--content-width` + `3rem` for side padding), there's a wrong alignment of the sidebar.

The width of the sidebar should be limited. It should also be centered like the content.

## Screenshots / Video

![Capture d’écran 2019-05-02 à 17 38 21](https://user-images.githubusercontent.com/1521015/57087850-431ed600-6d01-11e9-88de-80a66a23291d.png)

**Comment by ataylorme** [comment]
Closed by #458
