### ISSUE TITLE
Jetpack Infinite Scroll Not Working Without Tweaks in 2.0

### ISSUE THREAD

**Issue by ehowey** [wprig/wprig#459]
## Issue Overview
When you activate the infinite scroll setting in Jetpack it does not work as the wrong container is specified and also the render loop is not complete.

## Describe your environment
Clean install of latest 2.0 branch, otherwise N/A

## Steps to Reproduce

1.  Clean install of WP-RIg
2.  Most recent version of Jetpack
3.  Turn on Infinite Scroll
4.  Does not load more content.

## Expected Behavior
Load more content.

## Possible Solution
Incoming pull request with the required small fixes.

**Comment by benoitchantre** [comment]
Closed by #460.
