### ISSUE TITLE
Only run styles process on changed files

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#46]
## Issue Overview

When the `styles` process runs, it runs through all CSS files every time. This adds unnecessary lag in the system.

## Possible Solution

Use `newer` in combination with some logic to run the `styles` process on changed files only. Probably something similar to the logic around the `php` task created by @hellofromtonya.

### Caveats:
Some conditions need to be accounted for:
- First run (process all SCSS and CSS files)
- Changes to `/dev/config/cssVariables.json` (process all SCSS and CSS files)
- `bundle` script (process all SCSS and CSS files)

## Related Issues and/or PRs

Issue came up during testing around #42

**Comment by mor10** [comment]
You want to take a crack at this @hellofromtonya?

**Comment by hellofromtonya** [comment]
@mor10 I'm on it.

**Comment by hellofromtonya** [comment]
After reviewing this issue over the weekend, I propose that we roll the fix in after we get PR #47 merged in.  Why?  The new architecture that @ataylorme has laid out will make this job much easier...and more clean too.

@mor10 Are you cool with that?

**Comment by mor10** [comment]
Yes, that's my thinking too. I'll try to get #47 merged into the 1.1 branch tomorrow or Wednesday so we can move forward.

**Comment by mor10** [comment]
Closing as this is resolved in #47 which will be merged with 1.1 branch as soon as the PR is squashed.
