### ISSUE TITLE
Headings in _typography.css not using css variables v2.0

### ISSUE THREAD

**Issue by ehowey** [wprig/wprig#462]
## Issue Overview
Just going through and working on some things in v2.0 and I noticed that the code for headings in _typography.css is not using a css variable for the heading color...I assume this is just a small bug.  Incoming pull request to fix.

## Expected Behavior
Headings to use the CSS Custom Properties.

## Current Behavior
Currently the code looks like this:
`h1,
h2,
h3,
h4,
h5,
h6 {
	font-family: var(--highlight-font-family);
	color: #32373c;
	clear: both;
}`

## Possible Solution
`color: var(--global-font-color);`

**Comment by benoitchantre** [comment]
Closed by #463.
