### ISSUE TITLE
v2.0 documentation: All hands on deck!

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#466]
With `v2.0` in Beta, we are entering the [documentation phase](https://github.com/wprig/wprig/projects/5). Anyone can contribute to documentation for WP Rig. To make documentation writing as straight-forward as possible, I have created a [Google Drive folder](https://drive.google.com/drive/folders/1hSLx0qmCUAIa0vwa4Q5PQyqK3rUpZF-6?usp=sharing) with all the documents from the [Wiki](https://github.com/wprig/wprig/wiki) and additional documents in need of writing. The resulting documentation will live in the Wiki.

If there are any documents missing, please let me know in this issue and I'll add it to the [Drive folder](https://drive.google.com/drive/folders/1hSLx0qmCUAIa0vwa4Q5PQyqK3rUpZF-6?usp=sharing).

To contribute to the documentation, simply contribute comments, edits, and content to the Drive documents.

**Comment by benoitchantre** [comment]
I would love to see:

- best practices & known issues related to responsive images sizes
- things to do for themes aimed for wp.org (eg. how to include source files: #339)
- browsers support (#439)

**Comment by ehowey** [comment]
I really like the way functions.php has been dealt with and the new PHP architecture - way better than the old method of having a huge functions.php file with a mess of stuff BUT what I found hard being more of a hobbyist developer is that I couldn't just copy and paste a code snippet and it would work.  I had to go through and figure out how to properly initialize it and a few other things.  I would love to see a "code snippet" type library with some plug and play components for common site functions.  I would be happy to help contribute to this library but given my relative experience would probably want some oversight in terms of code quality as I had to learn some this by trial and error based on the examples from the current documentation and existing components.

**Comment by mor10** [comment]
I've added documents for responsive images, public themes, browser support, and code snippets. Feel free to contribute

**Comment by timnolte** [comment]
I'm trying to figure out, based on the installation steps, how putting your development under source control works of the directory is supposed to be left as wprig under themes and an mom build will create a theme directory for you. I need to keep under source control the development side of the theme, not just the final output.

**Comment by timnolte** [comment]
Thinking about it, I suppose my actual development repository can be my theme directory but then clone it as wprig for actual development, but the then gets hard to manage when working on multiple themes with wprig as the start.

**Comment by ataylorme** [comment]
@timnolte the way I approach this is to work on an external Git repository (e.g. GitHub) where I only have the development version of WP Rig committed. A continuous integration service then builds the production theme, deleted the dev version of the theme, and deploys the result to my website.

**Comment by timnolte** [comment]
@ataylorme I think I've got a working setup now. The latest version of the wprig documentation is a bit more clear on not just leaving it as wprig but prepending your theme directory with wprig for development. My next hurdle is how to apply the wprig changes to an existing theme. Since it doesn't seem viable to just do a git merge.

**Comment by robruiz** [comment]
We have moved all documentation for WP Rig to wprig.io/documentation. Closing this issue.
