### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by anoopd** [wprig/wprig#470]
## Issue Overview
npm install gives `found 17 vulnerabilities (10 low, 5 moderate, 2 high)`, and `audit fix` gives `17 vulnerabilities required manual review and could not be updated`

`npm run build ` gives  `Failed to load external module @babel/register` and `Requiring external module babel-register`
## Describe your environment
 - mac os mojave
- node -v `v11.6.0`
- npm -v  `6.9.0`
- gulp -v `CLI version: 2.2.0`
                   `Local version: 4.0.0`

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mor10** [comment]
These types of errors are not really errors, but related to dependencies that are not up to date. We keep WP Rig's dependencies up to date, but dependencies of dependencies are out of our control. Closing as out of scope.
