### ISSUE TITLE
entry-header rules too specific

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#472]
The selector for `.entry-title` seems too specific in `./assets/css/src/_typography.css`:

https://github.com/wprig/wprig/blob/v2.0/assets/css/src/_typography.css#L31-L32

I think it should be just

```css
.entry-title,
.page-title {
...
}
```

Is there a reason for this level of specificity?

**Comment by benoitchantre** [comment]
I think the specifity could be lowered as proposed, but there's a need to have a different sizes for the post title when it is part of an archive or of search results

We will need an `h2.entry-title` for archives and search results to adjust the size.

**Comment by benoitchantre** [comment]
@mor10 Do you want to submit a PR?
