### ISSUE TITLE
Gulp Watch fails on Windows because backslashes are bad

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#492]
## Issue Overview

Gulp watch fails on Windows because the path uses backslashes instead of forward slashes: https://github.com/paulmillr/chokidar/issues/668#issuecomment-357235531

To fix: Magically change Windows paths to use forward slashes.

**Comment by ataylorme** [comment]
@mor10 can you try adding `.replace(/\\/g, '/')` to paths in gulp watch?

[`gulpWatch(paths.styles.src[0], series( styles, editorStyles ) );`](https://github.com/wprig/wprig/blob/v2.0/gulp/watch.js#L37) would become `gulpWatch(paths.styles.src[0].replace(/\\/g, '/'), series( styles, editorStyles ) );`, for example.

**Comment by mor10** [comment]
Yes, adding `.replace(/\\/g, '/')` works!

**Comment by ataylorme** [comment]
Closed by #493
