### ISSUE TITLE
Wrong placeholder text for custom taxonomies

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#502]
## Issue Overview

The placeholder text is hardcoded based on hierarchical property of the taxonomy.

https://github.com/wprig/wprig/blob/a74f1a813854e23dd99332ef9757256a28f94cf7/template-parts/content/entry_taxonomies.php#L44-L50

When there's a custom taxonomy, the placeholder text will be either `Categories: %s` or `Tags: %s`.

## Expected Behavior

The placeholder text should be based on the taxonomy labels.

## Possible Solution

Use the `name` from the taxonomy labels.

**Comment by ataylorme** [comment]
Closed by #503
