### ISSUE TITLE
Add support for PurgeCSS or similar on bundle to further optimize production files

### ISSUE THREAD

**Issue by ehowey** [wprig/wprig#507]
## Issue Overview
The bundle process minifies the css however, from what I can see, does not purge unused CSS, leaving sometimes unnecessary css in the production files. I am unsure whether this would be possible however I have been playing around lately with another framework (non-WP) entirely that includes this feature which is a nice-to-have.  I thought it might make a good addition to WP-Rig and fit the philosophy of the theme. It would be important to run this only when using the `npm run bundle` command however.  

## Possible Solution
Would it be possible to implement [PurgeCSS](https://www.purgecss.com/#gulp)?

**Comment by ataylorme** [comment]
@ehowey thanks for starting a discussion. PurgeCSS needs the rendered HTML to determine what CSS is needed. There is not a way to determine that at bundle time in the gulp tasks as WordPress needs to run to serve the HTML - there are not `.html` files to scan.

[The WordPress AMP plugin](https://wordpress.org/plugins/amp/) does what you want, CSS Tree Shaking, in PHP and serves only the CSS needed by the page.

WP Rig is AMP compatible. You should try creating a Native AMP theme to increase performance. [Bill Erickson just wrote a great article on how to get started with AMP and WordPress](https://www.billerickson.net/native-amp-wordpress/) that covers the gotcha's, mostly around not having JavaScript.

**Comment by ehowey** [comment]
Thanks for explaining this.  I will close it given this information.  I appreciate the quick answer.
