### ISSUE TITLE
Duplicate Page Templates in Selection Picklist (Dev and Verbose)

### ISSUE THREAD

**Issue by joseph-farruggio** [wprig/wprig#51]
## Question Overview

When selecting a page template, I see three instances of the two page templates I created. When inspecting the select list, I learned that the duplicates are coming from the /dev folder and the /verbose folder.

`<select id="template-selector-0">
    <option value="">Default template</option>
    <option value="dev/header.php">Contact</option>
    <option value="dev/landing-page.php">Landing Page</option>
    <option value="header.php">Contact</option>
    <option value="landing-page.php">Landing Page</option>
    <option value="verbose/header.php">Contact</option>
    <option value="verbose/landing-page.php">Landing Page</option>
</select>`  

Why is this? Which template should I be selecting?

**Comment by solarianian** [comment]
Hey! My understanding is as follow (please correct me if I am wrong):

According to documentation, /dev folder is where we develop the theme. When ready, npm build command will generate a .zip with ready to use in production theme. /verbose folder acts as a back-up for /dev folder. Also, a /verbose folder is to be find in production theme, with untouched files theme, meaning no min for js and css files. Practically, /verbose folder should have no functionality in the theme, other then a back-up folder developed theme in /dev folder.

**Comment by mor10** [comment]
I'm classifying this as a bug. The original thinking was to minify all files including php files in which case the verbose version needed to be present in the theme. However, this is not necessary as the php files are not minified. I'll take out the copying of php files to the verbose folder in the current master branch and let @ataylorme to do the same in the gulp rewrite at #47.
