### ISSUE TITLE
WPRig v2.0-beta 1

### ISSUE THREAD

**Issue by idea--list** [wprig/wprig#514]
## Issue Overview

I downloaded the v2.0-beta.1 release, run npm install with just 2 warnings.
However `npm run build` just fails with the following:

[00:38:28] Requiring external module @babel/register
[00:38:30] Using gulpfile C:\wamp64\www\menes\wp-content\themes\mytheme\gulpfile.babel.js
[00:38:30] Starting 'buildDev'...
[00:38:30] Starting 'php'...
[00:38:30] Starting 'images'...
[00:38:30] Starting 'scripts'...
[00:38:30] Starting 'translate'...
[00:38:31] Starting 'styles'...
[00:38:32] gulp-imagemin: Minified 0 images
[00:38:32] Finished 'images' after 1.43 s
[00:38:33] 'php' errored after 2.49 s
[00:38:33] Error in plugin 'gulp-phpcs'
Message:
    Cannot find "C:\wamp64\www\menes\wp-content\themes\mytheme/vendor/bin/phpcs"
[00:38:33] 'buildDev' errored after 2.5 s
[00:38:33] The following tasks did not complete: <series>, scripts, translate, styles
[00:38:33] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.0 build: `gulp buildDev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Describe your environment
Windows 10 x64
WAMP 3.1.7 (PHP 7.2.14 set as active)
NODE JS v10.16.0 installed
Composer v1.8.6 installed

Can someone please help me how to get v2.0 working on windows 10?

**Comment by ehowey** [comment]
Try the 2.0 branch instead of the beta release. There was a recently merged pull request that related to an error with windows, this might fix the problem for you. You should be able to see the details about this if you look at recent commits to the 2.0 branch. I think it was within the last 2-3 weeks.

**Comment by idea--list** [comment]
@ehowey 
Thanks for the fast reply! Just tried the v2.0 branch but i face the same situation.
npm install outputs:
`  √ optipng pre-build test passed successfully
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

but then npm run build just fails with the same message i posted before.

**Comment by ehowey** [comment]
Oh I know what this is - sorry I didn’t look at your original post in enough detail. Check the documentation in the 2.0 branch. The install command is actually “npm run rig-init”. I am on my phone so t is awkward to double check. It looks like you did not get all your php dependencies installed potentially.

**Comment by ehowey** [comment]
Also - use a fresh directory, e.g., “wprig-mytheme2”.  I ran into some weird errors when flipping between 1.0x and 2.0 that solved with this.

**Comment by idea--list** [comment]
Thanks! That was it indded, i just did not find the documentation first and used the same commands as for v1.0.4 ;-)

**Comment by idea--list** [comment]
I can run `npm run dev` and `npm run build` without any problem.
But trying `npm run bundle` just fails with:

`'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by idea--list** [comment]
Found #494 that solves the issue and now i can build themes with WPRig v2.0 on windows.
