### ISSUE TITLE
Footer does not always remain on the bottom of the page when there is minimal content

### ISSUE THREAD

**Issue by ehowey** [wprig/wprig#517]
## Issue Overview
With the current CSS the footer is just placed at the end of the content, in almost all cases this results in the footer being at the bottom of the page or off the page entirely however on sites with smaller header areas and little content the footer comes up off the bottom of the page resulting in a less than appealing look.

## Describe your environment
N/A

## Steps to Reproduce
Create a page with a small amount of content, view it on a large resolution monitor.

## Expected Behavior
Footer to remain on the bottom of the page even when the content does not reach there.

## Current Behavior
Footer defaults to the end of the content.

## Possible Solution
See incoming PR, please review closely as there may be a better or more effective way to do what I did.

## Related Issues and/or PRs

#518

**Comment by felixarntz** [comment]
See https://github.com/wprig/wprig/pull/518#issuecomment-504058621
