### ISSUE TITLE
Composer failure on npm install

### ISSUE THREAD

**Issue by SimonParfittCode** [wprig/wprig#519]
Hi Mor10,

I'm very keen to start using WPRIG, as currently use _underscores start theme & Codekit 3 for developing WordPress websites, but feel maybe this is out-of-date and want to start using modern tools.

So, after downloading the WPRIG files, I then running the "npm install" command I get the error:

<img width="913" alt="58419676-26b55580-8083-11e9-8997-bce0941f76e0" src="https://user-images.githubusercontent.com/1633650/59507352-b2601c00-8ea2-11e9-83b4-5c40b09ba5fb.png">

I'm sure I have install composer globally though, when I run the command "composer --version" I get the result of 1.8.5 and running command "composer" I get the attached screenshot.

<img width="917" alt="58419677-26b55580-8083-11e9-98c1-bc4da1802a82" src="https://user-images.githubusercontent.com/1633650/59507522-239fcf00-8ea3-11e9-9284-78cce4fa1c40.png">

I'm new to the world of the command line, scary, so not sure what I'm doing wrong - please help, so eager to start using WPRIG.

Many Thanks ,
Simon

**Comment by SimonParfittCode** [comment]
Thanks @ataylorme,

I am now using the 2.0 version and trying to follow along with Mor10's LinkedIn video series, looks a little different. Successfully installed Composer (so installing it globally doesn't seem to make a difference?) and npm install - both new folders "node_modules" and "vendor".

Is there any documentation to the 2.0 version? I see there is no "dev" folder any more and the configuration seems a little different, at my level I need as much hand holding as possible :)

Cheers,
Simon

**Comment by ataylorme** [comment]
Hi @SimonParfittCode,
We just finalized the code for version `2.0` a few weeks ago and are still working on documentation.

The [`README`](https://github.com/wprig/wprig/blob/master/README.md) has a good intro and there are more in-depth articles on [the wiki](https://github.com/wprig/wprig/wiki).

I think @mor10 is working on new videos as well but I don't know when those will be done.

**Comment by mor10** [comment]
the [new LinkedIn Learning course is out and available to view](https://www.linkedin.com/learning/wordpress-building-progressive-themes-with-wp-rig-2/). Should answer your questions. Also check out the new [docs](https://github.com/wprig/docs) repo for documentation.
