### ISSUE TITLE
npm update failed

### ISSUE THREAD

**Issue by dackr** [wprig/wprig#52]
I have followed the steps that tell me to install the development theme but I get this notice and does not change the style.css data or I do not know what else does not change

![captura de pantalla 2018-07-13 a la s 17 33 35](https://user-images.githubusercontent.com/1920588/42716851-37fc81a2-86c3-11e8-9635-ad11f2d49570.png)

**Comment by mor10** [comment]
Looks like you need to update npm itself. Try running 
```
sudo npm install npm -g
```

**Comment by mor10** [comment]
I've updated Composer, so run the update for npm, then pull down a fresh version of the master branch, and try again. Report back and we'll get you up and running.

**Comment by dackr** [comment]
I have reinstalled composer I get this message.
![captura de pantalla 2018-07-15 a la s 13 07 50](https://user-images.githubusercontent.com/1920588/42736709-4c40f472-8830-11e8-93d5-83d8be408c6a.png)

**Comment by dackr** [comment]
this is what I get when I write 'npm run build'

![captura de pantalla 2018-07-15 a la s 13 56 12](https://user-images.githubusercontent.com/1920588/42737282-13ad69fe-8837-11e8-8c45-69f8af454905.png)

**Comment by mor10** [comment]
Ok, so mom install did not work. The gulp-sass module is not installed. Run `npm install` again. You should end up with a folder called `node-modules` with a ton of sub-folders in it.

**Comment by dackr** [comment]
thanks for your help I installed and reinstalled but now I get this message.
![captura de pantalla 2018-07-16 a la s 09 28 57](https://user-images.githubusercontent.com/1920588/42764947-7a8856a2-88dc-11e8-9c24-a4157d22893a.png)

**Comment by dackr** [comment]
I have rebooted my mac and it seems to work but I get this error.
![captura de pantalla 2018-07-16 a la s 09 54 05](https://user-images.githubusercontent.com/1920588/42765703-3a9a57aa-88de-11e8-9ac6-63fb94aece18.png)

![captura de pantalla 2018-07-16 a la s 09 54 35](https://user-images.githubusercontent.com/1920588/42765778-603ffa14-88de-11e8-8f68-43f953a79d7a.png)

**Comment by dackr** [comment]
when I type 'npm run build' I get this message.
![captura de pantalla 2018-07-16 a la s 09 59 16](https://user-images.githubusercontent.com/1920588/42766104-29f9747a-88df-11e8-994a-a5461c000831.png).
gracias por tu ayuda

**Comment by dackr** [comment]
I already managed to fix thanks only I have the detail of browsersync s and it is possible that you help me in llo please do not work well, do not load the page.
I'm working on localhost with mampp free

**Comment by dackr** [comment]
thank you for your help I have already managed to activate everything thanks for your great project, nice day

**Comment by mor10** [comment]
Great to hear!
