### ISSUE TITLE
ESLint code sniffing does not correctly check WP coding standards

### ISSUE THREAD

**Issue by ataylorme** [wprig/wprig#528]
## Issue Overview
The [`eslint-config-wordpress`](https://www.npmjs.com/package/eslint-config-wordpress) package hasn't been updated in 2 years. PHPCS is officially supported and should be used.

## Steps to Reproduce

1. Run `npm run gulp -- scripts`
2. See that issues reported do not reflect the actual WordPress coding standards

## Expected Behavior
The coding standard violations reported are accurate with the latest version of the WordPress coding standards.

## Possible Solution
Use PHPCS for JS code sniffing instead of ES Lint

**Comment by ataylorme** [comment]
We should be using the official [`@wordpress/eslint-plugin`](https://www.npmjs.com/package/@wordpress/eslint-plugin)

**Comment by benoitchantre** [comment]
Closed by #532
