### ISSUE TITLE
Help Wanted: Restarting Workspace

### ISSUE THREAD

**Issue by muggeridge** [wprig/wprig#53]
If I quit the wprig project, shut down MAMP and restart mac are there any requirements (EG Terminal Commands) when I next continue with development?

**Comment by solarianian** [comment]
from readme.md:

npm run build is the regular development process. While this process is running, files in the ./dev/ folder will be automatically compiled to the live theme and BrowserSync will update if it is enabled.

**Comment by mor10** [comment]
Any time you start development, enter the `nmp run build` command in terminal. This starts the build process which compiles the files and brings BrowserSync online. When you're done you can terminate the process by hitting `Ctrl+c`.
