### ISSUE TITLE
Documentation: some videos are not available at wprig.io

### ISSUE THREAD

**Issue by dashkevych** [wprig/wprig#537]
I've checked the [documentation page](https://wprig.io/course/wprig_en/) at wprig.io site, and some video displays the following message: "This video is no longer available".

**Comment by ataylorme** [comment]
Hi @dashkevych. We just finished the code release of `2.0` but haven't finished updating all the documentation or wprig.io

I believe @mor10 is working on a fresh course/new videos but I don't know the ETA for those.

**Comment by mor10** [comment]
There will be a new version of the course coming out shortly. It's currently in editing. Once it's up, it'll be available on the site. We are also working on more extensive documentation both here on the Wiki and on the site.

**Comment by mor10** [comment]
I'm updating all of this next week. Closing.
