### ISSUE TITLE
How to keep my customized WP Rig Updated?

### ISSUE THREAD

**Issue by vangpl** [wprig/wprig#538]
Adding customizations means that any changes made here on the main repo can't be integrated back into my theme. What's the solution?

Not being able to keep the core framework updated is a massive security flaw.

Thanks for the help!

**Comment by ataylorme** [comment]
Hi @vangpl,

I'm not sure if you are using WP Rig version 1 or the newly released [version 2](https://github.com/wprig/wprig/releases/tag/v2.0).

A version 1 to version 2 migration is not possible - at least not without a lot of manual effort. WP Rig project follows [semantic versioning](https://semver.org/) and version 2 is a rewrite of WP Rig and introduces many breaking changes.

Overall though, I think this is some misunderstanding on WP Rig's purpose. WP Rig is a starter theme, **not** a framework. 

To quote Underscores, another starter theme project:

> I'm a theme meant for hacking so don't use me as a Parent Theme

WP Rig is a starting point for new projects, at which point you should customize it to fit your needs. 

It is not built to have updates continuously merged into your project. Think of starting a new WP Rig project like forking the starting point, at which you own, maintain, and customize it. That means updating dependencies when they have security vulnerabilities is your responsibility.

WP Rig is here to help you have a starting place to build great WordPress themes with modern standards, saving development time compared to starting from nothing.

This is in contrast to a framework, like [Genesis](https://my.studiopress.com/themes/genesis/), that is meant to be used with a child theme and not edited directly. Genesis you install as a parent theme and apply updates to the framework over time.
