### ISSUE TITLE
Travis-CI not executing nightly build tests

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#539]
## Issue Overview
Since https://github.com/wprig/wprig/commit/25eaf84776b7f0fc96c31daae8b92a5f78981377, experimental builds that are allowed to fail aren't run anymore in Travis. That is because `allow_failures` is only used for matching against jobs that are in the actual matrix (see https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail).

## Expected Behavior
Jobs for nightly PHP and WordPress versions should be run, but be allowed to fail.

## Current Behavior
Jobs for nightly PHP and WordPress versions are not run.

**Comment by benoitchantre** [comment]
Closed by #540.
