### ISSUE TITLE
Merge conflict in /v1.1/gulp/php.js#L65

### ISSUE THREAD

**Issue by christophherr** [wprig/wprig#54]
## Issue Overview
 
This is about the v1.1 branch.
A merge conflict was left/appeared in https://github.com/wprig/wprig/blob/v1.1/gulp/php.js#L65 causing the Gulp task to error.
## Describe your environment

Windows 10 (not WSL)
## Steps to Reproduce

1. Checkout the v1.1 branch
2. run `npm install`
3. ignore that Guetzli doesn't seem to build on Windows 10.
4. run `npm run build`

## Expected Behavior

The Gulp tasks run.
## Current Behavior

Gulp errors.
## Possible Solution

Remove the merge conflict.
## Screenshots / Video

![gulp error](https://user-images.githubusercontent.com/8683126/42729753-982484ba-87b0-11e8-815d-d6b810abfd65.png)

**Comment by mor10** [comment]
This should be solved now with #55. Feel free to reopen the issue if the problem persists after pulling the latest update.
