### ISSUE TITLE
Array syntax: coding standards changes

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#553]
Arrays have been converted recently in WP Rig to use the short syntax as proposed in the Coding Standards Proposal.

> ## Coding Standards Proposal
> Arrays must be declared using short array syntax in WordPress Core. Arrays may be declared using short array syntax outside of Core.

https://make.wordpress.org/core/2019/03/26/coding-standards-updates-for-php-5-6/

Recently, a new post has been published about PHP Coding Standards Changes

> ## Short Array Syntax
>A little less controversial, but still with varying opinions, was the proposal to require short array syntax ( [ 1, 2, 3 ] ) instead of long array syntax ( array( 1, 2, 3 ) ) for declaring arrays.
>
>While I’m personally partial to short array syntax, there were two particularly convincing arguments for using long array syntax:
>
>It’s easier to distinguish from other forms of braces, particularly for those with vision difficulties.
>It’s much more descriptive for beginners.
>
>So, this change to the coding standards is the opposite of what was originally proposed, but is ultimately the more inclusive option.
> ### Coding Standards Change
> Arrays must be declared using long array syntax in WordPress Core.

https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/

@felixarntz, @ataylorme Should we go back to long array syntax or add an exception in `phpcs.xml.dist`?

**Comment by ataylorme** [comment]
I think we should follow the standard and go back to the long format `array` syntax. While I prefer the short syntax the reasons outlined in the post are valid

> - It’s easier to distinguish from other forms of braces, particularly for those with vision difficulties.
> - It’s much more descriptive for beginners.

**Comment by aristath** [comment]
the long array syntax guideline is only for WP-Core, not for themes or plugins.

**Comment by ataylorme** [comment]
> the long array syntax guideline is only for WP-Core, not for themes or plugins.

Yes, I understand that. However, I think their _reasons_ for choosing to use the long array syntax I highlighted above are valid and good reasons for WP Rig to use it as well.

**Comment by benoitchantre** [comment]
Closed by #557.
