### ISSUE TITLE
Trouble getting nesting css to work

### ISSUE THREAD

**Issue by Webfor247** [wprig/wprig#561]
I've just started diving into WP Rig as a potential starting off point for my company theme dev workflow.  Previously we've been using Understrap, but I've been researching more lightweight and modern solutions, which has led me here.  In my testing, everything is working fine except we're having issues getting the nested styles to work.  This is entirely possible that it's just me missing something as I'm extremely new to using PostCSS. 

## Issue Overview
When trying to use nested CSS, I'm given en error by stylelint and the style is processed as nested in the min.css file as well.

## Describe your environment
VS Code, Macbook Pro

## Steps to Reproduce

1. Install a fresh theme via github tutorial.
2. Once running, attempting to do a test nested style with the .site-header wherein I target the h1 with nested styling for testing purposes. 

```
.site-header {
	padding-bottom: 1em;
	h1 {background: red;}
}
```

3. Save and receive errors via stylelint with the nested style getting processed down to the min.css file.

`.site-header{padding-bottom:1em;h1{display:none}}`

## Expected Behavior
Nested styles would be processed into pure css via PostCSS processor.

## Current Behavior
Nested styles not being processed properly

**Comment by benoitchantre** [comment]
Try like that:
```css
.site-header {
	padding-bottom: 1em;

	& h1 {
		background: red;
	}
}
```

**Comment by Webfor247** [comment]
@benoitchantre Thanks! That seems to be the syntax issue I was having.  My stylelint is (understandably) still having a fit but the css is processing as expected now.

**Comment by benoitchantre** [comment]
You're welcome. I'm closing this issue.

**Comment by erdmann040** [comment]
Thanks for reporting this! The nesting issue you experienced was tied to the old PostCSS-based setup. In WP Rig v3 we’ve moved to **Lightning CSS** (with esbuild), which includes built-in support for CSS nesting. The original error no longer applies.

@robruiz This was a PostCSS-specific issue. With the migration to Lightning CSS in v3 it is obsolete. Can be closed.
