### ISSUE TITLE
Invalid value for `container` argument of `wp_nav_menu()`

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#567]
## Issue Overview
`wp_nav_menu()` supports a `container` argument that defines whether the menu's list element should be wrapped and, if so, how. The supported values are `div`, `nav` or `false` (to not provide a wrapping element). WP Rig currently automatically uses `ul`, which is an invalid value.

It doesn't actually break anything, because it will be interpreted as `false`, but is confusing and incorrect, so it should actually be set to `false`.

**Comment by benoitchantre** [comment]
Closed by #569.
