### ISSUE TITLE
Gallery block breaks unexpectedly if it contains as many images as columns

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#570]
## Issue Overview
When a gallery block with an odd number of columns has as many images as it has columns (or a multiple of the number of columns), it unexpectedly breaks although it shouldn't.

For example:
* 5 column gallery with 5 images shows in 2 rows (4+1) although it should be a single row of 5 images.
* 3 column gallery with 9 images shows in 4 rows (3+3+2+1) although it should be three rows of 3 images.

## Possible Solution
This happens because WP Rig sets `.blocks-gallery-item:last-child:nth-child(odd)` to span 2 columns instead of one. This provides a nicer appearance trying to fill up some space in certain case (e.g. 2 columns with 3 images, or 4 columns with 7 images) and must be maintained.

In order to prevent that mechanism from breaking where it shouldn't, we need to ensure that a `columns-x` gallery sets its `.blocks-gallery-item:last-child:nth-child(xn)` back to span just 1 column (i.e. if a gallery with x columns contains a multiple of x images, never have the last image span 2 columns, because the number fits perfectly without any tweaks).

**Comment by benoitchantre** [comment]
Closed by #571.
