### ISSUE TITLE
Config.json (Theme Name,  Php Namespace, etc) Not Reflecting on Build

### ISSUE THREAD

**Issue by Horlaes** [wprig/wprig#572]
## Issue Overview

When I fired npm run build, I noticed no settings I specified in config.json worked as expected with including the theme name and PHP Namespace

## Describe your environment

Win Ver 10.0 (Build 10240)
PHP 7.3.7 
WPRIG V2 IN VSCODE

## Steps to Reproduce

1. created my custom settings in config.json [example ](http://prntscr.com/opetuo)
2.  I ran - npm run build
3. and then npm run dev
4.

## Expected Behavior

1. I expect my stlyes.css to specify the name of my theme since I have specified it in config.json
2. PHP namespace should have what has been specified in config.json

## Current Behavior

Nothing occurred, the other CSS files is working as expected but the Styles.css still has the default settings, also, I noticed the namespace is still the default one WP_Rig, please help, I have spent several days trying to get things done, I migrated form _s

**Comment by Horlaes** [comment]
Someone should please help out, I tried this for about 2 days now, I can't hesitate to start working with WP Rig

**Comment by felixarntz** [comment]
@Horlaes This is expected, the replacements from `config.json` only happen when you run `npm run bundle` (which will deploy the development version of your theme into a separate directory, ready to be published).

In the development version of your theme you should continue to work with the `WP_Rig` etc. values. See [the git workflows documentation](https://github.com/wprig/wprig/wiki/Recommended-Git-Workflow) on more information how this is envisioned and why.

**Comment by Horlaes** [comment]
Alright thanks, after 6 hours of reading and getting to know the wiki, it's so easy, is there any way I can submit an extensive guide on this little stuff? (it's damn confusing at first)
