### ISSUE TITLE
Error in navigation.js

### ISSUE THREAD

**Issue by flegfleg** [wprig/wprig#58]
## Issue Overview

Javascript error prevents navigation from working correctly. The slug is not replaced correctly. 

## Describe your environment
macOS. I get an error `[13:51:10] Failed to load external module @babel/register
[13:51:10] Requiring external module babel-register` but that's unrelated, right?

## Steps to Reproduce

1. clone wp-rig
2. edit themeConfig.js, change slug & name
3. run npm build

## Expected Behavior

`    return e.classList.add("dropdown-toggle"), e.setAttribute("aria-expanded", "false"), e.setAttribute("aria-label", **myThemeName**ScreenReaderText.expand), e`

## Current Behavior

`    return e.classList.add("dropdown-toggle"), e.setAttribute("aria-expanded", "false"), e.setAttribute("aria-label", **myThemeName - theme**ScreenReaderText.expand), e`

**Comment by mor10** [comment]
This is your playground @bamadesigner

**Comment by bamadesigner** [comment]
This has to do with the issues with slug replacement we do during build. Related to #43 and #73.

**Comment by mor10** [comment]
What's the workaround in the meantime @bamadesigner? Something that needs to go in the Wiki?

**Comment by felixarntz** [comment]
@bamadesigner This should be fixed after #123 gets merged.
