### ISSUE TITLE
Enqueue Custom JavaScript Not Working

### ISSUE THREAD

**Issue by venuscrush** [wprig/wprig#601]
## Issue Overview
I tried enqueuing a custom js file as per @justlevine suggestion: 

> Best practice would be to either create something like inc/Scripts/Component.php, or if it's related to a specific feature in your theme, then include it there (for an example, see inc/Lazyload/Component.php line 135).

However, it's not loading on my site. I'm able to see this by viewing the source in my browser. I've also tried to start and restart npm run dev and that didn't work either.

## Describe your environment
Latest WPRIG setup using VSC.

## Steps to Reproduce

```
<?php
/**
 * WP_Rig\WP_Rig\Scripts\Component class
 *
 * @package wp_rig
 */

namespace WP_Rig\WP_Rig\Scripts;

use WP_Rig\WP_Rig\Component_Interface;
use function WP_Rig\WP_Rig\wp_rig;


/**
 * Class for improving various core features.
 */
class Component implements Component_Interface {

	/**
	 * Enqueues flickity JavaScript.
	 */
	public function action_enqueue_flickity_script() {
		wp_enqueue_script(
			'wp-rig-flickity-script',
			get_theme_file_uri( '/assets/js/flickity.pkgd.min.js' ),
			[],
			wp_rig()->get_asset_version( get_theme_file_path( '/assets/js/flickity.pkgd.min.js' ) ),
			false
		);
		wp_script_add_data( 'wp-rig-flickity-script', 'defer', true );
		wp_script_add_data( 'wp-rig-flickity-script', 'precache', true );
	}

	/**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */
	public function initialize() {
		add_action( 'wp_enqueue_scripts', [ $this, 'action_enqueue_flickity_script' ] );
	}
}
```

## Expected Behavior
I would like the script to load onto my website. I successfully loaded a custom CSS file.
 
## Current Behavior
My custom "Styles" component is not loading this js file. I've also tried to start and restart **npm run dev** and that didn't work.

I also have the flickity.pkgd.js file in the js/src folder which WPRIG has minified.

## Possible Solution

Need help / Not sure

## Screenshots / Video
N/A

## Related Issues and/or PRs
N/A

**Comment by justlevine** [comment]
Assuming this is the entire file, you're missing the `get_slug` function at the top of your class that lets wp-rig know to use the file.

```php
/**
 * Gets the unique identifier for the theme component.
 *
 * @return string Component slug.
 */
public function get_slug() : string {
    return 'scripts';
}
```

Add that, and then make sure that `inc/Theme.php`' includes your your new component:
```php
protected function get_default_components() : array {
    $components = [
        ...
        new Scripts\Component(),
        ...
    ];
}
```

(PS: totally unrelated, but you might want to consider using `wp_register_script()` for `flickity`, and then calling `wp_enqueue_script` before your carousel, instead of loading the js on every single page)

**Comment by venuscrush** [comment]
Thank you so much! This works.

Furthermore, I actually tried doing what you suggested in your "unrelated" notes. While I do see the `flickity.js` is loaded on my site, the actual javascript file is not loading. This is what I placed in the `flickity.js` file:

`/**
 * External dependencies
 */
import 'Flickity';
import 'flickity-imagesloaded';
import 'flickity-fullscreen';
`
I've also installed flickity npm. I tried placing  the raw code for`flickity.pkgd.js` in my custom `flickity.js` and it works! So I concluded that `flickity.pkgd.js` needs to be called in somehow? I thought I was doing that by referencing the external dependencies above?

![Screen Shot 2019-09-13 at 4 39 23 PM](https://user-images.githubusercontent.com/38008836/64893447-1979a200-d645-11e9-98ed-bdd79329b9cd.png)

**Comment by justlevine** [comment]
I dont want to go too off-topic here, but here's what should happen if youre using flickity and npm:

1. Install flickity itself `npm install --save flickity`.
2. Install any flickity extensions you need. From your example thats `npm install --save flickity-imagesloaded` and `npm install --save flickity-fullscreen`. You can check their docs for the other packages (or it might be quicker to just browser their [repo]( https://github.com/metafizzy) for anything prefaced with flickity.
3. The flickity file in your js/src should look like this
```js
import Flickity from 'flickity'; //this makes the function available you call new Flickity() somewhere else.
// These extensions you don't need to name, since it only needs to be available here.
import 'flickity-imagesloaded`;
import 'flickity-fullscreen`;
```

`flickity.pkgd.js` is just a preprocessed file that includes pretty much every single addon - which means its bloated if youre only using the two functions above.

If you cant figure out which packages youre missing (and thus youre still getting errors), dont want to post in flickity's github, you could still use npm to grab the `flickity.pkgd.js`, and have wp-rig bundle it automatically.

To do that just replace the entire javascript file with `import Flickity from '../../node_modules/flickity/dist/flickity.pkgd.js;` ('../' says go up a folder, so if you're using a nonstandard `assets/src` path, you might need to change that to get to the `node_modules` folder), and then whenever you update your npm dependencies, your theme will automatically be using the latest version.

**Comment by venuscrush** [comment]
Thank you for the detailed response. Unfortunately when I use the `import `snippet in` flickity.js`, Iit's greayed out and I'm getting an error that states the following:

> > 1:1  error  Expected preceding "External dependencies" comment block @wordpress/dependency-group
>   1:8  error  'Flickity' is defined but never used    no-unused-vars

![Screen Shot 2019-09-14 at 9 13 41 AM](https://user-images.githubusercontent.com/38008836/64908563-1081e280-d6d0-11e9-9ea1-29030d5b4efb.png)

As a result, `flickity` and all of its files aren't loading.

I tried fixing the errors but it still doesn't work when I add the comment block. Even simply calling `flickity.pkgd.js`doesn't work. (the screenshot above is the content in my flickity.js file).

**Comment by justlevine** [comment]
>Unfortunately when I use the import snippet in flickity.js, It's grayed out and I'm getting an error that states the following:
If the file is failing to compile, and not just passing an error to the log, then thats an issue with your linter.

Add the docblock (which you did in your second image) to resolve that error, and you can resolve the second error by adding a no-unused-vars comment. See the screenshot for how to use vscode to autofix this (and other issues like this) in the future.

![Annotation 2019-09-14 162707](https://user-images.githubusercontent.com/29322304/64908824-5a3cee00-d70d-11e9-8e11-fa0f49da6578.png)

>Even simply calling flickity.pkgd.jsdoesn't work. 

I guess I wasn't clear about the whole `import ... from 'node_modules'`:

- Import statements are _relative to the file they're called from_. and the `node_modules` folder is located in your base theme path.  
 - to go up a folder, you need to use `../`
- so if your js file is `assets/js/src/my-file.js`, to get to node_modules, you need to change your import path to `../../../node_modules/flickity/dist/flickity.pkgd.js`

**Comment by venuscrush** [comment]
- My full path for` flickity.pkgd.js` in wprig is `/wprig/node_modules/flickity/dist/flickity.pkgd.js`

Your explanation makes sense, but it's still not loading on my website (I still see my flikity.js file in `view source`).

For the screenshot below, I used quick fix. Is there a setting I should be adding to the 'Scripts' component? 

P.S. Everything works when I just copy/paste the flickity.pkgd.js straight from the Flikity website.

![Screen Shot 2019-09-14 at 10 01 48 AM](https://user-images.githubusercontent.com/38008836/64909238-6efe8f00-d6d7-11e9-8700-730dda9f6c4f.png)

**Comment by justlevine** [comment]
>  My full path for flickity.pkgd.js in wprig is /wprig/node_modules/flickity/dist/flickity.pkgd.js

But what's the path of your custom file?

**Comment by venuscrush** [comment]
My path is 
- /wprig/assets/js/src/flickity.js

**Comment by justlevine** [comment]
In that case: replace that import with this `import Flickity from '../../../node_modules/flickity/dist/flickity.pkgd';`

(you need 3 `../` because youre moving up 3 levels to get to `wprig` (where node-modules), and you leave off .js).

If you're using the the pkgd file instead of from `flickity`, then you dont need the other import statements for fullscreen etc.

Regardless of which, your `wp_register_script` should be the path to the compiled version of the file you created aka assets/js/flickity.min.js;

After these changes, remember to stop and rerun `npm run dev` (or `npm run bundle` if your testing the prod version of the them).

**Comment by venuscrush** [comment]
I've done the above and it's finally allowing me to go to the source file for `flickity.pkgd` (when cmd+ click the file path). Now, I _know_ that everything is linked correctly, however, the carousel functionality is still not loading on the website. 

Again, when I just copy/paste the raw code in `flickity.js` it works so there must be something going on with the importing unless it's something else?

Here's the code I placed in the file:
`/**
 * Internal dependencies
 */
// eslint-disable-next-line no-unused-vars
import Flickity from '../../../node_modules/flickity/dist/flickity.pkgd.min';
`

I've even imported the flickity.css and that has worked successfully:
`@import "../../../node_modules/flickity/dist/flickity.min.css";`

Could there be a file conflict going on? I'm stumped.

**Comment by justlevine** [comment]
Are you getting any errors in your `console.log`?
What happens if you type into the chrome dev console `typeof Flickity` (it should say function)?
How are you initializing flickity - via your html/PHP or using `new Flickity()` in is?

Sadly at this point I don't think I can help without having actual access to your code (if you want to share a link to the GitHub repo, by all means). You might want to consider posting an issue on the flickity GitHub repo.

**Comment by venuscrush** [comment]
Good call—it's not loading in the browser & certainly, feel free to inspect my repo: https://github.com/venuscrush/wprig-2/invitations
![Screen Shot 2019-09-15 at 12 05 47 PM](https://user-images.githubusercontent.com/38008836/64925213-2fa96e80-d7bb-11e9-8fad-0c6ac975c42d.png)

I've also been having issues loading fontawesome webfonts, if you have time of course, it would be great if you can look that over as well.

Thank you for support, hopefully this can be solved once and for all!

**Comment by justlevine** [comment]
I'm an idiot. 

I completely forgot that wp-rig doesnt include a bundler by default.

`require()` (which is what `import` transpiles into) is not supported by browsers by default, so you need a bundler such as webpack/requires/roll-up in your build process. 

I'm happy to share my scripts.js file which replaces the default wp-rig setup with webpack, but if all this sounds like gibberish to you you're probably better off manually including/enqueuing the pkgd.js.version the way you've been getting it to work. 

Sorry for wasting your time. Last time I offer unsolicited, offtopic advice - I swear!

**Comment by venuscrush** [comment]
Aha! That explains everything. I think I'll just stick to copy/paste for now but I'll definitely get into using webpack soon.

Before I close this issue, do you mind letting me know how I can call in the script for `flikity.js` to only load on front-page.php? I quoted you below, but you mentioned using wp_register_script()—based on my files, what would the exact code look like? I have an idea, but might as well get it from the pro so I can use it moving forward!


> Assuming this is the entire file, you're missing the `get_slug` function at the top of your class that lets wp-rig know to use the file.
> 
> ```
> /**
>  * Gets the unique identifier for the theme component.
>  *
>  * @return string Component slug.
>  */
> public function get_slug() : string {
>     return 'scripts';
> }
> ```
> 
> Add that, and then make sure that `inc/Theme.php`' includes your your new component:
> 
> ```
> protected function get_default_components() : array {
>     $components = [
>         ...
>         new Scripts\Component(),
>         ...
>     ];
> }
> ```
> 
> (PS: totally unrelated, but:
> 
> * you might want to consider using `wp_register_script()` for `flickity`, and then calling `wp_enqueue_script` before your carousel, instead of loading the js on every single page,
> * Also remember that half the point of using a starter theme with a build step is so you don't need to manage dependencies by manually dragging and replacing new vendor files. You might want to think about installing flickity as an npm dependency, and then creating a `flickity.js` file in your `js/src` that just calls `import Flickity from 'flickity;` (keeping in mind that pkgd.js contains all the different npm packages, so if youre using features like `flickity-imagesloaded` or `flickity-bg-lazyload` you need to import them in the same file as well).
>   This way, it's set it and forget it, and you dont need to keep manually replacing vendor files.
>   )

**Comment by justlevine** [comment]
>Before I close this issue, do you mind letting me know how I can call in the script for flikity.js to only load on front-page.php? I quoted you below, but you mentioned using wp_register_script() and then wp_enqueue_script in the actual file (in this case, front-page.php)—based on my files, what would the exact code look like?

(Based on your repo) Just throw `wp_enqueue_script('wp-rig-flickity-script');` at the top of `front-page.php` below the namespace declaration.

Although ps, remember to change your Scripts/Component() to `wp_register_script`, or itl still be enqueued on all pages.

If, in the future, youre using flickity in multiple places on your theme (e.g. a widget or shortcode, or who knows), you can throw it on top of your template part and then the script will be enqueued every place you use that partial automatically. #DRY

Good luck!

**Comment by venuscrush** [comment]
> > Before I close this issue, do you mind letting me know how I can call in the script for flikity.js to only load on front-page.php? I quoted you below, but you mentioned using wp_register_script() and then wp_enqueue_script in the actual file (in this case, front-page.php)—based on my files, what would the exact code look like?
> 
> (Based on your repo) Just throw `wp_enqueue_script('wp-rig-flickity-script');` at the top of `front-page.php` below the namespace declaration.
> 
> Although ps, remember to change your Scripts/Component() to `wp_register_script`, or itl still be enqueued on all pages.
> 
> If, in the future, youre using flickity in multiple places on your theme (e.g. a widget or shortcode, or who knows), you can throw it on top of your template part and then the script will be enqueued every place you use that partial automatically. #DRY
> 
> Good luck!

**(posting this in case anyone has a similar question)** 

Appreciate the fast follow-up on this! 

I actually modified the script from the accessibility component and wrapped it in a conditional tag so that it only loads on front_page.php (as per @mor10 video). This method seems to work great and I like that it keeps everything in a single file.
