### ISSUE TITLE
What's the Best Way to Register a New Widget Area?

### ISSUE THREAD

**Issue by digisavvy** [wprig/wprig#603]
## Issue Overview
What is the best way to add a new widget area with Rig? I see there is a file that registers the primary sidebar. Instead of registering a new one myself, I just wanted to see if there's a rig best practice there so I don't work too hard there.

**Comment by justlevine** [comment]
Pretty sure the easiest way _is_ to add a new `register_sidebar()` to `action_register_sidebars()` ([here](https://github.com/wprig/wprig/blob/master/inc/Sidebars/Component.php#L66)).

Just remember the other functions in that file are set up solely for the primary sidebar, so you might want to change the / add your own functions (esp. `filter_body_classes()` - the others IMO are just named shortcuts for already simple built-in WP functions but 🤷‍♂️)

**Comment by digisavvy** [comment]
Thanks @justlevine - that clarifies things for me. =)
