### ISSUE TITLE
PNG files cause failures in node_modules/zopflipng-bin/vendor/zopflipng

### ISSUE THREAD

**Issue by ev3rywh3re** [wprig/wprig#61]
## Issue Overview
Adding specific PNG files to /dev/images causes errors with node_modules/zopflipng-bin/vendor/zopflipng

## Describe your environment
Testing server is local hosted vagrant.
Local node environment is MacOS 10.13.6 with node v10.7.0 with npm 3.10.5. Installed with homebrew.

## Steps to Reproduce

1. Setup wprig either current branch or v1.1, run 'npm install' and 'npm run build'
2. Add the attached PNG file to /dev/images 
3. Boom! Error output, file is not copied.

<pre>
[09:54:58] Error in plugin "gulp-image"
Message:
Command failed: /Users/webmanager/Desktop/nicholls-vagrant/sites/www/wp-content/themes/nicholls_2018_core/node_modules/zopflipng-bin/vendor/zopflipng -
y --lossy_8bit --lossy_transparent /private/var/folders/3b/_s0mjl790md6vqdsdtl4c5k80000gq/T/78574744-9595-4b4f-9e77-c066f23ac42f /private/var/folders/3b/_s
0mjl790md6vqdsdtl4c5k80000gq/T/398ee317-3c1e-4e82-8c00-c9543ab42a0c

Optimizing /private/var/folders/3b/_s0mjl790md6vqdsdtl4c5k80000gq/T/78574744-9595-4b4f-9e77-c066f23ac42f
Encoding error 82: color conversion to palette requested while a color isn't in palette

Decoding error 82: color conversion to palette requested while a color isn't in palette
There was an error

Details:
code: 1
killed: false
stdout: Optimizing /private/var/folders/3b/_s0mjl790md6vqdsdtl4c5k80000gq/T/78574744-9595-4b4f-9e77-c066f23ac42f
Encoding error 82: color conversion to palette requested while a color isn't in palette
Decoding error 82: color conversion to palette requested while a color isn't in palette
There was an error

stderr:
failed: true
signal: null
cmd: /Users/webmanager/Desktop/nicholls-vagrant/sites/www/wp-content/themes/nicholls_2018_core/node_modules/zopflipng-bin/vendor/zopflipng -y --lossy_8
bit --lossy_transparent /private/var/folders/3b/_s0mjl790md6vqdsdtl4c5k80000gq/T/78574744-9595-4b4f-9e77-c066f23ac42f /private/var/folders/3b/_s0mjl790md6v
qdsdtl4c5k80000gq/T/398ee317-3c1e-4e82-8c00-c9543ab42a0c
timedOut: false
</pre>

## Expected Behavior

Expected to optimize and move files to /images

## Current Behavior

Error thrown and files not copied.

## Possible Solution

So far solution is to find another image. I've made PNG images with Photoshop and Gimp and the file continues to have problems. So far I've seen this with 3 separate PNG files.

## Little Question mark PNG that fails is below... its small with a transparent background.

[question.png](https://user-images.githubusercontent.com/871162/42954456-62c33218-8b42-11e8-9d41-d98dfcc33e3a.png)
![question](https://user-images.githubusercontent.com/871162/42954456-62c33218-8b42-11e8-9d41-d98dfcc33e3a.png)

**Comment by mor10** [comment]
Any insights on this @ataylorme?

**Comment by ataylorme** [comment]
@mor10 I left a comment on #63

**Comment by ev3rywh3re** [comment]
Fresh 1.1v Works fine and file with original issue processes fine. Closing.

**Comment by mehmoodak** [comment]
The actual cause of this is `zopflipng` dependency in npm. For me initialising the image with following configuration work fine in which I disable `zopflipng` and enable `optipng`.
```
image({
      pngquant: true,
      optipng: true,
      zopflipng: false,
      jpegRecompress: false,
      mozjpeg: true,
      guetzli: false,
      gifsicle: true,
      svgo: true,
      concurrent: 10,
      quiet: false // defaults to false
    })
