### ISSUE TITLE
Filters and Callable Functions

### ISSUE THREAD

**Issue by digisavvy** [wprig/wprig#619]
## Issue Overview
I'm struggling with how to place a filter within a custom component. 
````
add_filter( 'pre_render_block', function( $pre_render, $block ) {
	if ( is_singular( ) && in_the_loop() && is_main_query() && 'core/cover' === $block['blockName'] ) {
		$pre_render = '';
	}
	return $pre_render;
}, 10, 2 );
````
I want this bit of code to be placed in my component file rather than functions.php (this block works fine from there). But I know the importance of keeping things organized. I'm struggling with the appropriate syntax here. If anyone has guidance that would be helpful.

**Comment by Horlaes** [comment]
Are you able to resolve this?

**Comment by Horlaes** [comment]
Were you able to resolve this?

**Comment by digisavvy** [comment]
Yes, I did!
I set the filter within the initialize() function - I looked at other components for guidance. Then I had to create a method/function for the conditional. Below is how the code sits in that component.
```
	public function initialize() {
		add_filter( 'pre_render_block', array( $this, 'dgs_remove_block' ), 10, 2 );
	}
```

```
	public function dgs_remove_block( $pre_render, $block ) {
		if ( ! is_archive() && in_the_loop() && is_main_query() && 'acf/hh-hero-block' === $block['blockName'] ) {
			$pre_render = '';
		}
		return $pre_render;
	}
```
