### ISSUE TITLE
Helpful documentation for Virtualbox/Vagrant using BrowserSync

### ISSUE THREAD

**Issue by ev3rywh3re** [wprig/wprig#62]
## Issue Overview

Just some possible documentation help. This only works on my MacOS environment, but may be useful elsewhere. I know advanced users probably know about port forwarding already, but this single line helped BrowserSync work on my Vagrant setup. 

`# trying to fix browsersync`
 `config.vm.network :forwarded_port, guest: 80, host: 3000, auto_correct: true`

## Describe your environment

Based on my really low-fi Vagrant setup at: https://github.com/ev3rywh3re/vagrant-wp-simple
MacOS 10.13.6
VirtualBox 5.2.14
Vagrant 2.1.2

## Steps to Reproduce

1. Setup Vagrant/VirtualBox (advanced topic anyway...)
2. Setup wprig.
3. Run 'npm install' and 'npm run build'
4. Browsers won't work on localhost and don't reload while working on wprig.

## Expected Behavior

Browsers reload as wprig is developed

## Current Behavior

Depending on your system and your Vagrant setup, BrowserSync probably won't work.

## Possible Solution

Adding the following line to my Vagrantfile worked like a charm. With BrowserSync working on http://localhost:8181 with the BrowserSync UI available at http://localhost:3001

`# trying to fix browsersync`
 `config.vm.network :forwarded_port, guest: 80, host: 3000, auto_correct: true`

**Comment by mor10** [comment]
@ev3rywh3re Would you be willing to write up a little blurb that can go in the Wiki on this?

**Comment by ev3rywh3re** [comment]
Took me a little while to get my local debian/strech64 stuff running. Also the startling realization that Apple's Safari is horrible as a default browser since it likes to hold on to cached CSS. Got my brain wrapped around it now and my BrowserSync is working. Once get the proper apache configs on the Debian side looking proper, I'll see if I can write something up. 

I'm actually using:
`config.vm.network :forwarded_port, guest: 8181, host: 80, auto_correct: true`

Which may be more appropriate for WPRIG defaults.
