### ISSUE TITLE
What is the right way to work with Bootstrap in WPrig?

### ISSUE THREAD

**Issue by elobadi** [wprig/wprig#627]

**Comment by heathernew09** [comment]
I'm curious the best application for the Foundation grid framework, I'd assume it'd be very similar.

**Comment by M27Mangan** [comment]
Also for Tailwind, any hints how this works with V1 or V2?

**Comment by alexwcoleman** [comment]
Hi! Apologies for the delay - WP Rig is going through a minor restructuring.
This isn't an issue _per se_, so I'll be closing it out. However! One method you can use to get started is by creating a custom CSS "partial" file in the `assets/css/src` folder (partials start with an underscore) , then in `global.css` (if you want that available globally) you can import the file with `@import "_your-custom-partial-name.css";`. I know this isn't a full blown tutorial, but it's a bit to get you started.
