### ISSUE TITLE
npm_modules isn't being created

### ISSUE THREAD

**Issue by Breklin** [wprig/wprig#629]
I keep running into an issue on Mac OS Catalina where I run 'npm run rig-init' and it errs out. I run 'composer install' and composer installs without issue. I then run 'npm install' and it runs without issue. The result is that node_modules is not created withing the 'themes/wprig/' directory. 

This has happened on two separate machines. Both Macs running Catalina. Xcode is installed along with developer tools. Brew is installed. Latest version of node/npm. Brew updated. 

Any ideas? This is entirely frustrating because I'm super stoked to use this framework! 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by alexwcoleman** [comment]
is this issue still happening?

**Comment by Breklin** [comment]
Thanks for following up. It's been a while since I have tried. You can close this and I'll follow up again if I see it happening on any new builds.
