### ISSUE TITLE
phpcs not working properly

### ISSUE THREAD

**Issue by Dthompson1411** [wprig/wprig#632]
## Issue Overview
When phpcs is active on VS Code, I get the following warning on my index page.
Generic.WhiteSpace.DisallowTabIndent.TabsUsed
## Describe your environment
I downloaded VS Code on my Macbook Pro running 10.15.3 (Catalina) Installed homebrew, installed  Morton's recommended setup for VS Code.

## Steps to Reproduce

1. Load Homebrew
2. Load nodejs
3. Load composer
4. Load VS Code
5. Activate all plugins from the course Wordpress: Building Progressive Themes with WP Rig

## Expected Behavior
Composer, league/co/or-extractor, and squizlabs/php_codesniffer would load and behave normally.

## Current Behavior
index page displays Generic.WhigeSpace.DisallowTabIndent.TabsUsed alert on almost every line. (current file is the 02-02 folder)
## Possible Solution
None
## Screenshots / Video

![Screenshot 2020-02-29 12 21 34](https://user-images.githubusercontent.com/30248301/75600751-497f0980-5aee-11ea-8d27-8a5f4f019353.png)

I have spend 2 days searching for a work around to get this to work.  I found a rule to add, but I cannot find where to add the rule.  (I have since lost the reference LOL) Any ideas or recommendations to fix this issue would be appreciated.

**Comment by leanderlindahl** [comment]
I've been through this and it can be tricky. The messages seem to indicate that phpcs requires spaces instead of tabs, which as you noticed yourself is not the WordPress coding standard. You could try and make sure your phpcs standard is set to WordPress.

Also the project in your screenshot is not wprig, but example files from one of the chapters in the course. Try to install wprig in full and see if the problem persists.

**Comment by Dthompson1411** [comment]
Dear Leander,
Thank you for your answer.  It is right that WP-Rig wasn't loaded.  I was
taking Mortons course on WP Rig in the Become a Junior Wordpress Developer
class.  I am considering using WP-Rig (I currently use OceanWP and
Elementor Pro) but I am concerned that I cannot use Elementor once I create
my theme.  Can I still use a page builder once the theme is created?

Respectfully,
David Thompson

**Comment by leanderlindahl** [comment]
Hello  David, I don't really know how Elementor works with wp-rig, you could simply try it out by building a "finished" wp-rig theme with `npm run bundle` and then try it out with Elementor. 

As far as a I know a theme built with WP Rig works just like any other theme once you've built it. 

The "thing" with wp-rig is providing a good starting point and a workflow for coders when creating themes. The finished code is then "exported" to a theme that can be uploaded and installed in a WP Site. It's similar to when building React Apps and creating a "dist" of the finished app.

There could be other themes more suitable for building with Elementor. https://docs.elementor.com/article/78-themes

**Comment by alexwcoleman** [comment]
Since this isn't a WP Rig specific issue, I'm closing it out.
