### ISSUE TITLE
net::ERR_ABORTED 404 (Not Found). Cannot find css, js, images after a fresh install

### ISSUE THREAD

**Issue by JeradeC** [wprig/wprig#635]
## Issue Overview
I downloaded WP Rig and then actiavted in WordPress. Once activated I visited the site to just only seeing text but no styles were loaded. I inspected it in Chrome and it state cannot find files. Here's the error message:

GET http://wprig.local/wp-content/themes/wprig/assets/css/content.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
VM3823:52 GET http://wprig.local/wp-content/themes/wprig/assets/css/sidebar.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
VM3823:53 GET http://wprig.local/wp-content/themes/wprig/assets/css/widgets.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
(index):39 GET http://wprig.local/wp-content/themes/wprig/assets/css/global.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
(index):45 GET http://wprig.local/wp-content/themes/wprig/assets/js/navigation.min.js?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
(index):46 GET http://wprig.local/wp-content/themes/wprig/assets/js/lazyload.min.js?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
(index):1522 GET http://wprig.local/wp-content/themes/wprig/assets/css/sidebar.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
(index):51 GET http://wprig.local/wp-content/themes/wprig/assets/css/content.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
(index):1523 GET http://wprig.local/wp-content/themes/wprig/assets/css/widgets.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
(index):45 GET http://wprig.local/wp-content/themes/wprig/assets/js/navigation.min.js?ver=2.0.1 404 (Not Found)
(index):46 GET http://wprig.local/wp-content/themes/wprig/assets/js/lazyload.min.js?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
6A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
(index):1522 GET http://wprig.local/wp-content/themes/wprig/assets/css/sidebar.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)
(index):1523 GET http://wprig.local/wp-content/themes/wprig/assets/css/widgets.min.css?ver=2.0.1 net::ERR_ABORTED 404 (Not Found)

I check my folders to see if these files exist it and it doesn't. Only non-minimized exists it under "<name>/src folder

Can someone help me? Thanks.

**Comment by alexwcoleman** [comment]
Did you run the commands to generate the theme? I suspect this is the issue. Please look at the fourth point of [How To Install WP Rig](https://github.com/wprig/wprig#how-to-install-wp-rig). In order to generate those files you have to run `npm run dev` (during development), or for a production-ready theme use `npm run build`.
I'm going to close this as I believe this will solve your issue. Please comment again if this doesn't solve your issue.
