### ISSUE TITLE
The learning videos are not available (for free) anymore?

### ISSUE THREAD

**Issue by niklasp** [wprig/wprig#638]

**Comment by MagicRico** [comment]
If you have a LinkedIn account, you log in and then video will appear free

**Comment by goldtreefrog** [comment]
You can see the course at Morten Rand-Hendriksen's [WP Rig site](https://wprig.mor10.com/learn/).

Also, I don't know how common this is, but my library in Sonoma County, California, has some agreement with Lynda whereby library members can get into Lynda for free. Check with your local library. Hopefully, you will be pleasantly surprised.

**Comment by alexwcoleman** [comment]
as above you can [find the courses on Morten's site here](https://wprig.mor10.com/course/wprig_en/). Closing this out.
