### ISSUE TITLE
What is the path to assets > images?

### ISSUE THREAD

**Issue by Spleeding1** [wprig/wprig#643]
## Issue Overview

I am trying to view an image in the `assets > images` folder, but I can't seem to be able to make it work. It might be an "I don't know what I'm doing" issue, but frustrating none the less.

```html
<div><!-- Facebook Link -->
    <?php
    $src = get_template_directory();
    $src .= "/assets/images/my_image.png";
    echo "<img src=\"{$src}\" width\"50\" alt=\"facebook icon\"></img>";
    ?>
</div>
```
The `alt` displays, and the path looks correct in the inspector but no image. I am using macOS latest version, with Local. I tried moving the image to different places and using and absolute path, but it still didn't work.

Sorry if this is the wrong place to ask this question, I wasn't sure where to go to get help.

Thanks.

**Comment by mpbrunelle** [comment]
Try using: get_template_directory_uri()

You can find the difference between these two functions in this article : https://letslearnnow.net/get_template_directory-vs-get_template_directory_uri/

**Comment by Spleeding1** [comment]
It's a winner! Thanks.
