### ISSUE TITLE
Correct file path for background images

### ISSUE THREAD

**Issue by mark60480** [wprig/wprig#647]
## Issue Overview
Could someone please tell me the correct file path for a background image? I'm used to this css in the style sheet:
background-image: url(images/bgimage.jpg) - but this does not work. I tried adding "assets" and "../", but nothing is working.

**Comment by mpbrunelle** [comment]
If your css file is located in the assets/css/ folder and your image is in the assets/images folder, the path url(../images/bgimage.jpg) should work.

**Comment by mark60480** [comment]
Marie, first of all, thanks so much for your reply!! I was beginning to think that no one monitored this. However, the file page you mentioned does not work. See screenshots attached. 
![firefox_SBP](https://user-images.githubusercontent.com/23484360/88436743-8ebc1480-cdca-11ea-86c4-e384faf2f43b.jpg)
![vsCode_SBP](https://user-images.githubusercontent.com/23484360/88436757-97144f80-cdca-11ea-856e-cf18a3eaa034.jpg)

Do you know of anyone who can help me troubleshoot this? I am willing to pay an hourly fee.

**Comment by mpbrunelle** [comment]
I'm no expert, but if you can send me a link to the page, I'd be happy to try to help.

**Comment by mark60480** [comment]
Marie, thanks again for your reply. Unfortunately, the site is only accessible locally on my computer. However, you have certainly pointed me the right direction. I'm going to start from scratch and see if I can track down the issue. 
There are a few parts of MRH tutorial that are not as he shows them - probably due to updates. To that end, I would like to be certain that I'm starting correctly. I'm going to https://github.com/wprig/wprig and (different from tutorial) clicking on the download Code button. From there I choose "download zip" and when I unzip that I get a folder called "wprig-master". I then copy that folder into my wp-content/themes folder. The unzipped folder in the tutorial is called "wprig". Should I be changing the name of the "wprig-master" folder to "wprig" - or just leave it as is?

**Comment by mpbrunelle** [comment]
You can leave it as is or change it to wprig-[yourThemeName]. 

Actually, the installation process is well described on the github page: https://github.com/wprig/wprig#how-to-install-wp-rig.

Good luck!

**Comment by mark60480** [comment]
This turned out to be corrupted image files.
