### ISSUE TITLE
Fail run "npm run dev/build"

### ISSUE THREAD

**Issue by wolfylicious** [wprig/wprig#651]
## Issue Overview
Getting an error when attempting to use "npm run dev/build" in the 2.0.1 branch.

Error: 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v14.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle wprig@2.0.1~prebuild: wprig@2.0.1
6 info lifecycle wprig@2.0.1~build: wprig@2.0.1
7 verbose lifecycle wprig@2.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle wprig@2.0.1~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\wp-rig-starter\wp-content\themes\wprig-thewolf\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Users\Wolfylicious\AppData\Local\Microsoft\WindowsApps;C:\Users\Wolfylicious\AppData\Local\atom\bin;C:\Users\Wolfylicious\AppData\Local\Microsoft\WindowsApps;C:\Users\Wolfylicious\AppData\Roaming\npm;C:\Users\Wolfylicious\AppData\Roaming\Composer\vendor\bin
9 verbose lifecycle wprig@2.0.1~build: CWD: C:\xampp\htdocs\wp-rig-starter\wp-content\themes\wprig-thewolf
10 silly lifecycle wprig@2.0.1~build: Args: [ '/d /s /c', 'gulp buildDev' ]
11 silly lifecycle wprig@2.0.1~build: Returned: code: 1  signal: null
12 info lifecycle wprig@2.0.1~build: Failed to exec build script
13 verbose stack Error: wprig@2.0.1 build: `gulp buildDev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid wprig@2.0.1
15 verbose cwd C:\xampp\htdocs\wp-rig-starter\wp-content\themes\wprig-thewolf
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.7.0
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 1
22 error wprig@2.0.1 build: `gulp buildDev`
22 error Exit status 1
23 error Failed at the wprig@2.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Describe your environment
Atom/CMD
Win 10
Node.js v.14.7.0
npm v.6.14.7
composer v1.10.10
Gulp CLI 2.3.0
Gulp Local v.4.0.2

## Steps to Reproduce
I was interested to switch from Bones to WPRig and test the 2.0.1 branch to see what it was like. Clean install, downloaded fresh today. Ran 'npm install' with no significant errors. Run "npm run rig-init" with no problems. Run "npm run dev/build" and i am stopped in the following error.

## Expected Behavior
The npm run dev/build command to work.

## Possible Solution
See error above.

**Comment by wolfylicious** [comment]
Also had to mention that i used yarn

**Comment by alexwcoleman** [comment]
apologies for the delayed reply. There's been a bit of restructuring and this project is now getting back on its feet.
Did you run `npm run dev/build` exactly like that? If so, you should be running `npm run dev` OR `npm run build`. They both do similar, but different tasks. The differences are outlined at item #4 in [How To Install WP Rig](https://github.com/wprig/wprig#how-to-install-wp-rig).

**Comment by wolfylicious** [comment]
@alexwcoleman jokes on you xD. Tried both "npm run dev" as well with "npm run build". Downgrading to 2.0.0 fixed the problem for me without further configurations. 

TL,DR - problem is affecting 2.0.1 only (time on the post was opened). 2.0.0 works fine.

**Comment by alexwcoleman** [comment]
ah, you mentioned you ran `npm run dev/build` so there's no way for me to know otherwise, which made that a starting point. However, your version of Node seems to be a RC (perhaps I'm wrong though) - which I honestly can't say if that's really a suspect at this time. I can't currently recreate your environment (Mac for me right now), so I'll see if there's anyone else that can.
