### ISSUE TITLE
Any plan for soon update?

### ISSUE THREAD

**Issue by abazeed** [wprig/wprig#654]
Hi there,

I'm visiting your repository from time to time hoping to see any updates. It's more than one year since your last update, and many changes happened during that on WordPress, and I'm very excited to go further with your great theme and adopt more features and updates.

Best Regards,

**Comment by madebyvale** [comment]
> @abazeed - the project has been abandoned unless other community members want to maintain it. So far that answer has been "no."

Blimey is this so @mor10 I hope not!

**Comment by xeiter** [comment]
@drozumek Do you have any update?

**Comment by robruiz** [comment]
This project is not being abandoned. We are in the process of transitioning to a new team of maintainers. Stay tuned for more info.

**Comment by madebyvale** [comment]
Would be good if updating 'package.json' and 'package-lock.json' are prioritised.

**Comment by robruiz** [comment]
Noted

**Comment by alexwcoleman** [comment]
closing this out as this is being worked on.
