### ISSUE TITLE
config.local.json file missing or just not created by default?

### ISSUE THREAD

**Issue by dthenley** [wprig/wprig#662]
While setting up to use WPRig i get to 3.c in How to install WP Rig where it says "Place local-only theme settings in `./config/config.local.json`, e.g. potentially sensitive info like the path to your BrowserSync certificate."

I am not seeing the `./config/config.local.json` in the default file, so am i supposed to create a new file or is it just missing?

**Comment by alexwcoleman** [comment]
Create the file and place your settings in there.
