### ISSUE TITLE
NPM Errors

### ISSUE THREAD

**Issue by JackRie** [wprig/wprig#663]
## Issue Overview
I keep getting errors when I run npm install or npm run rig-init. I made sure composer was installed globally and tried downloading a new copy of wprig and setting up a new environment for it. I get the same errors.

--I am new to this so just looking for some help with what I am experiencing.

## Describe your environment
On Mac
Local by FlyWheel
VS Code
Composer version 1.10.15 2020-10-13 15:59:09
PHP 7.3.11 (cli) (built: Jun  5 2020 23:50:40) ( NTS )

## Steps to Reproduce

1. Download WP rig in zip file, unpack it 
2. Create new setup in local by flywheel
3. past wp rig folder into themes folder of setup
4. Open in VScode, change config settings
5. Open an integrated terminal in VS code run npm run rig-init

## Expected Behavior
new node_modules and vendor folders in project
## Current Behavior
npm ERR!

## Screenshots / Video

![Screen Shot 2020-10-17 at 4 45 46 PM](https://user-images.githubusercontent.com/65911379/96353229-38443680-1098-11eb-99d7-eebbf9597be4.png)

**Comment by madebyvale** [comment]
I have been getting similar issues. There are re-assurances that WPRig will be updated and is not abandoned. I am looking forward to future updates and these error messages being resolved. I have paid for the WPrig course on Linkedin Learning so it will be good to be able to continue with this course once WPRig has been updated.

**Comment by robruiz** [comment]
WP Rig is open source. We are always actively looking for contributors.
Feel free to let us know if you would like to help us maintain it.

**Comment by JackRie** [comment]
Hi @madebyvale It took me a while to figure out what was going on with my errors, but eventually, I was able to solve this issue by doing a few things:

1.) Uninstalling and reinstalling Xcode
2.) Deleting package-lock.json & package.json and doing another npm install
3.) Installing composer again according to the instructions on the LinkedIn Learning video

I hope this helps you. It took me a few days to research everything I needed to resolve this. Good luck!

**Comment by madebyvale** [comment]
Hi @JackRie, many thanks for the info and providing the benefit of your exhaustive research, this is a great help.

**Comment by madebyvale** [comment]
Hi @robruiz, my skills are primarily in Design and Art Direction which is why I enrolled on the Linkedin Learning course for WPRig. An as much as I would like to contribute I am unlikely to be able to make any significant contributions to the code.
If I can think of anyone who would be able to contribute I will surely point them this way.

**Comment by alexwcoleman** [comment]
Hi @madebyvale. I just went through the install process that you listed and I had no major errors. I _did_ have some similar errors like the ones in the upper portion the screenshot you took - but those weren't fatal.

In order to negate some low hanging fruit:

1. what version of NPM do you have `npm -v`
2. what version of Composer do you have `composer -V`

**Comment by madebyvale** [comment]
Hi, @alexwcoleman thanks very much for your investigation as above.
I guess it's okay to get some errors as long as they are not fatal - thanks this is good to know.
Regarding the hanging fruit, the versions currently installed are:

npm -v
6.14.6

composer -V
version 1.10.10

gulp -v
CLI version: 2.3.0
Local version: 4.0.2

I will go ahead and make a new install.
Just to say, your interest in maintaining the repo is hugely appreciated.
