### ISSUE TITLE
Composer package incompatible with Composer 2.x

### ISSUE THREAD

**Issue by jacklowrie** [wprig/wprig#665]
## Issue Overview

The version of `phpcodesniffer-composer-installer` specified in `composer.json` isn't compatible with composer 2.0. This results in `composer install` failing if using composer 2.0. Bumping that package to `"^0.7.0"` fixes it, which we found out needs to be done manually in a linked issue.

We noticed this on a project that uses github actions to bundle our theme for staging and prod environments (it looks like all GitHub-hosted runners use composer 2 now).

## Describe your environment

GitHub-hosted Runner with Ubuntu 18.04 [ runs-on: ubuntu-latest](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md)
| Tool     | Version                     |
| -------- | --------------------------- |
| PHP      | 7.1.33 7.2.34 7.3.23 7.4.11 |
| Composer | 2.0.2                       |
| PHPUnit    | 7.5.20                      |
| Node | 12.19.0 |
| Npm |  6.14.8  |

## Steps to Reproduce

1. run composer install with composer v2

## Expected Behavior

Composer install completes successfully.

## Current Behavior

composer errors out:

```
Error: Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer is locked to version v0.4.4 and an update of this package was not requested.
    - dealerdirect/phpcodesniffer-composer-installer v0.4.4 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer is locked to version v0.4.4 and an update of this package was not requested.
    - dealerdirect/phpcodesniffer-composer-installer v0.4.4 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
Error: Process completed with exit code 2.
```

## Possible Solution

We were able to fix it by bumping `phpcodesniffer-composer-installer` to `"^0.7.0"`, which according to the linked issue is compatible with both composer v1 and v2.

## Related Issues and/or PRs

https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/119#issuecomment-716625149
>Composer treats minors below 1.0 as majors, so you need to explicitly upgrade your version constraints to allow for version 0.7.x of this plugin. Version 0.7.0 was released last June and is fully ready for Composer 2.0, while also still supporting Composer 1.0.

**Comment by eclectic-coding** [comment]
I ran into the same issue. I agree that `composer.json` needs to be updated for the newer more compatible `phpcodesniffer-composer-installer: 0.7.x`

I will be glad to open a PR if need be.

**Comment by robruiz** [comment]
We are aware of this issue. I'm hoping to push out a new version that fixes
this in the next week or two. Thank you.

**Comment by eclectic-coding** [comment]
@robruiz Sounds great. 
BTW. First time trying out WPRig, and I have to say the most full featured starter I have ever seen.
