### ISSUE TITLE
npm run rig-init issues

### ISSUE THREAD

**Issue by maplesyrupCA** [wprig/wprig#666]
## Issue Overview
Hi everyone.  I'm doing the course Building Progressive Themes with WP Rig and am unable to get "npm run rig-init" to install properly on localhost.  Lots of errors including incompatibility with Composer 2.   

## Describe your environment
NPM 6.14.6
Composer 2.0.4
Local 5.9.0

Visual Studio Code 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

## Steps to Reproduce
1.   Tried reinstalling WP RIG, Wordpress, VS Studio, Local
2.   Tried reinstall WP RIG and Wordpress on MAMP

## Screenshots / Video

<img width="1116" alt="Screen Shot 2020-11-01 at 8 09 11 PM" src="https://user-images.githubusercontent.com/73809301/97829263-63c14680-1c7e-11eb-9c6b-71687b5622d6.png">
<img width="1644" alt="Screen Shot 2020-11-01 at 8 09 46 PM" src="https://user-images.githubusercontent.com/73809301/97829272-6cb21800-1c7e-11eb-8ae5-62af5a666783.png">
<img width="1646" alt="Screen Shot 2020-11-01 at 8 10 01 PM" src="https://user-images.githubusercontent.com/73809301/97829284-72a7f900-1c7e-11eb-9d44-7c4d5644f85d.png">

## Related Issues and/or PRs

Running npm run dev produces an error message of: Message:
    Execution of Code Sniffer Failed
Details:
    stdout: ERROR: Referenced sniff "WordPress" does not exist
Run "phpcs --help" for usage information

**Comment by joeyqlim** [comment]
Downgrading to Composer v1 worked for me:
`composer self-update v--1`


As for `gyp ERR! stack Error: `make` failed with exit code: 2`, the following steps worked for me:
`rm -rf package-lock.json`
`rm -rf node_modules`
`npm install`

**Comment by jacklowrie** [comment]
If you need to use composer v2, you can also update `phpcodesniffer-composer-installer' to `^0.7.0` - see #665. Bumping that package got us through the install processes, though we do still see the outdated package warnings

**Comment by maplesyrupCA** [comment]
Thank you so much.  I can run npm run dev now.  Thank you.

**Comment by jacklowrie** [comment]
closed by #673
