### ISSUE TITLE
npm err missing script

### ISSUE THREAD

**Issue by maplesyrupCA** [wprig/wprig#668]
## Issue Overview

When I try to run npm run rig-init or npm run dev it shows npm ERR! missing script: dev or npm ERR! missing script: rig-init 
It had previously worked 7 days ago.  

## Describe your environment

NPM 6.14.6
Node 12.18.3
Composer 1.10.17

Version: 1.47.3
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
## Steps to Reproduce

1. Reinstall a fresh copy of WPRIG following the instructions on the LinkedIn Learning course 
2.
3.
4.

## Screenshots / Video

<img width="1205" alt="Screen Shot 2020-11-11 at 8 00 01 PM" src="https://user-images.githubusercontent.com/73809301/98894254-40a24e00-2459-11eb-9217-7e699480c9a7.png">
<img width="1057" alt="Screen Shot 2020-11-11 at 8 06 31 PM" src="https://user-images.githubusercontent.com/73809301/98894329-6deefc00-2459-11eb-9937-b5c753ce1f5e.png">

**Comment by maplesyrupCA** [comment]
I'm not sure if this is the correct way of doing this, but I went to to the package.json file, clicked on Debug, and from here I can successfully  run dev and rig-init without the missing script error message.

<img width="1040" alt="Screen Shot 2020-11-14 at 9 33 34 PM" src="https://user-images.githubusercontent.com/73809301/99177798-a8f36880-26c1-11eb-90a7-08250b6ec2bd.png">

**Comment by maplesyrupCA** [comment]
So I think I finally found the solution.  I re-opened VS Code to point to the wprig folder inside WP-Themes and all the terminal scripts ran correctly without the missing script error message.  I had previously opened the project from the root folder.

**Comment by robruiz** [comment]
Looks like you found the solution, let me know if there is still actually an issue here. Otherwise, I'm going to close this one.
