### ISSUE TITLE
Default Gutenberg Gallery always displays 1 column of images

### ISSUE THREAD

**Issue by gianalvarez-cws** [wprig/wprig#670]
## Issue Overview
The default Gutenberg Gallery always displays images in one column. Instead of showing the images in a grid based on the amount of columns, each image in the gallery is always displayed in a new row. The columns are not being honored. 

## Describe your environment
WordPress 5.5.3 and wprig 2.0.1. (I'm using Local by Flywheel for local development) 

## Steps to Reproduce
1. Create a page.
2. Add a gallery to the content of the page.
3. Set the columns to 3 (or any value > 1)
4. View the preview or go to the page after publishing.

## Expected Behavior
I would expect wprig default styling to display the columns in a grid that honors the columns specified on the block.

## Current Behavior
Only one column is displayed
## Possible Solution
Adding .blocks-gallery-grid in the _.blocks.css gallery styles that handle grid display and grid-template columns seems to fix the problem. I suspect that WordPress changed the html structure of the gallery at some point and added an extra element wrapper.

PS: I'm new to using wprig. I apologize if this is a duplicate. I saw another ticket open regarding galleries but seemed unrelated based on the description.

**Comment by dp692001** [comment]
your workaround didn't seem to work for me. Removing all of the "Gallery Block - overrides core styles" does though.

**Comment by heathernew09** [comment]
I think @gianalvarez-cws is correct about the html structure changing. 
```
<figure class="wp-block-gallery">
     <ul class="blocks-gallery-grid"> ------> probably new
          <li class="blocks-gallery-item">
```       
 If you change references of .blocks-gallery-item to .blocks-gallery-grid in _blocks.css it detects the columns.

**Comment by heathernew09** [comment]
You'll also need to add the .blocks-gallery-grid class to .wp-block-gallery so it displays the grid properly in the editor. 

```
.wp-block-gallery .blocks-gallery-grid {
	display: grid;
	grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
	grid-gap: 0.5em;
}
```

**Comment by gianalvarez-cws** [comment]
@heathernew09  correct. Thanks for including the code snippet. That is exactly what I ended up doing in that file and corrected the problem.
