### ISSUE TITLE
Tips on adding Google fonts and home page layout break.

### ISSUE THREAD

**Issue by internetpirate11** [wprig/wprig#679]
## Issue Overview

I have two issues. One is google fonts adding and another is home page layout has horizontal scroll bar in Microsoft Edge and Chrome. Well I am trying to add google fonts but some how messed up. Don't know where to put the code as mentioned.
[As discussed in comments](https://github.com/wprig/wprig/issues/250#issuecomment-763653319)

## Describe your environment

1. Windows 10 64bits.
2. Atom Editor
3. Microsoft Edge (Version 87.0.664.75 (Official build) (64-bit)), Firefox (84.0.2 (64-bit)) and chrome ( Version 87.0.4280.141 (Official Build) (64-bit) )

## Steps to Reproduce

1. As home page loads in Microsoft Edge and Chrome horizontal scroll bar appears.

## Expected Behavior

1. Horizontal scroll bar should not appear.

## Current Behavior

1. Horizontal scroll bar is appearing in home page.

## Screenshots / Video

1. This link is for Layout breaking in home page. [Layout Break Img](https://ibb.co/R7S8XRf)
2. This link is for how to add google fonts I messed up. 1. [Code added in Component.php](https://ibb.co/0mPWgH4) 2. [Code added in _custom-properties.css file](https://ibb.co/LnnHbm3)

**Comment by dthenley** [comment]
Hey,

It looks like you changed the code in the wrong place. If you want to add "Chakra Petch" google font you want to add it to the google font array on line 361. You can either swap out Roboto or Crimson Text or put it after the Crimson Text Line after line 363.

You will want to change back line 371 to the default code.

**Comment by internetpirate11** [comment]
> 
> 
> Hey,
> 
> It looks like you changed the code in the wrong place. If you want to add "Chakra Petch" google font you want to add it to the google font array on line 361. You can either swap out Roboto or Crimson Text or put it after the Crimson Text Line after line 363.
> 
> You will want to change back line 371 to the default code.

well thank you @dthenley sir. It worked and I will try using bold font for it. I am wondering what will be the code for bold....

**Comment by dthenley** [comment]
> well thank you @dthenley sir. It worked and I will try using bold font for it. I am wondering what will be the code for bold....

Yay glad I can help. The font weight of the fonts are dictated in the google fonts array. If you want to use a certain font weight it will be included on that line in line 361 and then you would just implement it in the code.

**Comment by internetpirate11** [comment]
> > well thank you @dthenley sir. It worked and I will try using bold font for it. I am wondering what will be the code for bold....
> 
> Yay glad I can help. The font weight of the fonts are dictated in the google fonts array. If you want to use a certain font weight it will be included on that line in line 361 and then you would just implement it in the code.

well sir there is only font name and font weight ex: '300', '300i' for normal and italic respectively but what If I want to implement bold what will be the code ex: "300b" or "300s" ???

**Comment by dthenley** [comment]
The 300,300i are the font weights, those would be consider "light" font weights. If you would want to use the bold font weights you would add 700, 700i. That enables you to use the bold and bold italic font weight. You can find the different font weights on the google fonts page 
![image](https://user-images.githubusercontent.com/3503886/105509050-b7966700-5c92-11eb-8d59-773ffd3c3fe0.png)

**Comment by internetpirate11** [comment]
> 
> 
> The 300,300i are the font weights, those would be consider "light" font weights. If you would want to use the bold font weights you would add 700, 700i. That enables you to use the bold and bold italic font weight. You can find the different font weights on the google fonts page
> ![image](https://user-images.githubusercontent.com/3503886/105509050-b7966700-5c92-11eb-8d59-773ffd3c3fe0.png)

ok @dthenley  sir thank you for lovely explanation. appreciate it.

**Comment by dthenley** [comment]
Great, glad I can help
