### ISSUE TITLE
Webp format images are stripped out from bundle

### ISSUE THREAD

**Issue by ChrisBuck-Harness** [wprig/wprig#681]
I created a bundle with yarn run bundle. I can confirm that my theme's zipped folder doesn't contain any webp images. Where exactly is the script that checks file extensions during bundle?

**Comment by dthenley** [comment]
Hey Chris,

You if you have specific files/ folder that you want to include on export with bundle run you can add those to the export section in the wprig/config/config.default.json file after line 43.

```
 "export": {
    "compress": true,
    "generatePotFile": true,
    "filesToCopy": [
      "LICENSE",
      "readme.txt",
      "screenshot.png",
      "assets/css/vendor/**/*.css",
      "assets/js/vendor/**/*.js",
      "img/*.webp"
    ]
  }
```
Let me know if that helps.

**Comment by ChrisBuck-Harness** [comment]
Thanks, that fixed it. Appreciate it.
