### ISSUE TITLE
how to add an external javascript (i.e.for a slider)

### ISSUE THREAD

**Issue by ansikun2** [wprig/wprig#684]
## Issue Overview

I am trying to add an external javascript for master slider and managed to add the CSS scripts, but now I am struggling to add the javascript files. Can anyone point me to an example?

## Describe your environment

Wp-rip

## Steps to Reproduce

1. i added this a home.php template: <?php
wp_rig()->wp_enqueue_script( 'action_enqueue_masterslider_script' );
?>
2.added this to a component page: 	/**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */
	public function initialize() {
		add_action( 'wp_enqueue_scripts', array( $this, 'action_enqueue_masterslider_script' ) );
	}
/**
	 * Enqueues a script that improves navigation menu accessibility.
	 */
	public function action_enqueue_masterslider_script() {

		// If the AMP plugin is active, return early.
		if ( wp_rig()->is_amp() ) {
			return;
		}
		// Enqueue the navigation script.
		wp_enqueue_script(
			'wp-rig-masterslider',
			get_theme_file_uri( '/assets/js/masterslider.min.js' ),
			array(),
			wp_rig()->get_asset_version( get_theme_file_path( '/assets/js/masterslider.min.js' ) ),
			false
		);
		wp_script_add_data( 'wp-rig-masterslider', 'async', true );
		wp_script_add_data( 'wp-rig-masterslider', 'precache', true );
		wp_localize_script(
			'wp-rig-masterslider',
			'wpRigScreenReaderText',
			array(
				'expand'   => __( 'Expand child menu', 'wp-rig' ),
				'collapse' => __( 'Collapse child menu', 'wp-rig' ),
			)
		);
	}
3. 
4.

## Current Behavior

It says: 
![Screen Shot 2021-03-06 at 4 08 00 PM](https://user-images.githubusercontent.com/38434839/110220812-2d970c00-7e96-11eb-8c02-996a0f287ffe.png)
Fatal error
: Uncaught BadMethodCallException: The template tag wp_rig()->wp_enqueue_script() does not exist. 
## Related Issues and/or PRs

there are a few more javascript files that come with it, how to link them all?, sorry, new to javascript, familiar with html and css

**Comment by jacklowrie** [comment]
Hi @ansikun2, not sure what's going on at first glance - from the error, it looks like you may be calling `wp_rig()->wp_enqueue_script()` somewhere else in your theme. Maybe try searching your project for that?

If that doesn't work, can you attach a screenshot of your terminal with that error (there might be a clue somewhere else in the output)

This will help in figuring out what's going on.

**Comment by dthenley** [comment]
Hi @ansikun2 can you check to make sure that `use function wp_enqueue_style; ` is implemented at the top of your file.

I would suggest checking https://github.com/wprig/wprig/blob/master/inc/Styles/Component.php#L15 . if you send a link of the file or at least the top that would definitely help narrow down the issue.

**Comment by robruiz** [comment]
This seems to be resolved. We have a js component for this kind of thing. Also, in some cases, it does make sense to create a custom component to help you manage your custom JS file enqueues separate from the WP Rig ones. There is also a handy filter called 'wp_rig_js_files' found in the inc/scripts/component.php that allows you to just add to an array and it will manage these things for you. Combine this with a custom component and it allows you to keep your custom code nicely separated from the WP Rig code if that's your preference.
