### ISSUE TITLE
No padding on mobile for full width content

### ISSUE THREAD

**Issue by dthenley** [wprig/wprig#708]
## Issue Overview

content with the width of alignfull has no padding on mobile.

**Comment by erdmann040** [comment]
Does not happend on unchanged wp-rig installation, right? I had the same issue after i changed the custom-property `--content-width`, did you too? 

So i looked out, which part of the (Post)CSS-Codes left the padding disappear and found this in the content.css: (line 87 and following

```
.page-content > *,
.entry-content > *,
.entry-summary > *,
.page-header,
.entry-header,
.entry-footer,
.site-info,
.post-navigation,
.page-navigation,
.comments-area {
	margin-left: auto;
	margin-right: auto;
	padding-right: 1.5rem;
	padding-left: 1.5rem;
	max-width: var(--content-width);
}

@media (--content-query) {

	.entry-content > ul,
	.entry-content > ol {
		padding-left: 2.5em;
		padding-right: 2.5em;
	}

	.page-content > *,
	.entry-content > *,
	.entry-summary > *,
	.page-header,
	.entry-header,
	.entry-footer,
	.site-info,
	.post-navigation,
	.page-navigation,
	.comments-area {
		padding-left: 0;
		padding-right: 0;
	}
}
 
```

So if you change the `--content-width` in `_custom-properties.css`(have you?), you also should change the value of `--content-query` ins `_custom-media.css`.

It might be a good idea for to define the  `--content-query` by using the `--content-width` value in wp-rig 3?

**Comment by dthenley** [comment]
I thought this was the case for me as well since I work on a little different base install of wprig for my own projects but when it goes to mobile and even in desktop view it is showing it stretches content from end to end unless it's wrapped in some type of container

Desktop:
![image](https://user-images.githubusercontent.com/3503886/122489936-6458e400-cfa6-11eb-8d37-21b34976a42d.png)

Mobile:
![image](https://user-images.githubusercontent.com/3503886/122489990-89e5ed80-cfa6-11eb-8aaa-7af9c88072f0.png)
