### ISSUE TITLE
how to add a function

### ISSUE THREAD

**Issue by ansikun2** [wprig/wprig#709]
## Issue Overview

I am still can't find a tutorial or explanation on how to add a function. I understand that they are now added as "components" in the "inc" folder. But how can I add a new one. I don't know enough php to write them myself so I usually find them from someone else and copy/paste. Liek this one:

add_action( 'parse_query', 'enfold_customization_homepage_sticky_posts' );
function enfold_customization_homepage_sticky_posts( $query ){
	if ( is_home() ) {
		$sticky = get_option( 'sticky_posts' );
		set_query_var( 'post__in', $sticky );
	}
}

it displays only sticky posts on the front page.
How would I enqueue and run it in the component?
I wish the Linkedin course would explain it in more detail on how to add new functions, 
Thank you so much!

## Describe your environment

wp-rig, visual studio code with composer, gulp, and so on

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dthenley** [comment]
Hey @ansikun2 sorry you're having a bit of an issue implementing new features but the new way (while it will have a bit of a  learning curve) is meant to help clean up your code from having just one huge functions.php file. You can see a much better explanation of how to add a basic component structure on the wprig site here https://wprig.io/learn/build-a-basic-component-v2/.

Here is a non-tested version of how I would implement the new function that you have going there.

1. Create a new folder inside of the inc folder and name it something like "Home_Sticky_Post" So you know exactly what the code is supposed to do. Inside the folder create the Component.php file. 
2. At the top of the Component.php file make sure to include all the functions you will be using I think for something like this you should be good with the basic
  
```
<?php
/**
 * WP_Rig\WP_Rig\Home_Sticky_Post\Component class
 *
 * @package wp_rig
 */

namespace WP_Rig\WP_Rig\Home_Sticky_Post;

use WP_Rig\WP_Rig\Component_Interface;
use function add_action;
```
3. After adding the header information you want to implement your new class
```
/**
 * Class for displays only sticky posts on the front page.
 *
 * @link https://github.com/wprig/wprig/issues/709
 */
class Component implements Component_Interface {

	/**
	 * Gets the unique identifier for the theme component.
	 *
	 * @return string Component slug.
	 */
	public function get_slug() : string {
		return 'home_sticky_post';
	}

	/**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */
	public function initialize() {
		add_action( 'parse_query', array( $this, 'enfold_customization_homepage_sticky_posts' ) );
	}
       
        /**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */
	public function function enfold_customization_homepage_sticky_posts( $query ){
             if ( is_home() ) {
              $sticky = get_option( 'sticky_posts' );
               set_query_var( 'post__in', $sticky );
              }
         }
}
```

I HAVE NOT TESTED THIS so that's a bit of a warning lol. You might have to call a different function in the header for the query and get_option but I'm not sure. Try it out and let me know what you come up with.

**Comment by ansikun2** [comment]
Thank you so much, Donte,
I made that new folder with a component file and registered it in the Theme.php (			new Home_Sticky_Post\Component(),) like the build_basic_component video explained.

This is the code I used in the inc/Home_Sticky_Post/Component.php
`<?php
/**
 * WP_Rig\WP_Rig\Home_Sticky_Post\Component class
 *
 * @package wp_rig
 */

namespace WP_Rig\WP_Rig\Home_Sticky_Post;

use WP_Rig\WP_Rig\Component_Interface;
use function add_action;
/**
 * Class for displays only sticky posts on the front page.
 *
 * @link https://github.com/wprig/wprig/issues/709
 */
class Component implements Component_Interface {

	/**
	 * Gets the unique identifier for the theme component.
	 *
	 * @return string Component slug.
	 */
	public function get_slug() : string {
		return 'home_sticky_post';
	}

	/**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */
	public function initialize() {
		add_action( 'parse_query', array( $this, 'enfold_customization_homepage_sticky_posts' ) );
	}

	/**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */
	public function enfold_customization_homepage_sticky_posts( $query ){
		if ( is_home() ) {
			$sticky = get_option( 'sticky_posts' );
			set_query_var( 'post_in', $sticky );
		}
	}
}
`
(i figured that the public function function, and double space in post__in at the end were typos)

It does display the sticky posts on the homepage (that part was working ok before too), but it still puts in other posts that are not sticky. I am trying to display only sticky posts and disregard the rest.

so, I tried to register the new function in the header with 
`wp_rig()->enfold_customization_homepage_sticky_posts();` but that gives an error:

"Fatal error: Uncaught BadMethodCallException: The template tag wp_rig()->enfold_customization_homepage_sticky_posts() does not exist. in /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-content/themes/wprig-master/inc/Template_Tags.php:78 Stack trace: #0 /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-content/themes/wprig-master/header-home.php(14): WP_Rig\WP_Rig\Template_Tags->__call('enfold_customiz...', Array) #1 /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-includes/template.php(730): require_once('/Users/ansikun/...') #2 /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-includes/template.php(676): load_template('/Users/ansikun/...', true, Array) #3 /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-includes/general-template.php(48): locate_template(Array, true, true, Array) #4 /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-content/themes/wprig-master/front-page.php(12): get_header('home') #5 /Users/ans in /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-content/themes/wprig-master/inc/Template_Tags.php on line 78"

**Comment by dthenley** [comment]
There's no need to register that function in the header.
 
Yeah the double function function was a typo but not the double underscore. That is actually a part of the wpquery. Im not sure how you are using that piece of code but i suggest maybe looking at the official wordpress doc for working with sticky posts https://developer.wordpress.org/themes/functionality/sticky-posts/.  It depends on how you are pulling in the blog post that you are viewing on the homepage, is it being queryed in or some other type of way.

**Comment by ansikun2** [comment]
yeah, it worked after restarting the visual studio code and a new npm run dev. maybe it was still somehow cached before. 
thank you so much!
I will try to learn some more php so I can understand how to do this myself at some point, but thank you so much for your help!

**Comment by dthenley** [comment]
Well it sounds like you are definitely heading in the right direction. I highly suggest etching out a couple days and watching the whole wprig series from the wprig.io site to get a good feel and understanding for it. If you have any more questions just come back here and we're more than happy to help out.
