### ISSUE TITLE
functions are still somewhat a mystery

### ISSUE THREAD

**Issue by ansikun2** [wprig/wprig#710]
## Issue Overview
To add a new function I followed Morten Rand-Hendriksen Linkedin tutorial as much as possible, and thanks to Donte Henley solved one issue. 
Now I tried to do it myself, task: to add a custom menu, but I am getting errors
 

## Describe your environment
wp-rig, visual studio pro

## Steps to Reproduce

1. I added a new folder _Custom_Menu_ in _inc_ and a components file
2. registered the file in theme.php with a new line as 	new Custom_Menu\Component(), it seems to recognize that
3. i tried to replicate this function from https://www.wpbeginner.com/wp-themes/how-to-add-custom-navigation-menus-in-wordpress-3-0-themes/: 
`function wpb_custom_new_menu() {
  register_nav_menu('my-custom-menu',__( 'My Custom Menu' ));
}
add_action( 'init', 'wpb_custom_new_menu' );` i used it before and it worked
4. this is what my components file looks like:
`<?php
/**
 * WP_Rig\WP_Rig\Custom_Menu\Component class
 *
 * @package wp_rig
 */

namespace WP_Rig\WP_Rig\Custom_Menu;

use WP_Rig\WP_Rig\Component_Interface;
use function register_nav_menus;
use function add_action;

/**
 * Class for custom menu.
 */
class Component implements Component_Interface {

	/**
	 * Gets the unique identifier for the theme component.
	 *
	 * @return string Component slug.
	 */
	public function get_slug() : string {
		return 'custom_menu';
	}

	/**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */
	public function wpb_custom_new_menu() {
		register_nav_menus('custom_menu',__( ' My Custom Menu ' ));}
		add_action( 'init', ' wpb_custom_new_menu ' );
	}
}`
## Expected Behavior
getting a tickmark in the menus editor to click on My Custom Menu

## Current Behavior
Parse error: syntax error, unexpected 'add_action' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-content/themes/wprig-master/inc/Custom_Menu/Component.php on line 34

## Possible Solution
learning php functions, i just copy/paste that without really understanding it

**Comment by dthenley** [comment]
So it looks like to me you havent yet initialized the component.

You would need to add the code below the get_slug function https://github.com/wprig/wprig/blob/f4e1189a4540b14d3d74bda9a3f28136df0a4fcd/inc/Nav_Menus/Component.php#L40-L46

inside the initialize you will want to add code something like
`add_action( 'init', array( $this, 'wpb_custom_new_menu' ) );`

Also go ahead adn remove the add_action that is inside of the function. You can't call and initialize the function at the same time. The code above will initialize it for you.

**Comment by ansikun2** [comment]
thank you so much again for your super quick response. I am browsing to pick a course on php asap

i tried this in the Custom_Menu/component.php file:
` *
 * @package wp_rig
 */

namespace WP_Rig\WP_Rig\Custom_Menu;

use WP_Rig\WP_Rig\Component_Interface;
use function register_nav_menus;
use function add_action;


/**
 * Class for custom menu.
 */
class Component implements Component_Interface {

	/**
	 * Gets the unique identifier for the theme component.
	 *
	 * @return string Component slug.
	 */
	public function get_slug() : string {
		return 'custom_menu';
	}
	/**
	* Adds the action and filter hooks to integrate with WordPress.
	*/
	public function initialize() {
		add_action( 'init', array( $this, 'wpb_custom_new_menu' ) );
		add_filter( 'walker_nav_menu_start_el', array( $this, 'filter_primary_nav_menu_dropdown_symbol' ), 10, 4 );
	}

	/**
	 * Adds the action and filter hooks to integrate with WordPress.
	 */
	public function wpb_custom_new_menu() {
		register_nav_menus('custom_menu',__( ' My Custom Menu ' ));}
	}
}`

If i take out the last wpb_custom_new_menu part it loads the site, but with some error message. And with it, it says:
Parse error: syntax error, unexpected '}', expecting end of file in /Users/ansikun/my-project/Users/ansikun/Sites/anselm_dastner2021/wp-content/themes/wprig-master/inc/Custom_Menu/Component.php on line 42

**Comment by dthenley** [comment]
I can't be for certain but it looks like you have added an extra closing brace on the line of code at line 42. It looks like an extra curly function in the wpb_custom_new_menu() fucntion

**Comment by ansikun2** [comment]
yeah, I found someone doing a tutorial on adding a menu in components: 
https://www.linuxbookpro.com/wp-rig-creating-a-menu/
