### ISSUE TITLE
Block editor now progressively loads CSS almost like wprig! but CSS conflicts

### ISSUE THREAD

**Issue by LukaszJaro** [wprig/wprig#711]
Hello,

The newest version of Gutenberg block editor supports loading core-blocks assets when the blocks are used/rendered on page, see more here:
https://github.com/WordPress/gutenberg/pull/25220

This greatly reduces the CSS transferred and improves page loading performance. These updates were targeted for full site editing(FSE) but can be enabled in classic themes through a filter. 

The way it works is by loading a separate stylesheet for each block that is used on the page and in addition, for small stylesheets, maybe less than 2kb, are inlined in the html. This helps with reducing the http requests.

Too enable this in classic theme, you probably need latest Gutenberg version, and then add these filters:

```
//loads separate stylesheets for each block on page
add_filter( 'load_separate_block_assets', '__return_true' );
//inlines the CSS when stylesheets are of smaller nature
add_action( 'wp_footer', 'gutenberg_maybe_inline_styles', 1 );
```

The issue, due to the new way of loading block editor css, the theme css is being overridden in some places, like choosing a button color in the editor for example.
I opened a ticket for this and the Gutenberg Gods answered:

> In an FSE theme, blocks get parsed before the <head>, while in classic themes blocks get parsed on-render. The result of that is that in FSE themes stylesheets get printed in <head>, and in classic themes they get printed in the footer.
> In order for your theme's styles to override them, you can either make them more specific, OR load them in the footer (you can accomplish that by hooking your wp_enqueue_style calls in wp_footer for example).

-https://github.com/WordPress/gutenberg/issues/31013

WPRIG has it's own way of loading CSS, how practical would it be to use the suggested methods? I did some testing with mixed results, I need more time to test properly but I managed to load the css after the inlined block css and the theme css was not overridden but some other things were out of place probably because I did not do it correctly.

**Comment by LukaszJaro** [comment]
If you have an existing theme and you want to opt-in to this improvement, you will need to test your theme for style priorities. Opting-in to separate styles loading in a classic theme means that the loading order of styles changes. Block styles that used to be in the head will move to the footer, so you will need to check your theme’s styles and make sure any opinionated styles you add to blocks have a higher priority than core styles.

There are many ways you can address this on your theme, it all comes down to what you want to do.

- **Solution 1**: Increasing specificity for block CSS in the theme. You can change the specificity of theme theme’s CSS rules so they override the default block styles rules. If for example the theme was previously using .wp-block-button as a selector in its CSS, it can now change to :root .wp-block-button, body .wp-block-button, .wp-block-button.wp-block-button or anything else that has a higher specificity than the .wp-block-button selector.

- **Solution 2**: Making the theme’s blocks stylesheet load after core styles: You can change the way the theme’s styles get loaded. Instead of hooking in wp_enqueue_scripts you can hook in wp_footer. This will make the theme’s stylesheet load after the block styles have been added, and therefore override them. Note: This should be avoided if you don’t have separate stylesheets for block-styles and global styles.

- **Solution 3**: Don’t use separate styles loading. Use this solution if your theme is not ready for these improvements, or if you don’t want to deal with the complexities of the above 2 solutions. If you have added add_filter( 'should_load_separate_core_block_assets', '__return_true' ); in your theme remove it. If you haven’t added that line, the add add_filter( 'should_load_separate_core_block_assets', '__return_false' ); and that should disable the feature.

The above only makes sense if you are not working on a block-based theme. If you are on a block-based theme, then something else must be wrong and should be further investiated.

https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/

**Comment by robruiz** [comment]
I would be interested in having a larger discussion around this. Possibly a virtual live discussion. Thoughts on that? I would obviously help organize it.
