### ISSUE TITLE
Best Practice in Creating General Functions/Add_Action?

### ISSUE THREAD

**Issue by Radizzt** [wprig/wprig#713]
## Issue Overview

I'm looking for a best practice way to add this function, or these type of add_action function in general.
This one specifically let me use WordPress REST API to filter through Category Names:
```
function wpse_287931_register_categories_names_field()
{
    register_rest_field(
        array('post'),
        'categories_names',
        array(
            'get_callback'    => 'wpse_287931_get_categories_names',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}

add_action('rest_api_init', 'wpse_287931_register_categories_names_field');

function wpse_287931_get_categories_names($object, $field_name, $request)
{
    $formatted_categories = array();

    $categories = get_the_category($object['id']);

    foreach ($categories as $category) {
        $formatted_categories[] = $category->name;
    }

    return $formatted_categories;
}

```
 I would usually just drop that code in the function.php at the root of the theme folder before.

## Describe your environment

Visual Studio Code
Chrome

## Steps to Reproduce

1. I included the code in the function.php file in the _/inc/_ folder
2. go to URL: site.local/wp-json/wp/v2/posts?category_name=Nature

## Expected Behavior

Show me the correct info when I go to this URL: site.local/wp-json/wp/v2/posts?category_name=Nature
## Current Behavior

I'm getting warning such as this at the top:
>  call_user_func_array() expects parameter 1 to be a valid callback, function 'wpse_287931_register_categories_names_field' not found or invalid function name in _[MyPath]_/wp-includes/class-wp-hook.php on line 292

and like 6 other about header already sent:
> Warning: Cannot modify header information - headers already sent by (output started at _[MyPath]_/wp-includes/class-wp-hook.php:292) in _[MyPath]_/wp-includes/rest-api/class-wp-rest-server.php on line 1642

**Comment by dthenley** [comment]
Hey @Radizzt I walk through what I think is the simplest way to add a function in wprig here https://github.com/wprig/wprig/issues/709. Take a look and let me know if you have any questions.

**Comment by Radizzt** [comment]
Thank for the info @dthenley. I manage to get it working with the thread you link. Thanks!
