### ISSUE TITLE
No Read More Link on Recent Post Block

### ISSUE THREAD

**Issue by dthenley** [wprig/wprig#714]
## Issue Overview

The recent post block is not showing a read more link by default even though it shows it on the preview

## Describe your environment

Wamp
Wordpress 5.7.1

## Steps to Reproduce

1. Create a recent post block
2. Make sure Max number of words exceed the amount of words in the blog post
3. View on preview or published page

## Expected Behavior

Add a read more link at the end of excerpt 

## Current Behavior

Add elipses but nothing else

## Possible Solution

Other stock themes look to do their own version of read more at the end of the block so maybe use a variation of that and hopefully move the [...] at the end

**Comment by robruiz** [comment]
@dthenley is this one fixed now?
