### ISSUE TITLE
CSS nesting produces errors

### ISSUE THREAD

**Issue by erdmann040** [wprig/wprig#716]
## Issue Overview

Not realy a bug in wp-rig itself but in the recommended configuration of visual studio code:

If I use nested selectors, like here:

```
div.myclass {
	color: #000;

	& a {
		color: #f0f;
	}

}

```

the following errors are reported (see screenshot below): 
* `} expected css(css-rcurlyexpected)`
* `at-rule or selector expected css(css-ruleorselectorexpected),`

This should work out of the box, shouldn't it? Or do i have to do any extra configuration to make this work? 

## Describe your environment

I followed Mortens videos. Here is my `.vscode/settings.json`:

```
{
  "prettier.stylelintIntegration": true,
  "prettier.eslintIntegration": true,
  "editor.formatOnSave": true,
  "editor.renderWhitespace": "all",
  "phpcs.enable": true,
  "phpcs.composerJsonPath": "./composer.json",
  "phpcs.standard": "WordPress"
}
```

I downgraded Prettier to Version 1.12.0. Otherwise this configuration wouldn't work, as descriped in https://github.com/wprig/wprig/issues/703. 
   
My OS is Fedora Linux 32, but I reproduced the problem on Windows 10 in a vm. 

## Steps to Reproduce

I followed the videos and used used Local by Flywheel as the local environment, the VS Code extensions that where linked in the wiki. If other persons do not have the same problem I will describe all my installations and configurations steps in detail here. 

## Expected Behavior

Expected that nested CSS-selectors would work out of the box. At least if you do not override the default configurations in the config folder

## Possible Solution

Installed another extension  

ext install mhmadhamster.postcss-language

and added three lines to my  my `.vscode/settings.json`:

```
{
   ...
   "files.associations": {
       "*.css": "postcss"
   },
   ...
}
```
But I am not completely satisfied with this solution. I don't get an error if I forget the ampersand "&" in front of an embedded selector, which happens to me all the time because I used Sass before.

## Screenshots / Video

<img src="https://s20.directupload.net/images/210517/ngzwi8ol.png">

## Related Issues and/or PRs

https://github.com/wprig/wprig/issues/703  

Thanks in advance for any suggestions

**Comment by robruiz** [comment]
@dthenley Can you look into this issue while you are working on your little project? Thanks.

**Comment by dthenley** [comment]
Sorry you're having this issue @erdmann040 I've also ran into this issue while utilizing nesting. Because nesting is not officially apart of vanilla css VS code is automatically spitting out errors. The best way to fix this issue is to install the VS Code plugin https://marketplace.visualstudio.com/items?itemName=csstools.postcss. this will fix up those nasty little errors. Let me know if that helps you out.

**Comment by dthenley** [comment]
Hey sometimes all you need is someone to point out the obvious, i know this happens for me more often than naught.

It doesn't mark it as an error when writing but when the compiler or browsersync runs.

**Comment by robruiz** [comment]
Marking this as closed as this is IDE-specific. A PostCSS plugin for VS Code or PHPStorm resolves these kinds of issues.
