### ISSUE TITLE
Add phpcbf to help fix minor errors automatically

### ISSUE THREAD

**Issue by adamwhitlock1** [wprig/wprig#72]
## Issue Overview
Setting up a theme from other existing files, I am getting a ton of phpcs warnings on rebuild.

## Describe your environment
MacOs High Sierra, php7.1.7, WP 4.9.7, mysql 5.6.37, nginx

## Possible Solution
Add in a gulp task to run phpcbf and fix errors

Overall I am loving wprig in general. Thank you for making such a great modern wp starter!

**Comment by mor10** [comment]
Tentatively yes, though I'd like to see someone do a test to figure out if the fixing is clean or it it can cause new issues.

**Comment by jdelia** [comment]
I am using phpcbf with vscode and it is working.

**Comment by ataylorme** [comment]
Any objection for this being a Composer script rather than a gulp task? That will be a simpler solution as PHPCS is installed via Composer. We might be able to make a gulp task that calls the Composer script as well.

**Comment by ataylorme** [comment]
After thinking on this I think we should use gulp. If we were to use PHPCBF directly of via Composer then it will attempt to fix all PHP files, including `vendor`.

We could list out which files to include and exclude but that would be duplicating the same declarations in gulp and we should not repeat ourselves in this way.

However, I tried using [`gulp-phpcbf`](https://www.npmjs.com/package/gulp-phpcbf) but could not get it working.

I also tried changing the `bin` in [`gulp-phpcs`] (https://www.npmjs.com/package/gulp-phpcs) to be `phpcbf` but that did not work.

It seems we will either need to fork `gulp-phpcs` project to work with `phpcbf` or figure out what is wring with `gulp-phpcbf`, which hasn't been updated in 4 years.

Either way that is too much work than I can commit to. If someone else wants to take a stab at this please do.

**Comment by mor10** [comment]
What needs to be done to close this issue?

**Comment by ataylorme** [comment]
> What needs to be done to close this issue?

A task similar to the existing `run-phpcs` needs to be added to the `scripts` section of `composer.json` that will run PHP code beautifier.
