### ISSUE TITLE
Inc/Styles/Component.php Question: Putting Multiple CSS Files

### ISSUE THREAD

**Issue by Radizzt** [wprig/wprig#724]
## Issue Overview

I have a CSS code block that is used on half of the page templates I built. The way I've been doing it is putting that code block in its own CSS file and listing it as a separate array item in the `$css_files` array like so:

```
'wp-rig-who-we-are'   => array(
	'file'          => 'who-we-are.min.css',
),
'wp-rig-generic-bottom-section'   => array(
         file'          => 'generic-bottom.min.css',
),
```
and including it into the page template I want at the top:

```
<?php
/**
 * Template Name: Who We Are
 *
 * @package wp_rig
 */

namespace WP_Rig\WP_Rig;

use  WP_Query;

get_header();

wp_rig()->print_styles( 'wp-rig-who-we-are' );
wp_rig()->print_styles( 'wp-rig-generic-bottom-section' );

?>
```
Is this the best way to approach it, or is there a way for me to have multiple files in the `wp-rig-who-we-are` array like

```
'wp-rig-who-we-are'   => array(
	'file'          => 'who-we-are.min.css',
        'file'          => 'generic-bottom.min.css'
),

or

'wp-rig-who-we-are'   => array(
	'file'          => 'who-we-are.min.css generic-bottom.min.css',
),
```

Thanks in advance

**Comment by dthenley** [comment]
Hey @Radizzt one way i can suggest on how to implement 2 css files on one page template would be to separate the callback by commas. So for your template page you can call your 2 callbacks like `wp_rig()->print_styles( 'wp-rig-who-we-are', 'wp-rig-generic-bottom-section' );`. You can see an example of this by looking at the front-page.php file in the optional folder https://github.com/wprig/wprig/blob/f4e1189a4540b14d3d74bda9a3f28136df0a4fcd/optional/front-page.php#L16

**Comment by dthenley** [comment]
As for combining 2 files in the css preload and callback i would suggest trying to put the files in an array. I haven't tested it but it's worth the try.

	'wp-rig-front-page' => array(
		'file' => array( 'front-page.min.css', 'secondary.min.css' ),
		'preload_callback' => function() {
			global $template;
			return 'front-page.php' === basename( $template );
		},
	),,

This will preload it for your desired template and hopefully load multiple files. Try it out and let me know how it turns out

**Comment by Radizzt** [comment]
Thanks @dthenley.

> https://github.com/wprig/wprig/blob/f4e1189a4540b14d3d74bda9a3f28136df0a4fcd/optional/front-page.php#L16

This worked perfectly.

But as for combining 2 files in the css preload, that did not work as intended. There was no error, but the file was not loaded into the page.

**Comment by dthenley** [comment]
@Radizzt i'm glad to hear the first solution worked out. As for the second problem, the best solution i think you can do is to make an overall css file and then import those two files into it. This will enable you to keep the two css files seperate but call them at one time.

**Comment by Radizzt** [comment]
@dthenley  I'll go do that then.

Thanks for the help!
