### ISSUE TITLE
Getting error when I type npm run dev

### ISSUE THREAD

**Issue by neltongemo** [wprig/wprig#726]
## Issue Overview

I am trying to use wprig to develop wordpress themes.
I installed the wprig on WordPress local enviroment, but i could not get it runing because this error:
TypeError in plugin "gulp-postcss"
Message:
    plugin is not a function
Details:
    fileName: C:\xampp\htdocs\wp5\wp-content\themes\wprig\assets\css\src\comments.css

Stack:
TypeError: plugin is not a function
    at LazyResult.run (C:\xampp\htdocs\wp5\wp-content\themes\wprig\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.es6:352:14)
    at LazyResult.asyncTick (C:\xampp\htdocs\wp5\wp-content\themes\wprig\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.es6:280:26)
    at LazyResult.asyncTick (C:\xampp\htdocs\wp5\wp-content\themes\wprig\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.es6:292:14)
    at C:\xampp\htdocs\wp5\wp-content\themes\wprig\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.es6:285:16
[14:21:11] 'default' errored after 9.34 s

## Describe your environment

Windows 10 x64
Xampp v3.3.0
Nodejs v12.18.1.
VSCode
Google Chrome browser
## Steps to Reproduce

1.
2.
3.
4.

## Expected Behavior

Get the link to live preview of the website

## Screenshots / Video

![image](https://user-images.githubusercontent.com/17059068/123544676-aaefd080-d754-11eb-8a37-cb391cc983e1.png)

**Comment by dthenley** [comment]
1. Have you successfully been able to run the `npm run dev` command previously?
2. I would suggest re running `npm run rig-init` to make sure all the composer and npm dependencies are installed
3. Have you made any changes to the `comments.css` file? If you have been able to compile it previously and have made changes, sometimes if there is an error in your css file it will stop.

**Comment by neltongemo** [comment]
Dear @dthenley,
Thank you for this answer
This is my first time with WPRig. 
After clean and reinstall everything I was able to run `npm run rig-init` successfully but I am getting another error when I try `npm run dev` as you can see in attach
![image](https://user-images.githubusercontent.com/17059068/123559019-e95bae80-d799-11eb-863d-e8420ed8b61a.png)

Best regards!

**Comment by neltongemo** [comment]
Dear all!

It is was incompatibility of Node and Gulp Version: https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node-js
Solved

**Comment by neltongemo** [comment]
Thank you all of you!
