### ISSUE TITLE
Issues/concerns with theme slug and name replace

### ISSUE THREAD

**Issue by bamadesigner** [wprig/wprig#73]
## Issue Overview
We might need to re-think the global search/replace of the theme slug and name. OR at least give some documentation/instructions in the config file.

For example, be clear if the slug should have no dashes or underscores or spaces.

Example of an issue:

We use "wprigScreenReaderText" as a JS variable in our navigation script. But the "wprig" gets changed in the gulp php and scripts search/replace. I had an issue where my slug had underscores and it was causing issues because that was setting the name of a JS variable.

Related to #43.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by ev3rywh3re** [comment]
I too noticed the issue with dashes which is familiar with JavaScript. Didn’t notice the underscore yet (it’s my go to space replacement 😬)

**Comment by bamadesigner** [comment]
Heads up @mor10.

**Comment by bamadesigner** [comment]
Related to #43.

**Comment by mor10** [comment]
The dirty workaround here is to change `wprigScreenReaderText` to just `screenReaderText`, but yes, we need to think carefully about this.

**Comment by felixarntz** [comment]
@bamadesigner I think #93 addressed this, and the remaining bit that was missed there will be fixed by #123. Can you confirm this?

**Comment by mor10** [comment]
is this one good to close?
