### ISSUE TITLE
Any news on errorrs?

### ISSUE THREAD

**Issue by fernandofas** [wprig/wprig#733]
**Issue:**

There are plenty of errors when using npm run rig-init.
The "gulp-phpcs" is one of them, which I still haven't found the right solution for the issue after a few months googleing around.
There are many different errors on the img-min package.

**My Environment:**

I'm using Windows 10, Latest VS Code, PHP 7.4, latest XAMP version, latest Wordpress version.

**My error:**

After copy the files inside the themes folder in a newly installed Wordpress installation, I opened the folder where the theme is located in VS Code and run `npm run rig-init`.
After a few seconds, a ton of errors comes up in the terminal.
Ok, npm audit fix....
After the procedures above, I run npm run dev and the following error comes up:

> wprig@2.0.1 dev C:\xampp\htdocs\mpid\wp-content\themes\wprig
> gulp

[15:46:57] Requiring external module @babel/register
[15:46:59] Using gulpfile C:\xampp\htdocs\mpid\wp-content\themes\wprig\gulpfile.babel.js
[15:46:59] Starting 'default'...
[15:46:59] Starting 'cleanCSS'...
[15:46:59] Finished 'cleanCSS' after 8.91 ms
[15:46:59] Starting 'cleanJS'...
[15:46:59] Finished 'cleanJS' after 2.36 ms
[15:46:59] Starting 'php'...
[15:46:59] Starting 'images'...
[15:46:59] Starting 'scripts'...
[15:46:59] Starting 'styles'...
[15:47:00] gulp-imagemin: Minified 0 images
[15:47:00] Finished 'images' after 851 ms
[15:47:01] 
C:\xampp\htdocs\mpid\wp-content\themes\wprig\assets\js\src\customizer.js
   1:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:23  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:3   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   4:63  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:3   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   6:85  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   7:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:18  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:47  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:36  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:7   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  16:54  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  17:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  18:40  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  19:7   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  20:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  21:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  22:23  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  23:55  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  24:31  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  25:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  26:49  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  27:39  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  28:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  29:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  30:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  31:49  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  32:19  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  33:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  34:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  35:51  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  36:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  37:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  38:5   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  39:7   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  40:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  41:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

C:\xampp\htdocs\mpid\wp-content\themes\wprig\assets\js\src\navigation.js
    1:35   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    2:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    3:23   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    4:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    5:78   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    6:42   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    7:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    8:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
    9:17   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   10:9    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   11:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   12:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   13:43   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   14:37   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   15:66   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   16:9    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   17:37   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   18:19   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   19:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   20:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   21:42   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   22:28   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   23:26   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   24:23   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   25:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   26:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   27:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   28:38   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   29:49   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   30:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   31:35   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   32:68   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   33:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   34:25   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   35:29   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   36:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   37:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   38:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   39:48   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   40:46   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   41:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   42:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   43:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   44:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   45:42   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   46:53   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   47:43   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   48:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   49:43   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   50:22   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   51:54   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   52:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   53:29   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   54:28   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   55:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   56:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   57:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   58:32   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   59:45   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   60:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   61:47   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   62:51   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   63:62   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   64:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   65:33   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   66:22   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   67:23   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   68:48   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   69:41   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   70:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   71:57   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   72:54   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   73:43   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   74:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   75:26   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   76:69   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   77:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   78:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   79:33   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   80:63   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   81:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   82:44   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   83:53   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   84:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   85:42   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   86:68   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   87:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   88:59   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   89:59   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   90:41   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   91:7    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   92:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   93:62   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   94:60   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   95:37   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   96:7    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   97:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   98:70   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   99:76   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  100:113  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  101:63   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  102:57   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  103:5    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  104:7    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  105:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  106:56   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  107:56   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  108:75   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  109:82   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  110:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  111:37   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  112:24   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  113:65   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  114:89   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  115:51   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  116:7    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  117:59   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  118:94   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  119:50   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  120:6    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  121:5    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  122:7    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  123:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  124:69   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  125:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  126:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  127:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  128:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  129:38   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  130:47   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  131:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  132:32   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  133:70   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  134:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  135:25   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  136:29   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  137:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  138:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  139:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  140:48   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  141:44   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  142:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  143:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  144:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  145:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  146:40   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  147:53   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  148:43   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  149:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  150:41   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  151:57   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  152:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  153:43   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  154:23   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  155:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  156:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  157:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  158:45   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  159:54   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  160:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  161:50   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  162:45   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  163:117  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  164:13   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  165:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  166:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  167:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  168:77   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  169:55   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  170:55   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  171:18   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  172:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  173:56   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  174:74   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  175:50   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  176:91   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  177:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  178:81   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  179:76   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  180:41   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  181:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  182:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  183:33   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  184:87   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  185:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  186:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  187:35   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  188:58   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  189:80   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  190:5    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  191:32   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  192:31   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  193:62   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  194:45   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  195:75   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  196:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  197:40   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  198:91   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  199:59   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  200:53   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  201:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  202:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  203:36   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  204:107  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  205:62   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  206:56   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  207:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  208:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  209:30   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  210:59   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  211:42   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  212:77   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  213:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  214:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  215:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  216:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  217:31   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  218:32   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  219:45   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  220:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  221:31   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  222:60   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  223:52   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  224:58   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  225:76   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  226:24   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  227:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  228:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  229:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  230:34   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  231:45   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  232:29   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  233:27   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  234:33   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  235:96   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  236:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  237:72   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  238:72   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  239:39   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  240:45   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  241:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  242:15   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  243:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  244:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  245:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  246:34   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  247:44   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  248:29   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  249:27   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  250:33   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  251:95   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  252:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  253:71   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  254:72   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  255:39   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  256:72   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  257:3    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  258:15   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  259:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 300 problems (300 errors, 0 warnings)
  300 errors and 0 warnings potentially fixable with the `--fix` option.

[15:47:02] 'php' errored after 3.19 s
[15:47:02] Error in plugin "gulp-phpcs"
Message:
    Cannot find "C:\xampp\htdocs\mpid\wp-content\themes\wprig/vendor/bin/phpcs"
[15:47:02] 'default' errored after 3.2 s
[15:47:02] The following tasks did not complete: <series>, scripts, styles     
[15:47:02] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.1 dev: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@2.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fernandosilva\AppData\Roaming\npm-cache\_logs\2021-07-27T14_47_02_595Z-debug.log`

Any help on these issues would be great appreciated.

Kind regards,

Fernando

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dthenley** [comment]
Can you check to make sure you have composer installed by opening up your terminal and typing composer -V. If composer is installed correctly, you should see a version number.

**Comment by dthenley** [comment]
@erdmann040 I wonder if there is a way to automate that check, I know this is the source of a lot of headache for a lot of people

**Comment by erdmann040** [comment]
@dthenley You raise an important point here. Configuring the development environment correctly is probably the biggest difficulty for WP-Rig beginners and I still haven't quite mastered this challenge. The documentation is incomplete and outdated in this point.

**Comment by erdmann040** [comment]
Here a description that might help others to solve the iineending problem. Please send my feedback wether this helped or not cause im on Linux and actualy never had this trouble.  

### Git Config Levels 

Its important to know a little bit abount the way git can be configured. Git knows three configuration levels:

`system`, `global` (settings for the current user account) and project specific settings. 

Settings on higher levels will be overwritten on the one on a more specific levels.

You can change the settings by using the `git config`  command.

To give an example:

```
 $ git config --system user.name "Super Unknown"
 $ git config --global user.name "John Doe"
```

To set project specific settings, you have to change to the corresponding working directory first (the directory that contains the .git folder) first and the run for example: 
 
```
$ git config user.name "My Pseudonym"
```

You can list your active stetting by running 

```
$ git config --list 
```

Of course, the output depends on where you are on your system. 

### Lineending behavior

Now back to the lineending problem: 

Open a Terminal in you wprig directory and run  

```
$ git config --list 
```

If the output contains a line

```
core.autocrlf true
```

This setting is responsible for the lineending replacements and so the reason for your troubles.

To change the behavior within your project run  

$ git config core.autocrlf false

You can also change the behavior for all you projects    

$ git config --global core.autocrlf false

but keep in mind that the replacement behavior might be usefull in none wp-rig projects. 






The following article describes how to change the standard line-ending behavior for all contributors of a project. 
 
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

So maybe the Wp-Rig contributors should consider to 

# Adding a file `.gitattributes` to the WP-Rig main folder.
# Add the following content 

```
# Declare files that will always have LF line endings on checkout.
* text eol=lf

# Denote all files that are truly binary and should not be modified.
*.jpg binary
*.png binary
*.gif binary
*.webp binary
```

I'm not sure if that works or but it might be worth a try.
