### ISSUE TITLE
Errors on installation

### ISSUE THREAD

**Issue by fernandofas** [wprig/wprig#734]
I found more errors when installing a new version of WP-RIG.

See below:

`PS C:\xampp\htdocs\mpid\wp-content\themes\wprig> npm run rig-init

> wprig@2.0.1 rig-init C:\xampp\htdocs\mpid\wp-content\themes\wprig
> npm install && composer install

npm WARN babel-jest@27.0.6 requires a peer of @babel/core@^7.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@6.2.1 requires a peer of eslint@^3 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.13.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-hooks@1.6.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended-scss@3.3.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-wordpress@14.0.0 requires a peer of stylelint@^9.5.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-scss@3.9.3 requires a peer of stylelint@^8.0.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.

audited 2203 packages in 6.603s

88 packages are looking for funding
  run `npm fund` for details

found 13 vulnerabilities (6 low, 2 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
'composer' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.1 rig-init: `npm install && composer install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@2.0.1 rig-init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fernandosilva\AppData\Roaming\npm-cache\_logs\2021-07-27T14_54_05_425Z-debug.log`

Any idea how to sort that out?

Cheers,

Fernando

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dthenley** [comment]
Can you check to make sure you have composer installed by opening up your terminal and typing `composer -V`. If composer is installed correctly, you should see a version number.
