### ISSUE TITLE
CMB2 intergration

### ISSUE THREAD

**Issue by erdmann040** [wprig/wprig#744]
## Issue Overview

I use CMB2 in all my projects. Unfortunately I am not able to integrate CMB2 with WP-Rig. The procedure described in the videos does not work here unfortunately. Probably my fault and not bug - but i cant find a solution and CMB2 is pretty common framework, so I think a documented solution would be helpful for many theme developers.   

## Describe your environment

I stayed as close as psoible to Mortens video instructions. WP Rig Installation on Local by Flywheel with Theme-Test-Data imported. OS: Linux (Fedora 32), Browser: Chrome & Firefox, VS Code with plugins Morten recommened.

## Steps to Reproduce

My Composer.json looks like this:

```
{

  "name": "wprig/wprig",

  ...
 
  "config": {

    "platform": {

      "php": "7.0"

    }

  },

  "autoload": {

    "psr-4": {

      "WP_Rig\\WP_Rig\\": "inc"

    },

    "files": ["vendor/cmb2/cmb2/init.php"]

  },
  "scripts": {
     ....
  } 
  "require": {

    "cmb2/cmb2": "dev-master",

    "webdevstudios/cmb2-post-search-field": "^0.2.5"

    }

}
```

I added the autoload and the required property because of the CMB2 documentation i found here, that describes how to use CMB2 with Composer:

https://cmb2.io/docs/installation#-if-including-the-library-via-composer-in-psr-4-format-example-antonella-framework 

This actualy seemed to work as long as I was developing on my local system but when I exported the by runing 

`$ npm run bundle`

CMB2 wasn't intergrated in the exported theme. So I installed CMB2 as a plugin on the On the productive WP system. Everything is working this way, but i wish CMB2 would become a part of the exported theme. Is there a way to achieve this?

**Comment by robruiz** [comment]
@erdmann040 - As promised, here you go!
https://wprig.io/documentation/adding-cmb2-to-your-theme/

**Comment by erdmann040** [comment]
Woohooooo! 

Great article. Thank you very much!
