### ISSUE TITLE
WooCommerce is working but can't override WC template

### ISSUE THREAD

**Issue by crobertwatson** [wprig/wprig#746]
## Issue Overview

I've got WooCommerce working on a WP Rig site. I wanted to add some content to the My Account dashboard by using the WooCommerce template override. However, even when I copied dashboard.php from the parent WooCommerce to the theme's woocommerce/myaccount folder, whenever I add even a simple `<h1>Hello world</h1>` to dashboard.php, nothing appears on the front end. Theme support is declared for WooCommerce and I can tell because a) the rest of WooCommerce is functional on the site and b) I did an echo of a boolean test on the code below that is in functions.php to see if it was enabled and it returns true.

    /**
     * Is WooCommerce active?
     *
     * @return boolean
     */
     function woocommerce_active() {
	    return class_exists( 'WooCommerce' );
     }

Here is the `add_support()` function code

        /**
	 * Enable misc WooCommerce theme support
	 *
	 * @since 1.0.0
	 */
	public function add_support() {

		add_theme_support(
			'woocommerce',
			[
				'gallery_thumbnail_image_width' => 150,
			]
		);

		add_theme_support( 'wc-product-gallery-lightbox' );
		add_theme_support( 'wc-product-gallery-slider' );
	}

## Describe your environment

WP Rig

## Steps to Reproduce

1. Put a copy of dashboard.php into woocommerce/myaccount in WP Rig theme
2. Confirm that WC theme support is enabled
3. Insert test output into dashboard.php
4. Reload the My Account page

## Expected Behavior

I expected to see my test string appear on the My Account dashboard content area or within existing output strings for that page.

## Current Behavior

No test messaging appeared on the page.

## Related Issues and/or PRs

https://github.com/wprig/wprig/issues/37

**Comment by robruiz** [comment]
@crobertwatson - I just tested this. Even without theme support enabled, I was able to get the desired results by simply creating the directory structure woocommerce/myaccount/dashboard.php. As stated in the Woocommerce documentation is best practice, I copied the existing template code from plugins/woocommerce/templates/myaccount/dashboard.php, then pasted it in my new newly created file. Then altered some of the text, and it works. 
![wprig-woocommerce-pagetemplates](https://user-images.githubusercontent.com/8173081/131440333-d4bb0916-6a60-49be-af13-e63714a69190.jpg)
