### ISSUE TITLE
Improve Default Mobile Nav

### ISSUE THREAD

**Issue by robruiz** [wprig/wprig#755]
Currently, the default mobile nav in WP Rig gives you a "Menu" button that resides inside the <nav> element. It would be nice if the Menu control when on mobile for the main nav (or any menu for that matter) could be controlled by any button anywhere on the UI. 

Also, currently, a lot of work is needed to convert the mobil menu to something that is more conventional ( full-screen popup, slide-in from side, etc.) in modern themes. It would be great if there was some default CSS already built in to quickly get some other styles of responsive main menus.

**Comment by mvaleno** [comment]
Hi, 

Would it be possible to move the main navigation styles out from global to its own partial? Seem like a part of global.css most anyone would want to customize and it is a bit easier to work on in a partial... 

I did this successfully and it was pretty simple. What are your thoughts on whether or not this is a good idea?

Thank you!
