### ISSUE TITLE
Can't extend any core classes

### ISSUE THREAD

**Issue by fsdevriver** [wprig/wprig#769]
Can't extend any core class like Widget for making a custom widget or custom menu etc

**Comment by dthenley** [comment]
Hey @fsdevriver you should be able to create a new menu in the `inc/Nav_Menus/component.php` file. https://github.com/wprig/wprig/blob/master/inc/Nav_Menus/Component.php

**Comment by dthenley** [comment]
Hey @fsdevriver if you're still having issue please don't hesitate to reach back out. Right now i'm going to go ahead and close this issue
