### ISSUE TITLE
Bug blank page editor with 5.9 .. 

### ISSUE THREAD

**Issue by 6clicks** [wprig/wprig#784]
I made the update to the 5.9 and I have a blank page in the editor? 

my debug log said 

`[26-Jan-2022 14:18:58 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 127.0.0.1:9000 (from HTTP_X_FORWARDED_FOR HTTP header), localhost:9000 (fallback through xdebug.client_host/xdebug.client_port) :-(
`
I roll back to 5.8 and I work again ? any help ?

**Comment by 6clicks** [comment]
I get more deeply and it seems to be from inc/hook.php
the gutenbeg part

**Comment by dthenley** [comment]
Sucks your having issues with the WordPress update.

1. Have you deactivated all your other plugins from the site to rule out any plugin interference.
2. Have you tried running a new copy of wprig to rule out if there is a problem with a wprig customization.

I would also suggest turning on `define( 'WP_DEBUG', true );` in your `wp-congig.php` file. This regular prints the error directly to your screen other than looking into the debug log.

**Comment by 6clicks** [comment]
Thank's for your answer .. I made it by the way I had a bad setting in my local env ... sorry for disturbing ... everything goes better after a good sleep...

**Comment by dthenley** [comment]
You're all good, glad you got it figured out!
