### ISSUE TITLE
Add on/off option for PHPCS in Gulp process.

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#79]
Add a true/false trigger for PHPCS to run in the Gulp process. If a developer already has PHPCS integrated with their code editor, it is superfluous to run it again during the build process.

## Related Issues and/or PRs

#42

**Comment by adamwhitlock1** [comment]
I think this might be a good way to roll, to also address my issue about running PHPCBF during build. This way if you didn't want to fix or look at the errors this would be easy enough to use instead.

**Comment by felixarntz** [comment]
@mor10 According to the above PR, this should be done, or isn't it?

**Comment by ataylorme** [comment]
Addressed by #170
