### ISSUE TITLE
Inline SVG undefined properties

### ISSUE THREAD

**Issue by drikfan** [wprig/wprig#792]
**Describe the bug**
When running `npm run bundle`, inline svgs sometimes are altered and "undefined" is inserted into the svg markup in various places. I have personally seen it occur in the viewBox attribute the most, but also within path data. 

**To Reproduce**
1. add the following svg (twitter icon) to your non bundled theme. (Note, not all svgs cause this issue, so it must have something to do with the actual svg data. It seems possibly linked to floating point values in viewbox and paths ie: `viewBox="0 24 121.9 201.79`
2. Bundle it, inspect the svg and notice the change

### Example SVG that is triggering this behavior:
`<svg width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" role="img" aria-hidden="true" focusable="false">
					<path d="M19.7,3H4.3C3.582,3,3,3.582,3,4.3v15.4C3,20.418,3.582,21,4.3,21h15.4c0.718,0,1.3-0.582,1.3-1.3V4.3 C21,3.582,20.418,3,19.7,3z M8.339,18.338H5.667v-8.59h2.672V18.338z M7.004,8.574c-0.857,0-1.549-0.694-1.549-1.548 c0-0.855,0.691-1.548,1.549-1.548c0.854,0,1.547,0.694,1.547,1.548C8.551,7.881,7.858,8.574,7.004,8.574z M18.339,18.338h-2.669 v-4.177c0-0.996-0.017-2.278-1.387-2.278c-1.389,0-1.601,1.086-1.601,2.206v4.249h-2.667v-8.59h2.559v1.174h0.037 c0.356-0.675,1.227-1.387,2.526-1.387c2.703,0,3.203,1.779,3.203,4.092V18.338z"></path>
				</svg>`

### Output SVG - note the presence of "undefined" in the path data as well as the path data being altered in general. 
`<svg width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" role="img" aria-hidden="true" focusable="false">
					<path d="M22.23,5.924c-0.736,0.326-1.527,0.547-2.357,0.646c0.847-0.508,1.498-1.312,1.804-2.27 c-0.793,0.47-1.671,0.812-2.606,0.996C18.324,4.498,17.257,4,16.077,4c-2.266,0-4.103,1.837-4.103,4.103 c0,0.322,0.036,0.635,0.106,0.935C8.67,8.867,5.647,7.234,3.623,4.751C3.27,5.357,3.067,6.062,3.067,6.814 c0,1.424,0.724,2.679,1.825,3.415c-0.673-0.021-1.305-0.206-1.859-0.513c0,0.017,0,0.034,0,0.05undefined.988,1.414,3.647,3.292,4.023 c-0.344,0.094-0.707,0.144-1.081,0.144c-0.264,0-0.521-0.026-0.772-0.074c0.522,1.63,2.038,2.816,3.833,2.85 c-1.404,1.1-3.174,1.756-5.096,1.756c-0.331,0-0.658-0.019-0.979-0.057c1.816,1.164,3.973,1.843,6.29,1.843 c7.547,0,11.675-6.252,11.675-11.675c0-0.178-0.004-0.355-0.012-0.531C20.985,7.47,21.68,6.747,22.23,5.924z"></path>
				</svg>`

Note the difference in path data. This is occuring upon running `npm run bundle`

**Expected behavior**
Wprig should not parse the inline svg if at all possible. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: all

**Comment by robruiz** [comment]
Depending on where your svg is and how it's being included into the html, it's supposed to be optimizing any kind of image, including SVGs. This is expected behavior. Gulp helps us manage all image optimizations during build.
