### ISSUE TITLE
Fix array to string conversion error

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#80]
When debug is set to true, the following error appears:

> Notice: Array to string conversion in /.../wp-content/themes/wprig/functions.php on line 256

The line in question: 

```php
		$font_families[] = "{$font_name}:{$font_variants}";
``` 
in the function: 
```php
foreach ( $fonts_register as $font_name => $font_variants ) {
	if ( ! empty( $font_variants ) ) {
		$font_families[] = "{$font_name}:{$font_variants}";
	} else {
		$font_families[] = $font_name;
	}
}
```

**Comment by mor10** [comment]
Assigned to @bamadesigner because I think you're the one who ended up writing this function.

**Comment by bamadesigner** [comment]
Fixed. https://github.com/wprig/wprig/commit/6eabbff7d7cffb9a8ab41620471dad6e15ab1a22
