### ISSUE TITLE
Mobile menu obscures content when toggled off

### ISSUE THREAD

**Issue by cwrichardson** [wprig/wprig#805]
**Describe the bug**
The way the global.css file handles toggle-nav prevents accessing the page (e.g., clicking on a link) if the link is more than 300px down the page.

**To Reproduce**
1. Create a menu with a few items in it
2. Create a page that has a few paragraphs of text and put a link in the 2nd or 3rd paragraph
3. Open the page on some mobile device or emulator, such that the link is more than 300px from the top of the page, but not below the heigh of the nav menu
4. try and click on the link

**Expected behavior**
When toggled off, the nav menu should have no impact on site interaction

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS, but probably all
 - Browser at least Chrome and Safari
 - Version any

**Smartphone (please complete the following information):**
 - Device: iPhone 12, but probably all
 - OS: iOS 15.4.1 but probably all
 - - Safari, but probably all
 - probably all
 - 
**Additional context**
@Spleeding1 suggested this can be fixed by setting visibility on and off — which is true, and probably what we should do. But if we do that, we should probably remove the `transition` on line 343 of global.css, since that won't have any impact once we set `visibility: hidden`.

**Comment by Spleeding1** [comment]
@cwrichardson If i remember correctly, the nav menu doens't fade without the transition. It either just appears or just disappears. Feel free to check it. I could be mistaken.
