### ISSUE TITLE
Running production version changes part of string to 'undefined'

### ISSUE THREAD

**Issue by keramzyt** [wprig/wprig#807]
**Describe the bug**
When I run 'npm run bundle' in resulting php file, part of numeric string is changed to 'undefined'

**To Reproduce**
1. In php file declare string variable containing '20001' string 
2. In terminal run 'npm run bundle'
3. See error

**Expected behavior**
String should not be changed.

**Screenshots**
See attached screenshots

**Desktop (please complete the following information):**
 - OS: [macOS Monterey ver. 12.4]
 - MacBook M1
 - PHP [7.4.28]
 - Terminal

![Screenshot 2022-06-30 at 11 33 05](https://user-images.githubusercontent.com/22238141/176649418-3536b92b-d90a-4b3a-82df-24e1c5081c7a.png)
![Screenshot 2022-06-30 at 11 38 52](https://user-images.githubusercontent.com/22238141/176649429-b4237f54-c081-466e-9ac9-e160ee9fdedb.png)

**Additional context**

**Comment by dthenley** [comment]
Hey @keramzyt sorry you're getting errors when trying to bundle your theme. Which file and what is the directory you are experiencing this issue?

**Comment by keramzyt** [comment]
Hi @dthenley, it's my custom template part file under 'template-parts -> content' directory. This is strange but it concerns a specific string '20001' as you can see on screenshots. I tried to use double quotes but the error persists, as well for just clean '20001' string. After each bundle run I have to manually correct affected file. 
I just checked file under main theme directory (functions.php) and error persists.
![Screenshot 2022-06-30 at 22 01 04](https://user-images.githubusercontent.com/22238141/176769707-12eda950-2e8f-4dfe-8be7-2cfdbf5202e2.png)
![Screenshot 2022-06-30 at 22 05 52](https://user-images.githubusercontent.com/22238141/176769715-79ac1de9-c657-4199-bcc5-aa93b91b0a6b.png)

**Comment by dthenley** [comment]
@keramzyt do you have a link to your repo, I'd be happy to look at it to see if I can help troubleshoot it.
