### ISSUE TITLE
Add the ability to generate an SSL certificate with gulp

### ISSUE THREAD

**Issue by ataylorme** [wprig/wprig#81]
See #57 for background information. Generating SSL certs requires specialized knowledge and can be cumbersome to get correct. By creating a gulp task that automates generating an SSL certificate we can take this burden off WP Rig users. 

Additionally, the gulp and BrowserSync config can be updated to automatically turn on HTTPS when a generated cert is present in the default directory. The step of trusting the cert will still be manual, however.

**Comment by ataylorme** [comment]
https://www.npmjs.com/package/pem looks promising

**Comment by bamadesigner** [comment]
Completed by #92.
