### ISSUE TITLE
Help instalation

### ISSUE THREAD

**Issue by dackr** [wprig/wprig#811]
**Describe the bug**
I do everything for the installation process and it hangs when I start the next step npm run dev, as you can see in the code, it stays there and it doesn't matter, does this happen to someone?

> wprig@2.0.1 rig-init
> npm install && composer install

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-jsx-a11y@6.2.1
npm WARN Found: eslint@6.8.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^6.0.1" from the root project
npm WARN   7 more (babel-eslint, eslint-config-standard, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^3 || ^4 || ^5" from eslint-plugin-jsx-a11y@6.2.1
npm WARN node_modules/eslint-plugin-jsx-a11y
npm WARN   eslint-plugin-jsx-a11y@"^6.2.1" from @wordpress/eslint-plugin@2.3.0
npm WARN   node_modules/@wordpress/eslint-plugin
npm WARN 
npm WARN Conflicting peer dependency: eslint@5.16.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^3 || ^4 || ^5" from eslint-plugin-jsx-a11y@6.2.1
npm WARN   node_modules/eslint-plugin-jsx-a11y
npm WARN     eslint-plugin-jsx-a11y@"^6.2.1" from @wordpress/eslint-plugin@2.3.0
npm WARN     node_modules/@wordpress/eslint-plugin
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-react@7.13.0
npm WARN Found: eslint@6.8.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^6.0.1" from the root project
npm WARN   7 more (babel-eslint, eslint-config-standard, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0" from eslint-plugin-react@7.13.0
npm WARN node_modules/eslint-plugin-react
npm WARN   eslint-plugin-react@"^7.12.4" from @wordpress/eslint-plugin@2.3.0
npm WARN   node_modules/@wordpress/eslint-plugin
npm WARN 
npm WARN Conflicting peer dependency: eslint@5.16.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0" from eslint-plugin-react@7.13.0
npm WARN   node_modules/eslint-plugin-react
npm WARN     eslint-plugin-react@"^7.12.4" from @wordpress/eslint-plugin@2.3.0
npm WARN     node_modules/@wordpress/eslint-plugin
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-react-hooks@1.6.0
npm WARN Found: eslint@6.8.0
npm WARN node_modules/eslint
npm WARN   dev eslint@"^6.0.1" from the root project
npm WARN   7 more (babel-eslint, eslint-config-standard, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0" from eslint-plugin-react-hooks@1.6.0
npm WARN node_modules/eslint-plugin-react-hooks
npm WARN   eslint-plugin-react-hooks@"^1.6.0" from @wordpress/eslint-plugin@2.3.0
npm WARN   node_modules/@wordpress/eslint-plugin
npm WARN 
npm WARN Conflicting peer dependency: eslint@5.16.0
npm WARN node_modules/eslint
npm WARN   peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0" from eslint-plugin-react-hooks@1.6.0
npm WARN   node_modules/eslint-plugin-react-hooks
npm WARN     eslint-plugin-react-hooks@"^1.6.0" from @wordpress/eslint-plugin@2.3.0
npm WARN     node_modules/@wordpress/eslint-plugin
npm WARN deprecated fsevents@1.2.8: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated flatten@1.0.2: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request-promise-native@1.0.7: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated stylelint-config-wordpress@14.0.0: This package has been deprecated, please use @wordpress/stylelint-config or @wordpress/scripts
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.5: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated babel-eslint@10.0.2: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated axios@0.19.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@3.2.0: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 1849 packages, and audited 1850 packages in 2m

14 packages are looking for funding
  run `npm fund` for details

92 vulnerabilities (41 moderate, 40 high, 11 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 38 installs, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (3.5.8): Extracting archive
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.7.1): Extracting archive
  - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
  - Installing mockery/mockery (1.3.3): Extracting archive
  - Installing antecedent/patchwork (2.1.12): Extracting archive
  - Installing brain/monkey (2.6.0): Extracting archive
  - Installing myclabs/deep-copy (1.7.0): Extracting archive
  - Installing phar-io/version (1.0.1): Extracting archive
  - Installing phar-io/manifest (1.0.1): Extracting archive
  - Installing phpcompatibility/php-compatibility (9.3.5): Extracting archive
  - Installing phpdocumentor/reflection-common (1.0.1): Extracting archive
  - Installing phpdocumentor/type-resolver (0.5.1): Extracting archive
  - Installing sebastian/recursion-context (3.0.1): Extracting archive
  - Installing sebastian/exporter (3.1.3): Extracting archive
  - Installing sebastian/diff (2.0.1): Extracting archive
  - Installing sebastian/comparator (2.1.3): Extracting archive
  - Installing symfony/polyfill-ctype (v1.19.0): Extracting archive
  - Installing webmozart/assert (1.9.1): Extracting archive
  - Installing phpdocumentor/reflection-docblock (4.3.4): Extracting archive
  - Installing doctrine/instantiator (1.0.5): Extracting archive
  - Installing phpspec/prophecy (v1.10.3): Extracting archive
  - Installing theseer/tokenizer (1.1.3): Extracting archive
  - Installing sebastian/version (2.0.1): Extracting archive
  - Installing sebastian/environment (3.1.0): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.2): Extracting archive
  - Installing phpunit/php-token-stream (2.0.2): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing phpunit/php-file-iterator (1.4.5): Extracting archive
  - Installing phpunit/php-code-coverage (5.3.2): Extracting archive
  - Installing phpunit/php-timer (1.0.9): Extracting archive
  - Installing phpunit/phpunit-mock-objects (5.0.10): Extracting archive
  - Installing sebastian/global-state (2.0.0): Extracting archive
  - Installing sebastian/object-reflector (1.1.2): Extracting archive
  - Installing sebastian/object-enumerator (3.0.4): Extracting archive
  - Installing sebastian/resource-operations (1.0.0): Extracting archive
  - Installing wp-coding-standards/wpcs (2.3.0): Extracting archive
  - Installing phpunit/phpunit (6.5.14): Extracting archive
  - Installing yoast/phpunit-polyfills (1.0.3): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility,../../wp-coding-standards/wpcs

xxxxxx@MacBook-Pro-de-xxxxxxx-2 wprig % npm run dev     

> wprig@2.0.1 dev
> gulp

[01:14:26] Requiring external module @babel/register
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[01:14:31] Using gulpfile ~/Local Sites/wprig/app/public/wp-content/themes/wprig/gulpfile.babel.js
[01:14:31] Starting 'default'...
[01:14:31] Starting 'cleanCSS'...
[01:14:31] Finished 'cleanCSS' after 38 ms
[01:14:31] Starting 'cleanJS'...
[01:14:31] Finished 'cleanJS' after 13 ms
[01:14:31] Starting 'php'...
[01:14:31] Starting 'images'...
[01:14:31] Starting 'scripts'...
[01:14:31] Starting 'styles'...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[01:14:33] gulp-imagemin: Minified 0 images
[01:14:33] Finished 'images' after 2.31 s
[01:14:40] Finished 'scripts' after 8.44 s
As you can see here it stays and does not advance what can I do please.

**Comment by dthenley** [comment]
It looks like it's getting stuck at the script run. if this is an older version there was an issue where the theme is looking for a custom.js file. You might try adding that file to the script folder or removing the mention of the file from the /inc/scripts/component.php file

**Comment by dackr** [comment]
thanks for your help @dthenley, I have deactivated all the component and the problem continues, install version 2.2.1

**Comment by robruiz** [comment]
Im not seeing any errors here. What exactly is the issue?

**Comment by websupergirl** [comment]
@dackr did you ever solve this? I am seeing the same problem. Are you on an M1 chip by chance?

@robruiz the issue is that the production build gets to scripts and just stays there - never builds the files and never finishes the process.

@dthenley this is v2.2.1 which already has the call for the custom.min.js file removed.

**Comment by websupergirl** [comment]
FYI this is what I get on "npm run bundle --verbose" - it never finishes the build.

```
> wprig@2.0.1 bundle
> cross-env NODE_ENV=production gulp bundleTheme

npm http fetch GET 200 https://registry.npmjs.org/npm 14ms (cache hit)
[01:27:34] Requiring external module @babel/registerregistry.npmjs.org/npm 14ms (cache hit)
Browserslist: caniuse-lite is outdated. Please run next command `npm update`4ms (cache hit)
[01:27:35] Using gulpfile ~/Localwp/3mwtest/app/public/wp-content/themes/3mw-template/gulpfile.babel.js
[01:27:35] Starting 'bundleTheme'...
[01:27:35] Starting 'prodPrep'...
[01:27:35] Creating the production theme directory /Users/nikole/Localwp/3mwtest/app/public/wp-content/themes/threemw-base
[01:27:35] Finished 'prodPrep' after 30 ms
[01:27:35] Starting 'php'...
[01:27:35] Starting 'scripts'...
[01:27:35] Starting 'images'...
[01:27:35] Starting 'styles'...etch GET 200 https://registry.npmjs.org/npm 14ms (cache hit)
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[01:27:36] gulp-imagemin: Minified 1 image (saved 20 B - 22.7%)mjs.org/npm 14ms (cache hit)
[01:27:37] Finished 'images' after 1.86 s00 https://registry.npmjs.org/npm 14ms (cache hit)
[01:27:37] Finished 'scripts' after 2.07 s0 https://registry.npmjs.org/npm 14ms (cache hit)
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠦ : http fetch GET 200 https://registry.npmjs.org/npm 14ms (cache hit)
```

**Comment by websupergirl** [comment]
FYI this is what I get on "npm run bundle --verbose" - it never finishes the build.

```
> wprig@2.0.1 bundle
> cross-env NODE_ENV=production gulp bundleTheme

npm http fetch GET 200 https://registry.npmjs.org/npm 14ms (cache hit)
[01:27:34] Requiring external module @babel/registerregistry.npmjs.org/npm 14ms (cache hit)
Browserslist: caniuse-lite is outdated. Please run next command `npm update`4ms (cache hit)
[01:27:35] Using gulpfile ~/Localwp/test/app/public/wp-content/themes/template/gulpfile.babel.js
[01:27:35] Starting 'bundleTheme'...
[01:27:35] Starting 'prodPrep'...
[01:27:35] Creating the production theme directory /Users/nikole/Localwp/test/app/public/wp-content/themes/base
[01:27:35] Finished 'prodPrep' after 30 ms
[01:27:35] Starting 'php'...
[01:27:35] Starting 'scripts'...
[01:27:35] Starting 'images'...
[01:27:35] Starting 'styles'...etch GET 200 https://registry.npmjs.org/npm 14ms (cache hit)
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[01:27:36] gulp-imagemin: Minified 1 image (saved 20 B - 22.7%)mjs.org/npm 14ms (cache hit)
[01:27:37] Finished 'images' after 1.86 s00 https://registry.npmjs.org/npm 14ms (cache hit)
[01:27:37] Finished 'scripts' after 2.07 s0 https://registry.npmjs.org/npm 14ms (cache hit)
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠦ : http fetch GET 200 https://registry.npmjs.org/npm 14ms (cache hit)
```

**Comment by websupergirl** [comment]
I used nvm to test other versions of node, none of them worked.
node v16.15.1 (npm v8.11.0)
node v14.19.3 (npm v6.14.17)
node v12.22.12 (npm v6.14.16)

**Comment by websupergirl** [comment]
I tested a build of the exact same files on a non-M1 MBP and the build works as intended. I was concerned about this as I have had multiple projects not build since updating to the M1 chipset.

**Comment by robruiz** [comment]
@websupergirl - this is great. Thanks. Sorry it took me a while to notice this.

**Comment by maguijo** [comment]
I just ran into this issue myself exactly as the OP describes. Using the VS code integrated terminal, run "npm run dev", it hangs after finishing the scripts task. @websupergirl  I am in on an m1 chip macbook air. What worked though was to use the mac terminal, not the vscode terminal. Using that, it ran, finished and seems to be working perfectly.

**Comment by robruiz** [comment]
I'm still trying to work through this. I finally found someone I know that is on MacOS Monterey that can help me get some visibility into this. It seems that when he tries to run npm run dev in the Mac terminal from WP Rig directory, everything works great. It's when he is trying to run it from another terminal (in this case PHPStorm, but I assume the same result would occur from VS Code) that the theme CSS files don't build. I also think it might have something to do with PHP_Codesniffer. It surprises me that things fail so silently. Anyone know where I might be able to get more logging info when this fail occurs? It shocks me that something php-related would prevent Babel from transpiling the CSS. Has anyone had any luck looking into this? I don't think the issue is specific to M1, I think it might be specific to Monterey since they removed php from the core OS. Thoughts?

**Comment by maguijo** [comment]
> I'm still trying to work through this. I finally found someone I know that is on MacOS Monterey that can help me get some visibility into this. It seems that when he tries to run npm run dev in the Mac terminal from WP Rig directory, everything works great. It's when he is trying to run it from another terminal (in this case PHPStorm, but I assume the same result would occur from VS Code) that the theme CSS files don't build. I also think it might have something to do with PHP_Codesniffer. It surprises me that things fail so silently. Anyone know where I might be able to get more logging info when this fail occurs? It shocks me that something php-related would prevent Babel from transpiling the CSS. Has anyone had any luck looking into this? I don't think the issue is specific to M1, I think it might be specific to Monterey since they removed php from the core OS. Thoughts?

If you can explain or send me a link to instructions, I'm happy to give you all the logging info you want for when this happens. I left my mac set up stuck on this error so it's ready to roll out some logs if I knew how to do that (in VS code)

**Comment by websupergirl** [comment]
I thought there was more that I changed here but I know one of the big ones on the M1 to get it to compile was changing these lines in the composer.json:
`"php": ">=7.4"`
`"dealerdirect/phpcodesniffer-composer-installer": "^0.7.2"`
`"phpunit/phpunit": "^9"`

I still haven't found a fix for
`"yoast/phpunit-polyfills": "^1.0"`
So I removed that line for now.

And then in package.json, this line was updated:
`"@babel/preset-env": "^7.19.3"`

It gives me some errors I need to work with on the M1 but at least the whole thing builds a theme.

**Comment by dackr** [comment]
Hello friends, I left the development with wp rig for the moment, because it didn't work for me on windows or mac, some time I managed to make something work but you make some modifications to the composer.json that @websupergirl did but it didn't really work I ask the team development manager who can help us and give solutions

**Comment by robruiz** [comment]
> Hello friends, I left the development with wp rig for the moment, because it didn't work for me on windows or mac, some time I managed to make something work but you make some modifications to the composer.json that @websupergirl did but it didn't really work I ask the team development manager who can help us and give solutions

The issues being covered in this thread are very situational and specific to MacOS and specifically either M1, Monterey, or both. It's still kind of unclear until I can find someone to help me test through some things.

**Comment by robruiz** [comment]
I have successfully narrowed down the issue here to PHPCS. It seems we currently get PHPCS because it is a dependency of   dealerdirect/phpcodesniffer-composer-installer. However, the dealerdirect package hasn't been updated to require the latest version of PHPCS from squizlabs. They recently pushed out a new version (3.7) that addresses the issues around PHP 8.1. So, I simply added "squizlabs/php_codesniffer": "3.*" as a dev dependency and boom, everything worked. Now my question is, do we really need the dealerdirect package if we are getting PHPCS straight from Squiz? I'm inclined to think no, but I could be wrong. 

So, we have 2 options here that I know both work, in either case, squizlabs must be added as a dependency:
A. Remove the dealer direct package and all references to it from the composer.json file. 
B. Simply add squizlabs as a dependency in addition to dealer direct. 

I hope to push out a release to WP Rig to address this issue some time this week, so please weigh in on this. My only concern here is that by removing dealerdirect we might be removing some PHP coding standards checks from the build process. With that said though, I haven't noticed a difference in what is getting caught when PHPCS runs when I removed it. Thanks for your patience everyone.

**Comment by websupergirl** [comment]
@robruiz I have both non-M1 Monterey and M1 Monterey if you need me to pull a branch and run a test on it.

And yes my findings were the same as yours, that this points to be the issue. I'd rather add the other package and bump the min version higher than to take it out, I think.

**Comment by robruiz** [comment]
@websupergirl - want to give this a go?
https://github.com/wprig/wprig/tree/bump-phpcs

**Comment by Spleeding1** [comment]
Going through the gulp file, my device hung on php and css. The following would go through to launch the dev server.

```
export const firstRun = series(
	cleanCSS,
	cleanJS,
	parallel(
		// php,
		images,
		// series(styles, editorStyles),
		scripts
	),
	serve,
	watch
);
```

caniuse-ite was flagged outdated.

**Comment by robruiz** [comment]
@Spleeding1  - can I get you to pull down the bump-phpcs branch and give it a go please?

**Comment by websupergirl** [comment]
@robruiz I am getting hung on "translate" in the build of the bump-phpcs branch on M1.

<img width="554" alt="Screen Shot 2022-10-13 at 3 15 21 PM" src="https://user-images.githubusercontent.com/38568655/195720842-ed968853-6dc1-44de-ba08-1beef526ab1e.png">

**Comment by websupergirl** [comment]
@robruiz the build went just fine on non-M1 Monterey.

I will say the non-M1 is running PHP 7.4.30 and the M1 has PHP 8.1.9.

**Comment by websupergirl** [comment]
@robruiz I switched to an arm64 brew of php 7.4 on the M1 and it did build successfully.

It just has to be installed like this
`arch -arm64 brew install php@7.4`
and then update the paths in .zshrc.
