### ISSUE TITLE
autoprefixer not working

### ISSUE THREAD

**Issue by flegfleg** [wprig/wprig#83]
## Issue Overview
Autoprefixer does not seem to run

## Describe your environment
wprig 1.03

## Steps to Reproduce

1. Edit browserlist:

```
		browserslist: [ // See https://github.com/browserslist/browserslist
			'> 0.5%',
			'last 2 versions',
			'Firefox ESR',
			'not dead'
		],
```

2. `npm run build`

## Expected Behavior
Prefixes for IE11 added in style.css

## Current Behavior
No prefixes added.

**Comment by mor10** [comment]
This has been fixed in `v2.0 alpha`. Closing for now. If the problem persists in `v2.0 alpha`, please reopen this issue.
