### ISSUE TITLE
I installed but it stays in scripts

### ISSUE THREAD

**Issue by dackr** [wprig/wprig#833]
**Describe the bug**
I installed but it stays in scripts

This is what I did and it comes out like this

MAC@MAC wprig-southerntheme % npm run rig-init

> wprig@2.3 rig-init
> npm install && composer install

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated stylelint-config-wordpress@14.0.0: This package has been deprecated, please use @wordpress/stylelint-config or @wordpress/scripts
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated trim@0.0.1: Use String.prototype.trim() instead
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 2123 packages, and audited 2124 packages in 2m

166 packages are looking for funding
  run `npm fund` for details

53 vulnerabilities (16 moderate, 33 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Package operations: 38 installs, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (3.5.8): Extracting archive
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.7.1): Extracting archive
  - Installing hamcrest/hamcrest-php (v2.0.1): Extracting archive
  - Installing mockery/mockery (1.3.3): Extracting archive
  - Installing antecedent/patchwork (2.1.12): Extracting archive
  - Installing brain/monkey (2.6.0): Extracting archive
  - Installing myclabs/deep-copy (1.7.0): Extracting archive
  - Installing phar-io/version (1.0.1): Extracting archive
  - Installing phar-io/manifest (1.0.1): Extracting archive
  - Installing phpcompatibility/php-compatibility (9.3.5): Extracting archive
  - Installing phpdocumentor/reflection-common (1.0.1): Extracting archive
  - Installing phpdocumentor/type-resolver (0.5.1): Extracting archive
  - Installing sebastian/recursion-context (3.0.1): Extracting archive
  - Installing sebastian/exporter (3.1.3): Extracting archive
  - Installing sebastian/diff (2.0.1): Extracting archive
  - Installing sebastian/comparator (2.1.3): Extracting archive
  - Installing symfony/polyfill-ctype (v1.19.0): Extracting archive
  - Installing webmozart/assert (1.9.1): Extracting archive
  - Installing phpdocumentor/reflection-docblock (4.3.4): Extracting archive
  - Installing doctrine/instantiator (1.0.5): Extracting archive
  - Installing phpspec/prophecy (v1.10.3): Extracting archive
  - Installing theseer/tokenizer (1.1.3): Extracting archive
  - Installing sebastian/version (2.0.1): Extracting archive
  - Installing sebastian/environment (3.1.0): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.2): Extracting archive
  - Installing phpunit/php-token-stream (2.0.2): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing phpunit/php-file-iterator (1.4.5): Extracting archive
  - Installing phpunit/php-code-coverage (5.3.2): Extracting archive
  - Installing phpunit/php-timer (1.0.9): Extracting archive
  - Installing phpunit/phpunit-mock-objects (5.0.10): Extracting archive
  - Installing sebastian/global-state (2.0.0): Extracting archive
  - Installing sebastian/object-reflector (1.1.2): Extracting archive
  - Installing sebastian/object-enumerator (3.0.4): Extracting archive
  - Installing sebastian/resource-operations (1.0.0): Extracting archive
  - Installing wp-coding-standards/wpcs (2.3.0): Extracting archive
  - Installing phpunit/phpunit (6.5.14): Extracting archive
  - Installing yoast/phpunit-polyfills (1.0.3): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility,../../wp-coding-standards/wpcs

MAC@MAC wprig-southerntheme % npm run dev

> wprig@2.3 dev
> gulp

[16:56:11] Requiring external module @babel/register
[16:56:15] Using gulpfile ~/Local Sites/southern-theme/app/public/wp-content/themes/wprig-southerntheme/gulpfile.babel.js
[16:56:15] Starting 'default'...
[16:56:15] Starting 'cleanCSS'...
[16:56:15] Finished 'cleanCSS' after 32 ms
[16:56:15] Starting 'cleanJS'...
[16:56:15] Finished 'cleanJS' after 7.9 ms
[16:56:15] Starting 'php'...
[16:56:15] Starting 'images'...
[16:56:15] Starting 'scripts'...
[16:56:16] Starting 'styles'...
[16:56:20] gulp-imagemin: Minified 1 image (saved 20 B - 22.7%)
[16:56:24] Finished 'images' after 8.52 s
[16:56:25] Finished 'scripts' after 9.25 s

there it stays and does not run anymore.

Please help me.

**Comment by robruiz** [comment]
I installed from scratch just now and it worked for me. What version of Node/npm you running? Are you trying to run it Ina container by chance?

**Comment by dackr** [comment]
node v16.16.0
NPM 8.11.0
thanks for your help

**Comment by robruiz** [comment]
If this is happening on PHP 8.1+, this is expected. WP Rig does not yet support 8.1+
