### ISSUE TITLE
watch process freezes after "Finished 'editorStyles'.... "

### ISSUE THREAD

**Issue by zedebugger** [wprig/wprig#836]
### Discussed in https://github.com/wprig/wprig/discussions/835

<div type='discussions-op-text'>

<sup>Originally posted by **zedebugger** June 16, 2023</sup>
Hi,
Over the years I've built about one site a year with wprig, and I have never had this issue below:

Whenever I change a watched file e.g. a CSS file and the browsersync watch process is started to reload the browser with my changes, the process hangs at "Finished 'editorStyles' after xx ms". 

I can build and I can bundle but in the 'npm run dev'  process it always hangs and 9 times out of 10 it never finishes reloading the browser.

I have no idea how to troubleshoot this. Does anyone have an idea?

WPRIG 2.3
Debian 11
nodejs 12.22.12
node 16.13.0
npm 8.1.0
composer 2.0.9
vscode  </div>

**Comment by robruiz** [comment]
Can others confirm this is happening to them as well? I can't seem to replicate. Maybe this issue is isolated to Linux?

**Comment by robruiz** [comment]
I'm going to assume you are using PHP 8.1+, which is currently not supported. Please correct me if I am wrong.
