### ISSUE TITLE
mobile menu clickable under text when hamburger menu is folded up

### ISSUE THREAD

**Issue by zedebugger** [wprig/wprig#837]
**Describe the bug**
When a new project is started, the mobile view with hamburger menu does not show the menu itself, but it "exists on the page" and ghost menu entries (ghost because they are invisible) are clickable if you click on the site text.

**To Reproduce**
1. Load a new project
2. Create landing page with lorem ipsum text
3. Create a menu
4. Launch the site in mobile dimensions view - do not activate/show hamburger menu - and hover with the mouse and you will find the ghost menu entries that are clickable

**Expected behavior**
Not to be able to find and click ghost menu entries

**Desktop (please complete the following information):**
 - OS: Win10 and Debian
 - Browser chrome, firefox
 - Version latest

**Smartphone (please complete the following information):**
 - Device: android and iPad

**Comment by robruiz** [comment]
Sorry, this one slipped by me somehow. I will try to reproduce and fix when I get s chance.

**Comment by robruiz** [comment]
@zedebugger - I am starting to work on another issue that overlaps with this one some. I am having a hard time exactly understanding what you are getting at here. I don't know what you mean by "ghost" menu entries and I am also unfamiliar with where you can activate/deactivate show hamburger menu. Please help me understand this a bit better as I would like to get this issue addressed next. Thanks.

**Comment by robruiz** [comment]
@zedebugger - how are you creating your nav menu? With the gutenberg navigation block? Are you using the [full] site editor to create your header and nav?

**Comment by robruiz** [comment]
I believe this was addressed in the latest release - v2.3.1
