### ISSUE TITLE
javascript compilation question – browser support

### ISSUE THREAD

**Issue by flegfleg** [wprig/wprig#85]
## Issue Overview
Is wprig supposed to compile js for the browser specified in themconfig.js "browserlist"?  

## Steps to Reproduce

wprig1.03 without any modifications. 

```
		browserslist: [ // See https://github.com/browserslist/browserslist
			'> 1%',
			'last 2 versions'
		],
```

## Expected Behavior

Navigation dropdown should work in IE/Edge

## Current Behavior
Javascript Error on Edge40, IE11
```
Object doesn't support property or method 'forEach'
navigation.js (1, 217)
```

**Comment by mor10** [comment]
The browser support system has been updated for `v2.0 alpha`. Please test on that branch and see if problem persists. Closing for now, but feel free to reopen if problem is still there in the new version.
