### ISSUE TITLE
Don't style classes used for structured data

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#86]
Classes used for structured data should not be part of the stylesheet. Having structured data or not should not have an influence on the appearance of the site.

Related issues from Underscores:

- [Don't style hatom classes](https://github.com/Automattic/_s/issues/930)
- [Remove Microformat Classes from CSS](https://github.com/Automattic/_s/issues/1268)

**Comment by mor10** [comment]
Good issue. Are you interested in contributing with a PR, or highlight which rules you'd like to see changed?

**Comment by benoitchantre** [comment]
Yes. I’ll either add some comments or work on a PR next week.

**Comment by benoitchantre** [comment]
I'll try to work on it this week.

**Comment by benoitchantre** [comment]
At the moment, WP Rig has styles on the following classes related to [microformats](http://microformats.org/wiki/hentry):

- `hentry`
- `entry-title`
- `entry-content`
- `entry-summary`
- `updated`
- `published`

The only class not added by WP Rig is `hentry` (added by `post_class()`).

I would like to see styles removed from `hentry`, `entry-title`, `entry-content` and `entry-summary`.
This involves to add new classnames as replacements where `entry-title`, `entry-content` and `entry-summary` are used in the templates. These new classnames may depend on #109.

**Comment by miklb** [comment]
I wouldn’t remove the microformat classes, just add new styling hooks

**Comment by benoitchantre** [comment]
At the moment, the idea is not to remove the microformat classes, only to move styles to other classes. In a second step, structured data could be added with JSON-LD ([recommended by Google](https://developers.google.com/search/docs/guides/sd-policies)) instead of microformats.
