### ISSUE TITLE
[Question/Feedback] Good tools, why so opiniated ?

### ISSUE THREAD

**Issue by MarieComet** [wprig/wprig#87]
## Issue Overview
Not an issue but a question.
WPRig is very good boilerplate with useful tools to create a good theme and thanks for that; but why stylesheets are so much opiniated ? (fonts, colors, header).
I think, before test it, I saw it more like a starter theme, without decorative styles.

**Comment by mor10** [comment]
WP Rig provides a minimum viable stylesheet to give designers and developers a place to start from. The stylesheets are minimal, and the most significant elements such as the overall layout and menu are controlled using flexbox and CSS grid making them easy to alter. If you don't want to use the minimal styles provided, you can simply remove them and build your own from scratch. WP Rig provides a framework. You can change it in any way that suits your particular development flow.

**Comment by MarieComet** [comment]
Thanks @mor10 for your answer.

> If you don't want to use the minimal styles provided, you can simply remove them and build your own from scratch
Yes, that's what I'm doing.
I'm used to from scratch, with Underscore for example, that's why I was surprised; but yes you're right, removing the style of WP Rig is simple.
