### ISSUE TITLE
Make conversion of CSS custom properties optional

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#91]
Right now, CSS custom properties are automatically rewritten to verbose CSS using the `/dev/config/cssVariables.json` file via `postcssPresetEnv`. This should be an on-by-default option that a developer can toggle off in `/dev/config/themeConfig.js`. Something like 

```
convertVariables: true,
```

If this setting (or something like it) is set to `false`, the entire `features` section of `postcssPresetEnv` should be disabled: https://github.com/wprig/wprig/blob/v1.1/gulp/styles.js#L38-L47.

If the developer chooses to not convert variables, they will need to use true variables in CSS and contents of `/dev/config/cssVariables.json` will not be read by the Gulp task at all meaning calling it in will be irrelevant. Which means some of the watch behavior would change as well.

This is all in preparation for a not-too-distant future where CSS custom properties actually work properly.

Not sure exactly what that logic would look like in the gulp task.

**Comment by theharshin** [comment]
Any documentation for this option would be a great help 😃
