### ISSUE TITLE
menu not showing up only menu button which does not work.

### ISSUE THREAD

**Issue by hazephase** [wprig/wprig#95]
## Issue Overview

after a fresh install I see that there is also a menu button and the main menu on desktop is set to display:none; The menu button also does not work.

## Describe your environment

I Set up local by flywheel and I am using PHPstorm. 

## Steps to Reproduce

1. add the files to a folder in themes folder 
2. run npm install 
3. run npm start build
4. activate the theme

## Expected Behavior

The desktop should have the long menu and the mobile should have a button that displays the menu

## Current Behavior

can only see the menu button on desktop and mobile and the button does not work

## Possible Solution

edit the CSS properties

**Comment by mor10** [comment]
Will check.

**Comment by alexjgustafson** [comment]
Menu is working correctly for me on a fresh install.

**Comment by bamadesigner** [comment]
I cannot reproduce this issue. Please re-open if you're still experiencing issues @hazephase. Thanks!
