### ISSUE TITLE
howto exclude specific image from gulp processing?

### ISSUE THREAD

**Issue by niksfirefly** [wprig/wprig#98]
## Issue Overview

howto exclude specific image from gulp processing?

**Comment by mor10** [comment]
There is currently no method for this. The hacky way around it is to place the image in the root folder.

**Comment by niksfirefly** [comment]
nope
images from dev root folder are also processed
for now i simply edited images paths
`'!dev/**/excluded.{jpg,JPG,png,svg}'`

what do you think about:
https://github.com/gulpjs/gulp/blob/master/docs/recipes/split-tasks-across-multiple-files.md
so anybody can add custom build tasks
or
https://www.npmjs.com/package/gulp-filter
to exclude certain files from processing?

regards
