### ISSUE TITLE
syncing theme as it is in development dir to remote server?

### ISSUE THREAD

**Issue by niksfirefly** [wprig/wprig#99]
## Issue Overview

Is it acceptable to rsync theme files - generated with npm build - to remote staging server?
I noticed some cache issues with css but other than that it works fine.
I want to use 

`npm run bundle`

and theme.zip only for production when theme is ready.

regards

**Comment by mor10** [comment]
I have done this (while excluding the `./node_modules/` and `./vendor/` folders) and it works, though you end up syncing a lot of unnecessary files that way. In most situations I use the `npm run bundle` process with the `export compress ` setting set to `false` in `./dev/config/themeConfig.js`. Then I sync the "clean" bundle folder to the live site.

**Comment by niksfirefly** [comment]
wow nice trick! thx :)
